namespace XREngine.Rendering.Commands;

/// <summary>
/// Cumulative S13a counters captured with independent atomic reads. Compare two
/// snapshots to observe a window; fields do not represent one atomic frame.
/// </summary>
public readonly record struct S13aPublicationTelemetrySnapshot(
    bool Enabled, long StopwatchFrequency, long SnapshotSequence, long CapturedTimestamp,
    long DirtyIdentityNotifications,
    long DirtyOtherNotifications, long DirtyAlreadySet, long ManualDirty,
    long QueueAdds, long QueueDuplicates, long QueueClean, long SwapCount,
    long SwapQueued, long SwapCallbacks, long SwapAuthorityYields,
    long MeshUpdateCalls, long MeshUpdateChanged, long MeshUpdateUnchanged,
    long MeshUpdateFailed,
    long MeshUpdateWaitTicks, long MeshUpdateBodyTicks, long MeshUpdateHeldTicks,
    long MeshUpdateMaterialTicks, long MeshUpdateRegistrationTicks, long MeshUpdateWriteTicks,
    long MeshUpdateAllocationBytes,
    long MeshUpdateSubmeshes, long MeshUpdateRegistrationAttempts,
    long MeshUpdateRegistrationHits, long MeshUpdateRegistrationRebuilds,
    long MeshUpdateAtlasEnsureCalls, long MeshUpdateLogicalTableWrites,
    long MeshUpdateMembershipAllocatedBytes, long MeshUpdateLookupAllocatedBytes,
    long MeshUpdateMaterialAllocatedBytes, long MeshUpdateRegistrationAllocatedBytes,
    long MeshUpdateMetadataAllocatedBytes, long MeshUpdateStateClassAllocatedBytes,
    long MeshUpdateFlagsAllocatedBytes, long MeshUpdateTransparencyAllocatedBytes,
    long MeshUpdateBoundsCompareAllocatedBytes, long MeshUpdateWriteAllocatedBytes,
    long MeshUpdateCommitAllocatedBytes,
    long MeshUpdateMetadataWrites, long MeshUpdateStateClassWrites,
    long MeshUpdateTransparencyWrites,
    long PublicationReused, long PublicationMissing, long PublicationExpired,
    long PublicationResourceMutation,
    long PublicationMaterialMutation, long PublicationCommandMutation,
    long PublicationTemporalMutation, long PublicationRegistrationRemoval,
    long MeshUpdateBoundsWrites, long MeshUpdateTransformWrites,
    long SceneSwaps, long SceneSwapsContentDirty, long SceneSwapsStreamsDirty,
    long SceneSwapCullControlElements, long SceneSwapBoundsElements,
    long SceneSwapClassificationElements, long SceneSwapVisibilityElements,
    long SceneSwapTransformElements, long SceneSwapPreviousTransformElements,
    long SceneSwapMaterialStateElements, long SceneSwapAabbElements,
    long SceneSwapTransparencyBytes,
    long AdvancedFamilyPreparations, long AdvancedFamilyStages,
    long AdvancedScenePublicationPrepareCalls, long AdvancedScenePublicationAttempts,
    long AdvancedScenePublicationReuses, long AdvancedScenePublicationPrepareTicks,
    long AdvancedScenePublicationFailures,
    long AdvancedSceneSlotHits, long AdvancedSceneSlotRealizations,
    long AdvancedPlanDiscoveries, long AdvancedPlanOperations,
    long AdvancedPlanAdvancedOperations, long AdvancedPlanFamilies,
    long AdvancedPlanDiscoveryVisits, long AdvancedPlanFamilyScanVisits,
    long AdvancedPlanLeaseChecks, long AdvancedPlanDiscoveryTicks,
    long AdvancedPlanPreparationTicks, long AdvancedPlanGateWaitTicks,
    long AdvancedPlanAllocatedBytes, long AdvancedPlanSealCollections,
    long AdvancedPlanSealVisits,
    long[] AdvancedFamilyStepCalls, long[] AdvancedFamilyStepTicks,
    long[] AdvancedFamilyStepBytes,
    long AdvancedBinFreezeSorts, long AdvancedBinFreezeRecords,
    long AdvancedBinFreezeOrderViolations);
