[CmdletBinding()]
param(
    [string]$SourceRoot = 'XREngine.Runtime.Rendering.Vulkan\Rendering\API\Rendering\Vulkan',
    [string]$OutputPath = '',
    [ValidateRange(1, 200)]
    [int]$LargestFileCount = 30
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$resolvedSourceRoot = if ([System.IO.Path]::IsPathRooted($SourceRoot)) {
    [System.IO.Path]::GetFullPath($SourceRoot)
}
else {
    [System.IO.Path]::GetFullPath((Join-Path $repoRoot $SourceRoot))
}

if (-not [System.IO.Directory]::Exists($resolvedSourceRoot)) {
    throw "Vulkan source root does not exist: $resolvedSourceRoot"
}

function Get-PortableRelativePath([string]$BasePath, [string]$Path) {
    $baseWithSeparator = $BasePath.TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar) +
        [System.IO.Path]::DirectorySeparatorChar
    $baseUri = [Uri]::new($baseWithSeparator)
    $pathUri = [Uri]::new([System.IO.Path]::GetFullPath($Path))
    return [Uri]::UnescapeDataString(
        $baseUri.MakeRelativeUri($pathUri).ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

function Get-RelativePath([string]$Path) {
    return (Get-PortableRelativePath $repoRoot $Path).Replace('\', '/')
}

function Test-GeneratedSource([System.IO.FileInfo]$File, [string]$Source) {
    return $File.Name -match '\.(?:g|generated)\.cs$' -or
        $Source.IndexOf('<auto-generated', [System.StringComparison]::OrdinalIgnoreCase) -ge 0 -or
        $Source.IndexOf('[GeneratedCode(', [System.StringComparison]::Ordinal) -ge 0
}

function Get-DeclarationCount([string]$Source, [string]$Pattern) {
    return [regex]::Matches(
        $Source,
        $Pattern,
        [System.Text.RegularExpressions.RegexOptions]::Multiline).Count
}

function Get-CSharpStructuralSource([string]$Source) {
    # Keep offsets and line breaks stable while removing text which must not
    # participate in the retained-ownership graph. This is intentionally a
    # lightweight structural scanner rather than a C# parser, but unlike the
    # former whole-file regex it cannot invent types or braces from comments
    # and ordinary string/character literals.
    $withoutBlockComments = [regex]::Replace(
        $Source,
        '(?s)/\*.*?\*/',
        { param($match) [regex]::Replace($match.Value, '[^\r\n]', ' ') })
    $withoutLineComments = [regex]::Replace(
        $withoutBlockComments,
        '(?m)//[^\r\n]*',
        { param($match) ' ' * $match.Value.Length })
    $withoutStrings = [regex]::Replace(
        $withoutLineComments,
        '@"(?:[^"]|"")*"|"(?:\\.|[^"\\])*"|''(?:\\.|[^''\\])*''',
        { param($match) [regex]::Replace($match.Value, '[^\r\n]', ' ') })
    return $withoutStrings
}

function Get-CSharpTypeSpans([string]$StructuralSource) {
    $typeSpans = [System.Collections.Generic.List[object]]::new()
    $declarations = [regex]::Matches(
        $StructuralSource,
        '(?m)^\s*(?:(?:public|internal|private|protected|file|sealed|abstract|static|unsafe|partial|readonly|ref|new)\s+)*(?:class|struct|interface|record(?:\s+(?:class|struct))?)\s+(?<name>[A-Za-z_]\w*)')
    foreach ($declaration in $declarations) {
        $bodyStart = $StructuralSource.IndexOf('{', $declaration.Index + $declaration.Length)
        $semicolon = $StructuralSource.IndexOf(';', $declaration.Index + $declaration.Length)
        if ($bodyStart -lt 0 -or ($semicolon -ge 0 -and $semicolon -lt $bodyStart)) {
            continue
        }

        $depth = 1
        $bodyEnd = $StructuralSource.Length - 1
        for ($index = $bodyStart + 1; $index -lt $StructuralSource.Length; $index++) {
            switch ($StructuralSource[$index]) {
                '{' { $depth++ }
                '}' {
                    $depth--
                    if ($depth -eq 0) {
                        $bodyEnd = $index
                        break
                    }
                }
            }
            if ($depth -eq 0) {
                break
            }
        }

        $typeSpans.Add([ordered]@{
            name = $declaration.Groups['name'].Value
            declaration_start = $declaration.Index
            body_start = $bodyStart
            body_end = $bodyEnd
            body_depth =
                ([regex]::Matches($StructuralSource.Substring(0, $bodyStart + 1), '\{')).Count -
                ([regex]::Matches($StructuralSource.Substring(0, $bodyStart + 1), '\}')).Count
        })
    }
    return @($typeSpans)
}

function Test-FacadeCallbackCandidate([string]$Source) {
    # Receiver names such as `renderer` are common for mesh, OpenGL, and
    # target-output capabilities. Treat a receiver as a facade callback only
    # when this file also declares that receiver with the concrete
    # VulkanRenderer type. This keeps the check declaring-type-aware without
    # requiring a particular field or parameter name.
    $declarations = [regex]::Matches(
        $Source,
        '\bVulkanRenderer\s*\??\s+(?<name>[A-Za-z_]\w*)\b')
    foreach ($declaration in $declarations) {
        $receiverName = [regex]::Escape($declaration.Groups['name'].Value)
        $lineStart = $Source.LastIndexOf("`n", $declaration.Index)
        $lineEnd = $Source.IndexOf("`n", $declaration.Index)
        if ($lineEnd -lt 0) {
            $lineEnd = $Source.Length
        }
        $declarationLine = $Source.Substring(
            $lineStart + 1,
            $lineEnd - $lineStart - 1)
        if ($declarationLine -match
            "\bVulkanRenderer\s+$receiverName\s*=\s*new(?:\s+VulkanRenderer)?\s*\(") {
            # A local constructed and immediately driven by the backend factory
            # is facade composition, not a retained callback from a subsystem.
            continue
        }
        if ($Source -match "\b$receiverName\s*(?:\?\.|\.)\s*[A-Za-z_]\w*") {
            return $true
        }
    }
    return $false
}

function Get-MaxDirectoryDepth([System.IO.FileInfo[]]$Files) {
    $maximumDepth = 0
    foreach ($file in $Files) {
        $relativeDirectory = Get-PortableRelativePath $resolvedSourceRoot $file.DirectoryName
        $depth = if ($relativeDirectory -eq '.') {
            0
        }
        else {
            $relativeDirectory.Split(
                [System.IO.Path]::DirectorySeparatorChar,
                [System.StringSplitOptions]::RemoveEmptyEntries).Length
        }
        if ($depth -gt $maximumDepth) {
            $maximumDepth = $depth
        }
    }
    return $maximumDepth
}

function Get-MethodSpanEstimates(
    [System.IO.FileInfo]$File,
    [string]$Source) {
    $lines = $Source -split "`r?`n"
    $methods = [System.Collections.Generic.List[object]]::new()
    for ($lineIndex = 0; $lineIndex -lt $lines.Length; $lineIndex++) {
        $line = $lines[$lineIndex]
        if ($line -match '\b(?:class|struct|record|interface)\s+[A-Za-z_]') {
            continue
        }
        if ($line -notmatch '^\s*(?:(?:public|private|protected|internal|static|sealed|virtual|override|abstract|async|unsafe|extern|new|partial|readonly)\s+)+(?:[\w.<>\[\],?]+\s+)+(?<name>[A-Za-z_]\w*)\s*(?:<[^>]+>)?\s*\(') {
            continue
        }

        $methodName = $Matches.name
        $signatureEnd = $lineIndex
        while ($signatureEnd -lt $lines.Length - 1 -and
               $lines[$signatureEnd].IndexOf('{') -lt 0 -and
               $lines[$signatureEnd].IndexOf('=>') -lt 0 -and
               $lines[$signatureEnd].IndexOf(';') -lt 0) {
            $signatureEnd++
        }

        if ($lines[$signatureEnd].IndexOf('=>') -ge 0 -or
            $lines[$signatureEnd].TrimEnd().EndsWith(';')) {
            $methods.Add([ordered]@{
                path = Get-RelativePath $File.FullName
                method = $methodName
                start_line = $lineIndex + 1
                physical_line_span = $signatureEnd - $lineIndex + 1
                logical_line_estimate = $signatureEnd - $lineIndex + 1
            })
            $lineIndex = $signatureEnd
            continue
        }

        $braceDepth = 0
        $opened = $false
        $methodEnd = $signatureEnd
        for ($bodyLine = $signatureEnd; $bodyLine -lt $lines.Length; $bodyLine++) {
            $openCount = ([regex]::Matches($lines[$bodyLine], '\{')).Count
            $closeCount = ([regex]::Matches($lines[$bodyLine], '\}')).Count
            if ($openCount -gt 0) {
                $opened = $true
            }
            $braceDepth += $openCount - $closeCount
            $methodEnd = $bodyLine
            if ($opened -and $braceDepth -le 0) {
                break
            }
        }

        $logicalLineCount = 0
        for ($logicalLine = $lineIndex; $logicalLine -le $methodEnd; $logicalLine++) {
            $trimmed = $lines[$logicalLine].Trim()
            if ($trimmed.Length -gt 0 -and $trimmed -notmatch '^[{}]+[;,]?$') {
                $logicalLineCount++
            }
        }

        $methods.Add([ordered]@{
            path = Get-RelativePath $File.FullName
            method = $methodName
            start_line = $lineIndex + 1
            physical_line_span = $methodEnd - $lineIndex + 1
            logical_line_estimate = $logicalLineCount
        })
        $lineIndex = $methodEnd
    }
    return @($methods)
}

$sourceFiles = @(
    Get-ChildItem -LiteralPath $resolvedSourceRoot -Recurse -File -Filter '*.cs' |
        Sort-Object FullName
)
$sourceTextByPath = [System.Collections.Generic.Dictionary[string, string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)
foreach ($file in $sourceFiles) {
    $sourceTextByPath[$file.FullName] = [System.IO.File]::ReadAllText($file.FullName)
}

$fileRecords = [System.Collections.Generic.List[object]]::new($sourceFiles.Count)
$rendererPartialFiles = [System.Collections.Generic.List[string]]::new()
$rendererNonPartialFiles = [System.Collections.Generic.List[string]]::new()
$rendererAuthorityRootFields = [System.Collections.Generic.List[object]]::new()
$unsafeTypeFiles = [System.Collections.Generic.List[string]]::new()
$threadStaticFiles = [System.Collections.Generic.List[string]]::new()
$ambientThreadStateFiles = [System.Collections.Generic.List[string]]::new()
$facadeCallbackFiles = [System.Collections.Generic.List[string]]::new()
$ambientRendererLookupFiles = [System.Collections.Generic.List[string]]::new()
$methodRecords = [System.Collections.Generic.List[object]]::new()
$handWrittenLineCount = 0
$generatedLineCount = 0
$rendererPartialDeclarationCount = 0
$rendererNonPartialDeclarationCount = 0
$rendererDirectAbstractBaseDeclarationCount = 0
$rendererNonPartialPhysicalLines = 0
$rendererFieldEstimate = 0

foreach ($file in $sourceFiles) {
    $source = $sourceTextByPath[$file.FullName]
    $lineCount = if ($source.Length -eq 0) {
        0
    }
    else {
        1 + (Get-DeclarationCount $source "`n")
    }
    $generated = Test-GeneratedSource $file $source
    if ($generated) {
        $generatedLineCount += $lineCount
    }
    else {
        $handWrittenLineCount += $lineCount
    }

    # Count renamed implementation shells as renderer partials too. A partial
    # monolith does not become a facade merely by moving "Renderer" out of the
    # public type name and inheriting from it.
    $partialCount = Get-DeclarationCount $source '\bpartial\s+(?:(?:sealed|abstract|unsafe)\s+)*class\s+VulkanRenderer(?:Runtime)?\b'
    if ($partialCount -gt 0) {
        $rendererPartialDeclarationCount += $partialCount
        $rendererPartialFiles.Add((Get-RelativePath $file.FullName))
        $rendererFieldEstimate += Get-DeclarationCount $source '^[ \t]*(?:(?:public|private|protected|internal|static|readonly|volatile|unsafe|new|required)\s+)+[A-Za-z_][\w<>,.?\[\]: \t]*\s+[A-Za-z_]\w*\s*(?:=(?!>)|;)'
    }

    $nonPartialCount = Get-DeclarationCount $source '^\s*(?:(?:public|internal|private|protected|sealed|unsafe|abstract)\s+)*(?!partial\s+)class\s+VulkanRenderer\b'
    if ($nonPartialCount -gt 0) {
        $rendererNonPartialDeclarationCount += $nonPartialCount
        $rendererNonPartialFiles.Add((Get-RelativePath $file.FullName))
        $rendererNonPartialPhysicalLines += $lineCount
        $rendererDirectAbstractBaseDeclarationCount += Get-DeclarationCount $source 'class\s+VulkanRenderer\s*:\s*AbstractRenderer\s*<\s*Vk\s*>'
    }

    if ($partialCount -gt 0 -or $nonPartialCount -gt 0) {
        foreach ($rootFieldMatch in [regex]::Matches(
            $source,
            '^\s*private\s+readonly\s+(?<type>VulkanDeviceContext|VulkanOutputRuntime|VulkanFrameLoop|VulkanFramePlanner|VulkanResourceRuntime|VulkanCommandRuntime|VulkanFrameTelemetry)\s+(?<name>_[A-Za-z_]\w*)\s*(?:=[^;]+)?;',
            [System.Text.RegularExpressions.RegexOptions]::Multiline)) {
            $rendererAuthorityRootFields.Add([ordered]@{
                type = $rootFieldMatch.Groups['type'].Value
                name = $rootFieldMatch.Groups['name'].Value
                path = Get-RelativePath $file.FullName
            })
        }
    }

    if ($source -match '\b(?:public|internal|private|protected)\s+unsafe\s+(?:partial\s+)?(?:class|struct|record)\b') {
        $unsafeTypeFiles.Add((Get-RelativePath $file.FullName))
    }
    $hasThreadStatic = $source.IndexOf('[ThreadStatic]', [System.StringComparison]::Ordinal) -ge 0 -or
        $source.IndexOf('ThreadStaticAttribute', [System.StringComparison]::Ordinal) -ge 0
    if ($hasThreadStatic) {
        $threadStaticFiles.Add((Get-RelativePath $file.FullName))
    }
    if ($hasThreadStatic -or $source -match '\bstatic\s+(?:readonly\s+)?ThreadLocal<') {
        $ambientThreadStateFiles.Add((Get-RelativePath $file.FullName))
    }
    if (Test-FacadeCallbackCandidate $source) {
        $facadeCallbackFiles.Add((Get-RelativePath $file.FullName))
    }
    if ($source -match '\b(?:AbstractRenderer\.Current|RuntimeRenderingHostServices\.FrameTiming\.CurrentRenderer)\b') {
        $ambientRendererLookupFiles.Add((Get-RelativePath $file.FullName))
    }

    $fileRecords.Add([ordered]@{
        path = Get-RelativePath $file.FullName
        lines = $lineCount
        generated = $generated
        renderer_partial_declarations = $partialCount
    })
    # Method sizing must ignore braces and apparent declarations inside comments
    # and literals. Get-CSharpStructuralSource preserves line positions while
    # blanking those tokens, so the report remains reproducible without turning
    # shader strings or diagnostic examples into false oversized methods.
    foreach ($methodRecord in @(
        Get-MethodSpanEstimates $file (Get-CSharpStructuralSource $source))) {
        $methodRecords.Add($methodRecord)
    }
}

$authorityPatterns = [ordered]@{
    device = 'VulkanDeviceContext'
    output = 'VulkanOutputRuntime|VulkanDesktopWsiTargetDriver|IVulkanRendererTargetDriver'
    frame_loop = 'VulkanFrameLoop|VulkanDesktopFrameCoordinator'
    planner = 'VulkanFramePlanner|VulkanResourcePlanCoordinator|VulkanRenderGraphRuntime'
    resources = 'VulkanResourceRuntime|VulkanResourceLifetimeTracker|VulkanDescriptorManager|VulkanPipelineManager'
    commands = 'VulkanCommandRuntime|VulkanCommandRecorder|VulkanQueueGateway'
    telemetry = 'VulkanFrameTelemetry|VulkanFrameTrace|VulkanFrameTiming'
}

$authorityMatches = [ordered]@{}
foreach ($entry in $authorityPatterns.GetEnumerator()) {
    $authorityFiles = [System.Collections.Generic.List[string]]::new()
    foreach ($file in $sourceFiles) {
        $source = $sourceTextByPath[$file.FullName]
        # Source ownership is declaration-based. Classifying every file which merely
        # mentions an authority makes a facade composition file appear to own every
        # authority and produces meaningless all-to-all dependency edges.
        $declarationPattern = "\b(?:class|struct|interface|record(?:\s+(?:class|struct))?)\s+(?:$($entry.Value))\b"
        if ($source -match $declarationPattern) {
            $authorityFiles.Add((Get-RelativePath $file.FullName))
        }
    }
    $authorityMatches[$entry.Key] = @($authorityFiles)
}

$approvedAuthorityEdges = [ordered]@{
    device = @()
    output = @('device', 'telemetry')
    frame_loop = @('output', 'planner', 'resources', 'commands', 'device', 'telemetry')
    planner = @('resources', 'device', 'telemetry')
    resources = @('device', 'telemetry')
    commands = @('resources', 'device', 'telemetry')
    telemetry = @()
}

$authorityRendererBacklinkFiles = [System.Collections.Generic.List[string]]::new()
foreach ($entry in $authorityMatches.GetEnumerator()) {
    foreach ($sourceFilePath in @($entry.Value)) {
        $sourceFile = Join-Path $repoRoot $sourceFilePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $source = $sourceTextByPath[$sourceFile]
        if (Test-FacadeCallbackCandidate $source) {
            $authorityRendererBacklinkFiles.Add($sourceFilePath)
        }
    }
}

$authorityDependencyEdges = [System.Collections.Generic.List[object]]::new()
foreach ($sourceEntry in $authorityPatterns.GetEnumerator()) {
    foreach ($sourceFilePath in @($authorityMatches[$sourceEntry.Key])) {
        $sourceFile = Join-Path $repoRoot $sourceFilePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $source = $sourceTextByPath[$sourceFile]
        foreach ($targetEntry in $authorityPatterns.GetEnumerator()) {
            if ($targetEntry.Key -eq $sourceEntry.Key -or
                $source -notmatch "\b(?:$($targetEntry.Value))\b") {
                continue
            }
            $authorityDependencyEdges.Add([ordered]@{
                source_authority = $sourceEntry.Key
                target_authority = $targetEntry.Key
                path = $sourceFilePath
            })
        }
    }
}

$authorityDependencyViolations = [System.Collections.Generic.List[object]]::new()
foreach ($edge in $authorityDependencyEdges) {
    if ($approvedAuthorityEdges[$edge.source_authority] -notcontains $edge.target_authority) {
        $authorityDependencyViolations.Add($edge)
    }
}

# Build a conservative retained-type graph from instance fields and auto-properties.
# This intentionally ignores method parameters and return values: the gate is about
# stored ownership paths which can hide a multi-authority service locator.
$authorityRootTypes = @(
    'VulkanDeviceContext',
    'VulkanOutputRuntime',
    'VulkanFrameLoop',
    'VulkanFramePlanner',
    'VulkanResourceRuntime',
    'VulkanCommandRuntime',
    'VulkanFrameTelemetry')

# Cross-authority composition is not duplicate ownership. These generation-local
# adapters coordinate canonical roots at an explicit operation boundary and own
# no competing device, output, planner, resource, command, or telemetry state.
# Keeping the allowlist here makes every exception reviewable and causes any new
# multi-root holder to fail the hard gate by default.
$approvedCrossAuthorityCompositions = [ordered]@{
    VulkanBackendObjectContext = 'Generation-local backend-wrapper capability boundary.'
    VulkanDescriptorLifetimeAuthority = 'Descriptor lifetime subowner coordinated by the resource root.'
    VulkanDescriptorManager = 'Descriptor publication subowner coordinated by the resource root.'
    VulkanDesktopSwapchainService = 'Desktop output adapter between device, output, and resource roots.'
    VulkanFallbackTextureAuthority = 'Resource-owned fallback upload adapter.'
    VulkanFinalPresentationDescriptorPort = 'Final-output descriptor publication operation port.'
    VulkanImageResourceService = 'Resource-owned image creation and transfer service.'
    VulkanImGuiDrawBufferResources = 'ImGui leaf resource adapter.'
    VulkanImGuiFontAtlasResources = 'ImGui font-upload operation adapter.'
    VulkanImGuiOutputPipelineService = 'ImGui output pipeline adapter.'
    VulkanImGuiOverlayAdmission = 'ImGui overlay admission adapter.'
    VulkanImGuiTextureOutputResources = 'ImGui texture-output leaf adapter.'
    VulkanImGuiTextureRegistryService = 'ImGui texture registration adapter.'
    VulkanMappedFrameArenaBackend = 'Mapped-arena native allocation backend.'
    VulkanOpenXrCommandRecordingService = 'OpenXR leaf command-recording adapter.'
    VulkanOpenXrEyeWorkerCommandService = 'OpenXR eye worker recording adapter.'
    VulkanOpenXrOutputResourceService = 'OpenXR output resource adapter.'
    VulkanReadbackOutputResourceService = 'Readback output operation adapter.'
    VulkanResourceCommandWrapperPort = 'Backend-wrapper resource command port.'
    VulkanResourceGenerationTransactionService = 'Frame-loop resource-generation transaction coordinator.'
    VulkanResourcePlannerSessionService = 'Frame-loop planner session coordinator.'
    VulkanSamplerResourceService = 'Resource-owned sampler registration service.'
    VulkanSynchronousResourceCommandSession = 'Bounded synchronous resource command transaction.'
    VulkanSynchronousUploadSession = 'Bounded synchronous upload transaction.'
    VulkanTargetSurfaceAuthority = 'Target-scoped surface lifetime adapter.'
    VulkanTextureUploadSchedulingContext = 'Immutable texture-upload operation context.'
    VulkanTimelineGpuFence = 'Fence adapter over canonical timeline and retirement owners.'
}
$approvedCallableCompositionMembers = @(
    'VkObjectBase|BackendContext',
    'VulkanGraphicsPipelineBuildRequest|ProgramServices')
$knownTypes = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::Ordinal)
$fileTypeSpans = @{}
$fileStructuralSources = @{}
foreach ($file in $sourceFiles) {
    $source = $sourceTextByPath[$file.FullName]
    $structuralSource = Get-CSharpStructuralSource $source
    $typeSpans = @(Get-CSharpTypeSpans $structuralSource)
    $fileStructuralSources[$file.FullName] = $structuralSource
    $fileTypeSpans[$file.FullName] = $typeSpans
    foreach ($typeSpan in $typeSpans) {
        $typeName = $typeSpan.name
        [void]$knownTypes.Add($typeName)
    }
}

$retainedTypeEdges = @{}
$directAuthorityMembers = [System.Collections.Generic.List[object]]::new()
$rawAuthorityProperties = [System.Collections.Generic.List[object]]::new()
function Add-RetainedEdge([string]$OwnerType, [string]$MemberType, [string]$MemberName, [string]$MemberKind, [bool]$Callable, [System.IO.FileInfo]$File, [int]$Line) {
    $targetType = $MemberType.Trim() -replace '^global::', ''
    $targetType = $targetType -replace '[?<\[].*$', ''
    if (-not ($knownTypes.Contains($targetType) -or $authorityRootTypes -contains $targetType)) { return }
    if (-not $retainedTypeEdges.ContainsKey($OwnerType)) {
        $retainedTypeEdges[$OwnerType] = [System.Collections.Generic.List[object]]::new()
    }
    $edge = [ordered]@{ target_type = $targetType; member_name = $MemberName; member_kind = $MemberKind; callable = $Callable; path = Get-RelativePath $File.FullName; line = $Line }
    $retainedTypeEdges[$OwnerType].Add($edge)
    if ($authorityRootTypes -contains $targetType) {
        $directAuthorityMembers.Add([ordered]@{ owner_type = $OwnerType; authority_type = $targetType; member = $MemberName; member_kind = $MemberKind; callable = $Callable; path = $edge.path; line = $Line })
        if ($Callable) { $rawAuthorityProperties.Add($directAuthorityMembers[$directAuthorityMembers.Count - 1]) }
    }
}
foreach ($file in $sourceFiles) {
    $source = $fileStructuralSources[$file.FullName]
    $typeSpans = @($fileTypeSpans[$file.FullName])
    $lines = $source -split "(?<=`n)"; $sourceOffset = 0; $braceDepth = 0
    # Primary-constructor parameters are retained inputs for this inventory.
    foreach ($typeSpan in $typeSpans) {
        $header = $source.Substring($typeSpan.declaration_start, $typeSpan.body_start - $typeSpan.declaration_start)
        foreach ($parameter in [regex]::Matches($header, '(?<type>[A-Za-z_]\w*(?:\s*<[^()>{}]+>)?)\s+(?<name>[A-Za-z_]\w*)')) {
            $line = 1 + ([regex]::Matches($source.Substring(0, $typeSpan.declaration_start + $parameter.Index), "`n")).Count
            Add-RetainedEdge $typeSpan.name $parameter.Groups['type'].Value $parameter.Groups['name'].Value 'primary_constructor_parameter' $false $file $line
        }
    }
    for ($lineIndex = 0; $lineIndex -lt $lines.Count; $lineIndex++) {
        $lineWithEnding = $lines[$lineIndex]; $line = $lineWithEnding.TrimEnd("`r", "`n"); $owner = $null
        foreach ($candidate in $typeSpans) {
            if ($sourceOffset -gt $candidate.body_start -and $sourceOffset -lt $candidate.body_end -and ($null -eq $owner -or $candidate.body_start -gt $owner.body_start)) { $owner = $candidate }
        }
        if ($null -ne $owner -and $braceDepth -eq $owner.body_depth -and $line -notmatch '\b(?:static|const)\b') {
            $fieldMatch = [regex]::Match($line, '^\s*(?:(?:public|private|protected|internal|file|readonly|volatile|unsafe|required|new)\s+)+(?<type>[A-Za-z_]\w[\w.<>,?\[\] ]*)\s+(?<name>[A-Za-z_]\w*)\s*(?:=[^;]*)?;\s*$')
            $propertyMatch = [regex]::Match($line, '^\s*(?:(?:public|private|protected|internal|file|readonly|unsafe|required|new|virtual|override|sealed)\s+)+(?<type>[A-Za-z_]\w[\w.<>,?\[\] ]*)\s+(?<name>[A-Za-z_]\w*)\s*\{\s*(?:get|init)\s*;')
            $match = if ($fieldMatch.Success) { $fieldMatch } else { $propertyMatch }
            if ($match.Success) { Add-RetainedEdge $owner.name $match.Groups['type'].Value $match.Groups['name'].Value $(if ($fieldMatch.Success) { 'field' } else { 'property' }) $propertyMatch.Success $file ($lineIndex + 1) }
        }
        $braceDepth += ([regex]::Matches($lineWithEnding, '\{')).Count; $braceDepth -= ([regex]::Matches($lineWithEnding, '\}')).Count; $sourceOffset += $lineWithEnding.Length
    }
}
$retainedAuthorityReach = @{}
foreach ($typeName in $knownTypes) { $retainedAuthorityReach[$typeName] = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal); if ($authorityRootTypes -contains $typeName) { [void]$retainedAuthorityReach[$typeName].Add($typeName) } }
$reachChanged = $true
while ($reachChanged) {
    $reachChanged = $false
    foreach ($ownerType in @($retainedTypeEdges.Keys)) {
        if ($authorityRootTypes -contains $ownerType) { continue }
        foreach ($edge in @($retainedTypeEdges[$ownerType])) {
            $targetType = $edge.target_type
            if ($authorityRootTypes -contains $targetType) { if ($retainedAuthorityReach[$ownerType].Add($targetType)) { $reachChanged = $true }; continue }
            foreach ($authorityType in @($retainedAuthorityReach[$targetType])) { if ($retainedAuthorityReach[$ownerType].Add($authorityType)) { $reachChanged = $true } }
        }
    }
}
function Get-RetainedAuthorityPaths([string]$StartType) {
    $paths = [ordered]@{}; $pending = [System.Collections.Generic.Queue[object]]::new(); $pending.Enqueue([ordered]@{ type = $StartType; edges = @() })
    $visited = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal); [void]$visited.Add($StartType)
    while ($pending.Count -gt 0) {
        $state = $pending.Dequeue(); $current = $state.type
        if ($authorityRootTypes -contains $current) { if (-not $paths.Contains($current)) { $paths[$current] = @($state.edges) }; continue }
        if (-not $retainedTypeEdges.ContainsKey($current)) { continue }
        foreach ($edge in @($retainedTypeEdges[$current] | Sort-Object target_type, path, line, member_name)) { if ($visited.Add($edge.target_type)) { $pending.Enqueue([ordered]@{ type = $edge.target_type; edges = @($state.edges + $edge) }) } }
    }
    return $paths
}
$retainedMultiAuthorityTypes = [System.Collections.Generic.List[object]]::new()
foreach ($typeName in @($retainedAuthorityReach.Keys | Sort-Object)) {
    if ($authorityRootTypes -contains $typeName -or $typeName -eq 'VulkanRenderer' -or $retainedAuthorityReach[$typeName].Count -lt 4) { continue }
    $authorityPaths = Get-RetainedAuthorityPaths $typeName
    $retainedMultiAuthorityTypes.Add([ordered]@{ type = $typeName; authority_count = $retainedAuthorityReach[$typeName].Count; authorities = @($retainedAuthorityReach[$typeName] | Sort-Object); authority_paths = $authorityPaths; path = @($authorityPaths.Values | Select-Object -First 1)[0][0].path })
}
$authorityRetainedMultiAuthorityTypes = [System.Collections.Generic.List[object]]::new()
foreach ($authorityType in $authorityRootTypes) { if ($retainedTypeEdges.ContainsKey($authorityType)) { foreach ($candidate in @($retainedMultiAuthorityTypes)) { foreach ($edge in @($retainedTypeEdges[$authorityType] | Where-Object { $_.target_type -eq $candidate.type })) { $authorityRetainedMultiAuthorityTypes.Add([ordered]@{ authority_type = $authorityType; retained_type = $candidate.type; member = $edge.member_name; path = $edge.path; line = $edge.line }) } } } }

# A hard failure requires directly retained authority capability. Transitive
# reach through immutable payloads remains advisory: it can be useful context,
# but does not by itself demonstrate service location at the current type.
$hardGateDirectAuthorityViolations = [System.Collections.Generic.List[object]]::new()
$approvedDirectAuthorityCompositions = [System.Collections.Generic.List[object]]::new()
$effectiveDirectAuthorityMembers = [System.Collections.Generic.List[object]]::new()
$directAuthorityMembersByStorage = @{}
foreach ($member in $directAuthorityMembers) {
    $storageName = ([string]$member['member']) -replace '^_+', ''
    $storageKey = '{0}|{1}|{2}' -f $member['owner_type'], $member['authority_type'], $storageName
    if (-not $directAuthorityMembersByStorage.ContainsKey($storageKey) -or
        $directAuthorityMembersByStorage[$storageKey]['member_kind'] -eq 'primary_constructor_parameter') {
        $directAuthorityMembersByStorage[$storageKey] = $member
    }
}
foreach ($member in $directAuthorityMembersByStorage.Values) { $effectiveDirectAuthorityMembers.Add($member) }
$directAuthorityMembersByOwner = @{}
foreach ($member in $effectiveDirectAuthorityMembers) {
    $ownerType = [string]$member['owner_type']
    if (-not $directAuthorityMembersByOwner.ContainsKey($ownerType)) {
        $directAuthorityMembersByOwner[$ownerType] = [System.Collections.Generic.List[object]]::new()
    }
    $directAuthorityMembersByOwner[$ownerType].Add($member)
}
foreach ($ownerType in @($directAuthorityMembersByOwner.Keys | Sort-Object)) {
    $members = @($directAuthorityMembersByOwner[$ownerType])
    $authorities = @($members | ForEach-Object { $_['authority_type'] } | Sort-Object -Unique)
    if ($ownerType -eq 'VulkanRenderer' -or
        $authorityRootTypes -contains $ownerType -or
        $authorities.Count -lt 2) { continue }
    if ($approvedCrossAuthorityCompositions.Contains($ownerType)) {
        $approvedDirectAuthorityCompositions.Add([ordered]@{
            type = $ownerType
            reason = $approvedCrossAuthorityCompositions[$ownerType]
            direct_authority_count = $authorities.Count
            authorities = $authorities
            members = $members
        })
        continue
    }
    $hardGateDirectAuthorityViolations.Add([ordered]@{
        type = $ownerType
        classification = 'direct_multi_authority'
        reason = 'Retains two or more distinct authority roots directly.'
        direct_authority_count = $authorities.Count
        distinct_authority_count = $authorities.Count
        member_declaration_count = $members.Count
        authorities = $authorities
        members = $members
    })
}
$allAuthoritiesContextViolations = [System.Collections.Generic.List[object]]::new()
foreach ($violation in $hardGateDirectAuthorityViolations) {
    if ($violation.distinct_authority_count -lt 4) { continue }
    $hasRawRootAccessor = @($violation.members | Where-Object { $_['callable'] }).Count -gt 0
    $isNarrowImmutableOperationOrSession = $violation.type -match '(?:Operation|Op|Session)$'
    if ($isNarrowImmutableOperationOrSession -and -not $hasRawRootAccessor) { continue }
    $allAuthoritiesContextViolations.Add([ordered]@{
        type = $violation.type
        classification = 'all_authorities_context'
        reason = if ($isNarrowImmutableOperationOrSession) { 'Retains four or more distinct roots and exposes a raw root accessor.' } else { 'Retains four or more distinct authority roots directly.' }
        direct_authority_count = $violation.direct_authority_count
        member_declaration_count = $violation.member_declaration_count
        authorities = $violation.authorities
        members = $violation.members
    })
}
$hardGateCallableServiceLocationViolations = [System.Collections.Generic.List[object]]::new()
$approvedCallableServiceLocationCompositions = [System.Collections.Generic.List[object]]::new()
foreach ($ownerType in @($retainedTypeEdges.Keys | Sort-Object)) {
    if ($authorityRootTypes -contains $ownerType) { continue }
    foreach ($edge in @($retainedTypeEdges[$ownerType] | Where-Object { $_.callable -and $authorityRootTypes -notcontains $_.target_type })) {
        if (-not $retainedAuthorityReach.ContainsKey($edge.target_type) -or $retainedAuthorityReach[$edge.target_type].Count -lt 2) { continue }
        if ($edge.target_type -notmatch '(?:Context|Port|Service|Dispatcher|Encoder)$') { continue }
        $memberKey = '{0}|{1}' -f $ownerType, $edge.member_name
        if ($approvedCallableCompositionMembers -contains $memberKey) {
            $approvedCallableServiceLocationCompositions.Add([ordered]@{
                owner_type = $ownerType
                retained_type = $edge.target_type
                member = $edge.member_name
                authorities = @($retainedAuthorityReach[$edge.target_type] | Sort-Object)
                path = $edge.path
                line = $edge.line
            })
            continue
        }
        $hardGateCallableServiceLocationViolations.Add([ordered]@{
            owner_type = $ownerType
            retained_type = $edge.target_type
            classification = 'callable_retained_service_location'
            reason = 'Callable member exposes a retained context, port, service, dispatcher, or encoder with two or more authority roots.'
            authority_count = $retainedAuthorityReach[$edge.target_type].Count
            authorities = @($retainedAuthorityReach[$edge.target_type] | Sort-Object)
            member = $edge.member_name
            path = $edge.path
            line = $edge.line
        })
    }
}
$hardGateViolationCount = $hardGateDirectAuthorityViolations.Count + $hardGateCallableServiceLocationViolations.Count

$outputTargetImGuiMultiAuthorityTypes = @(
    $retainedMultiAuthorityTypes |
        Where-Object {
            $_.path -match '/(?:Frame/Output|Bootstrap/Targets|UI)/' -or
                $_.type -match 'OpenXrOutput'
        })
$outputTargetImGuiRawAuthorityProperties = @(
    $rawAuthorityProperties |
        Where-Object {
            $_.path -match '/(?:Frame/Output|Bootstrap/Targets|UI)/' -or
                $_.owner_type -match 'OpenXrOutput'
        })

$sourceRootRelative = (Get-RelativePath $resolvedSourceRoot).TrimEnd('/')
$lifecycleSpineRelativePaths = @(
    'Bootstrap/VulkanRenderer.cs',
    'Frame/Loop/Authority/VulkanFrameLoop.cs',
    'Frame/Loop/Authority/VulkanFrameLoop.Lifecycle.cs',
    'Frame/Loop/Authority/VulkanFrameLoop.ResourcePlannerContext.cs',
    'Frame/Loop/VulkanFrameLoop.PrimaryRecordingPreparation.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Acquire.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.FrameSlots.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.FrameSlots.Retirement.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Preflight.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Preflight.Policy.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Presentation.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recording.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recording.Failures.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.Policy.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.Presentation.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.Recording.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.Submission.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Recovery.SubmissionBridge.cs',
    'Frame/Loop/VulkanRenderer.FrameLoop.Submission.cs',
    'Frame/Loop/VulkanFrameAttempt.cs',
    'Frame/Loop/VulkanDesktopFramePhaseResult.cs',
    'Frame/Loop/VulkanDesktopFrameTerminalResult.cs',
    'Frame/Desktop/Contracts/DesktopFrameIdentity.cs',
    'Frame/Output/Authority/VulkanOutputRuntime.cs',
    'RenderGraph/Authority/VulkanFramePlanner.cs',
    'RenderGraph/Authority/VulkanFramePlanner.ContextSignatures.cs',
    'RenderGraph/VulkanFrameOperationScheduler.cs',
    'Commands/Authority/VulkanCommandRuntime.cs',
    'Commands/Authority/VulkanCommandRuntime.DesktopOutputArtifacts.cs',
    'Commands/Authority/VulkanCommandRuntime.FrameOperationApi.cs',
    'Commands/Authority/VulkanCommandRuntime.FrameOperationQueue.cs',
    'Commands/Authority/VulkanCommandRuntime.FramePlanningState.cs',
    'Commands/Authority/VulkanCommandRuntime.TrackedSubmission.cs',
    'Commands/CommandBuffers/Recording/VulkanCommandRuntime.PrimaryRecording.cs',
    'Commands/Scheduling/Primary/VulkanPrimaryCommandPlan.cs',
    'Frame/Synchronization/VulkanSubmissionReceipt.cs',
    'Frame/Telemetry/VulkanFrameTelemetry.cs',
    'Frame/Telemetry/VulkanFrameTrace.cs')
$lifecycleSpinePaths = @(
    $lifecycleSpineRelativePaths | ForEach-Object { "$sourceRootRelative/$_" })
$allFilePaths = @($fileRecords | ForEach-Object { $_['path'] })
$lifecycleSpineFiles = @(
    $fileRecords | Where-Object { $lifecycleSpinePaths -contains $_['path'] })
$lifecycleSpineMissingFiles = @(
    $lifecycleSpinePaths | Where-Object { $allFilePaths -notcontains $_ })
$lifecycleSpineLineCount = 0
foreach ($file in $lifecycleSpineFiles) {
    $lifecycleSpineLineCount += [int]$file['lines']
}

$partialDeclarationsByType = @{}
foreach ($file in $sourceFiles) {
    $structuralSource = $fileStructuralSources[$file.FullName]
    foreach ($match in [regex]::Matches(
        $structuralSource,
        '\bpartial\s+(?:(?:sealed|abstract|unsafe|readonly|ref)\s+)*(?:class|struct|record(?:\s+(?:class|struct))?)\s+(?<name>[A-Za-z_]\w*)')) {
        $name = $match.Groups['name'].Value
        if (-not $partialDeclarationsByType.ContainsKey($name)) {
            $partialDeclarationsByType[$name] = [System.Collections.Generic.List[string]]::new()
        }
        $partialDeclarationsByType[$name].Add((Get-RelativePath $file.FullName))
    }
}

# The role ledger prevents a cleanup from merely renaming two competing owners.
# Each responsibility has one canonical declaration family; retired ambiguous
# owner names must remain absent. Focused leaf algorithms (for example barrier
# and resource planners beneath VulkanFramePlanner) are intentionally not roots.
$canonicalRoleSpecifications = @(
    [ordered]@{ role = 'device_authority'; canonical_type = 'VulkanDeviceContext'; retired_competitors = @('VulkanDeviceAuthority') },
    [ordered]@{ role = 'output_authority'; canonical_type = 'VulkanOutputRuntime'; retired_competitors = @('VulkanOutputAuthority') },
    [ordered]@{ role = 'frame_lifecycle_authority'; canonical_type = 'VulkanFrameLoop'; retired_competitors = @('VulkanDesktopFrameLoop') },
    [ordered]@{ role = 'frame_planning_authority'; canonical_type = 'VulkanFramePlanner'; retired_competitors = @('VulkanPlanningRuntime') },
    [ordered]@{ role = 'frame_operation_scheduler'; canonical_type = 'VulkanFrameOperationScheduler'; retired_competitors = @('VulkanCommandScheduler', 'VulkanPrimaryRecordingPolicy') },
    [ordered]@{ role = 'resource_authority'; canonical_type = 'VulkanResourceRuntime'; retired_competitors = @('VulkanResourceAuthority') },
    [ordered]@{ role = 'descriptor_publication'; canonical_type = 'VulkanDescriptorManager'; retired_competitors = @('VulkanDescriptorPublisher') },
    [ordered]@{ role = 'resource_lifetime'; canonical_type = 'VulkanResourceLifetimeTracker'; retired_competitors = @('VulkanLifetimeManager') },
    [ordered]@{ role = 'command_authority'; canonical_type = 'VulkanCommandRuntime'; retired_competitors = @('VulkanQueueGateway') },
    [ordered]@{ role = 'frame_telemetry'; canonical_type = 'VulkanFrameTelemetry'; retired_competitors = @('VulkanFrameProfiler') })
$canonicalRoleRecords = [System.Collections.Generic.List[object]]::new()
$canonicalRoleViolationCount = 0
foreach ($specification in $canonicalRoleSpecifications) {
    $canonicalType = [string]$specification.canonical_type
    $canonicalFiles = [System.Collections.Generic.List[string]]::new()
    $retiredDeclarations = [System.Collections.Generic.List[object]]::new()
    foreach ($file in $sourceFiles) {
        foreach ($typeSpan in @($fileTypeSpans[$file.FullName])) {
            if ($typeSpan.name -eq $canonicalType) {
                $canonicalFiles.Add((Get-RelativePath $file.FullName))
            }
            elseif (@($specification.retired_competitors) -contains $typeSpan.name) {
                $retiredDeclarations.Add([ordered]@{
                    type = $typeSpan.name
                    path = Get-RelativePath $file.FullName
                })
            }
        }
    }
    $passes = $canonicalFiles.Count -gt 0 -and $retiredDeclarations.Count -eq 0
    if (-not $passes) { $canonicalRoleViolationCount++ }
    $canonicalRoleRecords.Add([ordered]@{
        role = $specification.role
        canonical_type = $canonicalType
        canonical_declaration_count = $canonicalFiles.Count
        canonical_files = @($canonicalFiles | Sort-Object -Unique)
        retired_competitors = @($specification.retired_competitors)
        retired_declarations = @($retiredDeclarations)
        passes = $passes
    })
}
$partialTypeRecords = @(
    foreach ($name in @($partialDeclarationsByType.Keys | Sort-Object)) {
        [ordered]@{
            type = $name
            declaration_count = $partialDeclarationsByType[$name].Count
            files = @($partialDeclarationsByType[$name] | Sort-Object -Unique)
        }
    })

$multipleTopLevelTypeFiles = [System.Collections.Generic.List[object]]::new()
foreach ($file in $sourceFiles) {
    $structuralSource = $fileStructuralSources[$file.FullName]
    $declarations = @(
        [regex]::Matches(
            $structuralSource,
            '(?m)^\s*(?:(?:public|internal|private|protected|file|sealed|abstract|static|unsafe|partial|readonly|ref|new)\s+)*(?:class|struct|interface|enum|record(?:\s+(?:class|struct))?)\s+(?<name>[A-Za-z_]\w*)') |
            ForEach-Object {
                [ordered]@{
                    name = $_.Groups['name'].Value
                    depth =
                        ([regex]::Matches($structuralSource.Substring(0, $_.Index), '\{')).Count -
                        ([regex]::Matches($structuralSource.Substring(0, $_.Index), '\}')).Count
                }
            })
    if ($declarations.Count -eq 0) { continue }
    $topLevelDepth = [int]::MaxValue
    foreach ($declaration in $declarations) {
        $topLevelDepth = [Math]::Min($topLevelDepth, [int]$declaration['depth'])
    }
    $topLevelTypes = @($declarations | Where-Object { [int]$_['depth'] -eq $topLevelDepth })
    if ($topLevelTypes.Count -gt 1) {
        $multipleTopLevelTypeFiles.Add([ordered]@{
            path = Get-RelativePath $file.FullName
            top_level_type_count = $topLevelTypes.Count
            types = @($topLevelTypes | ForEach-Object { $_['name'] })
        })
    }
}

$structuralExceptionManifestPath = Join-Path $repoRoot 'Tools\Reports\VulkanCoreStructuralExceptions.json'
if (-not [System.IO.File]::Exists($structuralExceptionManifestPath)) {
    throw "Vulkan structural exception manifest does not exist: $structuralExceptionManifestPath"
}
$structuralExceptionManifest =
    [System.IO.File]::ReadAllText($structuralExceptionManifestPath) | ConvertFrom-Json
if ($structuralExceptionManifest.schema_version -ne 1) {
    throw "Unsupported Vulkan structural exception manifest schema: $($structuralExceptionManifest.schema_version)"
}
$approvedFileExceptions = @{}
foreach ($exception in @($structuralExceptionManifest.file_exceptions)) {
    $approvedFileExceptions[[string]$exception.path] = [string]$exception.reason
}
$approvedMethodExceptions = @{}
foreach ($profile in @($structuralExceptionManifest.method_exception_profiles)) {
    foreach ($method in @($profile.methods)) {
        $approvedMethodExceptions[('{0}|{1}' -f $profile.path, $method)] = [string]$profile.reason
    }
}

$oversizedFiles = @(
    $fileRecords |
        Where-Object { -not $_['generated'] -and [int]$_['lines'] -gt 1500 } |
        Sort-Object { [int]$_['lines'] } -Descending)
$oversizedMethods = @(
    $methodRecords |
        Where-Object { [int]$_.logical_line_estimate -gt 150 } |
        Sort-Object { [int]$_.logical_line_estimate } -Descending)
$unapprovedOversizedFiles = [System.Collections.Generic.List[object]]::new()
foreach ($file in $oversizedFiles) {
    $relativePath = ([string]$file['path']).Substring($sourceRootRelative.Length + 1)
    if ($approvedFileExceptions.ContainsKey($relativePath)) {
        $file['exception_reason'] = $approvedFileExceptions[$relativePath]
    }
    else {
        $unapprovedOversizedFiles.Add($file)
    }
}
$unapprovedOversizedMethods = [System.Collections.Generic.List[object]]::new()
foreach ($method in $oversizedMethods) {
    $relativePath = ([string]$method['path']).Substring($sourceRootRelative.Length + 1)
    $key = '{0}|{1}' -f $relativePath, $method['method']
    if ($approvedMethodExceptions.ContainsKey($key)) {
        $method['exception_reason'] = $approvedMethodExceptions[$key]
    }
    else {
        $unapprovedOversizedMethods.Add($method)
    }
}
$mainFrameMethod = @(
    $methodRecords |
        Where-Object {
            $_.path -eq "$sourceRootRelative/Frame/Loop/Authority/VulkanFrameLoop.cs" -and
                $_.method -eq 'Render'
        } |
        Select-Object -First 1)

$result = [ordered]@{
    schema_version = 4
    generated_utc = [DateTime]::UtcNow.ToString('O')
    repository_root = $repoRoot
    source_root = Get-RelativePath $resolvedSourceRoot
    totals = [ordered]@{
        files = $sourceFiles.Count
        hand_written_files = @($fileRecords | Where-Object { -not $_.generated }).Count
        generated_files = @($fileRecords | Where-Object generated).Count
        physical_lines = $handWrittenLineCount + $generatedLineCount
        hand_written_physical_lines = $handWrittenLineCount
        generated_physical_lines = $generatedLineCount
        maximum_directory_depth = Get-MaxDirectoryDepth $sourceFiles
    }
    facade = [ordered]@{
        renderer_partial_files = $rendererPartialFiles.Count
        renderer_partial_declarations = $rendererPartialDeclarationCount
        renderer_non_partial_files = $rendererNonPartialFiles.Count
        renderer_non_partial_declarations = $rendererNonPartialDeclarationCount
        renderer_non_partial_physical_lines = $rendererNonPartialPhysicalLines
        renderer_direct_abstract_base_declarations = $rendererDirectAbstractBaseDeclarationCount
        authority_root_fields = @($rendererAuthorityRootFields)
        authority_root_field_count = $rendererAuthorityRootFields.Count
        renderer_field_estimate = $rendererFieldEstimate
        unsafe_type_files = $unsafeTypeFiles.Count
        ambient_facade_callback_files = $facadeCallbackFiles.Count
        ambient_renderer_lookup_files = $ambientRendererLookupFiles.Count
        thread_static_files = $threadStaticFiles.Count
        ambient_thread_state_files = $ambientThreadStateFiles.Count
    }
    structural_gates = [ordered]@{
        source_budget = [ordered]@{
            hand_written_line_ceiling = 200000
            hand_written_physical_lines = $handWrittenLineCount
            passes = $handWrittenLineCount -le 200000
            file_count = $sourceFiles.Count
            file_count_is_informational = $true
            organization_rule = 'Prefer one top-level type per file; do not merge unrelated types to reduce file count.'
        }
        lifecycle_spine = [ordered]@{
            file_budget = 40
            line_budget = 20000
            file_count = $lifecycleSpineFiles.Count
            physical_lines = $lifecycleSpineLineCount
            passes = $lifecycleSpineMissingFiles.Count -eq 0 -and
                $lifecycleSpineFiles.Count -le 40 -and
                $lifecycleSpineLineCount -le 20000
            files = @($lifecycleSpineFiles)
            missing_files = $lifecycleSpineMissingFiles
        }
        main_frame_orchestration = [ordered]@{
            logical_line_budget = 100
            method = @($mainFrameMethod)
            passes = $mainFrameMethod.Count -eq 1 -and
                [int]$mainFrameMethod[0].logical_line_estimate -le 100
        }
        size_review = [ordered]@{
            approval = $structuralExceptionManifest.approval
            file_line_threshold = 1500
            method_logical_line_threshold = 150
            oversized_files = $oversizedFiles
            oversized_file_count = $oversizedFiles.Count
            oversized_methods = $oversizedMethods
            oversized_method_count = $oversizedMethods.Count
            unapproved_oversized_files = @($unapprovedOversizedFiles)
            unapproved_oversized_file_count = $unapprovedOversizedFiles.Count
            unapproved_oversized_methods = @($unapprovedOversizedMethods)
            unapproved_oversized_method_count = $unapprovedOversizedMethods.Count
            passes = $unapprovedOversizedFiles.Count -eq 0 -and
                $unapprovedOversizedMethods.Count -eq 0
        }
        type_organization = [ordered]@{
            multiple_top_level_type_files = @($multipleTopLevelTypeFiles)
            multiple_top_level_type_file_count = $multipleTopLevelTypeFiles.Count
            partial_types = $partialTypeRecords
            partial_type_count = $partialTypeRecords.Count
        }
        canonical_roles = [ordered]@{
            roles = @($canonicalRoleRecords)
            role_count = $canonicalRoleRecords.Count
            violation_count = $canonicalRoleViolationCount
            passes = $canonicalRoleViolationCount -eq 0
        }
    }
    authority_matches = $authorityMatches
    authority_dependency_edges = @($authorityDependencyEdges)
    approved_authority_edges = $approvedAuthorityEdges
    authority_dependency_violations = @($authorityDependencyViolations)
    authority_renderer_backlink_files = @($authorityRendererBacklinkFiles | Sort-Object -Unique)
    retained_type_graph = [ordered]@{
        hard_gate = [ordered]@{
            approved_direct_authority_compositions = @($approvedDirectAuthorityCompositions)
            approved_direct_authority_composition_count = $approvedDirectAuthorityCompositions.Count
            direct_authority_violations = @($hardGateDirectAuthorityViolations)
            direct_authority_violation_count = $hardGateDirectAuthorityViolations.Count
            approved_callable_service_location_compositions = @($approvedCallableServiceLocationCompositions)
            approved_callable_service_location_composition_count = $approvedCallableServiceLocationCompositions.Count
            callable_retained_service_location_violations = @($hardGateCallableServiceLocationViolations)
            callable_retained_service_location_violation_count = $hardGateCallableServiceLocationViolations.Count
            all_authorities_context_violations = @($allAuthoritiesContextViolations)
            all_authorities_context_violation_count = $allAuthoritiesContextViolations.Count
            violation_count = $hardGateViolationCount
        }
        advisory_transitive_immutable_payload_reach = [ordered]@{
            multi_authority_types = @($retainedMultiAuthorityTypes)
            multi_authority_type_count = $retainedMultiAuthorityTypes.Count
        }
        direct_authority_members = @($effectiveDirectAuthorityMembers)
        direct_authority_member_count = $effectiveDirectAuthorityMembers.Count
        multi_authority_types = @($retainedMultiAuthorityTypes)
        multi_authority_type_count = $retainedMultiAuthorityTypes.Count
        authority_retained_multi_authority_types = @($authorityRetainedMultiAuthorityTypes)
        authority_retained_multi_authority_type_count = $authorityRetainedMultiAuthorityTypes.Count
        raw_authority_properties = @($rawAuthorityProperties)
        raw_authority_property_count = $rawAuthorityProperties.Count
        output_target_imgui_multi_authority_types = $outputTargetImGuiMultiAuthorityTypes
        output_target_imgui_multi_authority_type_count = $outputTargetImGuiMultiAuthorityTypes.Count
        output_target_imgui_raw_authority_properties = $outputTargetImGuiRawAuthorityProperties
        output_target_imgui_raw_authority_property_count = $outputTargetImGuiRawAuthorityProperties.Count
    }
    largest_files = @(
        $fileRecords |
            Sort-Object { [int]$_.lines } -Descending |
            Select-Object -First $LargestFileCount)
    largest_method_span_estimates = @(
        $methodRecords |
            Sort-Object { [int]$_.logical_line_estimate } -Descending |
            Select-Object -First $LargestFileCount)
    renderer_partial_files = @($rendererPartialFiles)
    renderer_non_partial_files = @($rendererNonPartialFiles)
    unsafe_type_files = @($unsafeTypeFiles)
    ambient_facade_callback_files = @($facadeCallbackFiles)
    ambient_renderer_lookup_files = @($ambientRendererLookupFiles)
    thread_static_files = @($threadStaticFiles)
    ambient_thread_state_files = @($ambientThreadStateFiles)
    methodology = [ordered]@{
        physical_lines = 'One plus LF count for non-empty source files.'
        generated_source = 'Filename suffix or auto-generated/GeneratedCode marker.'
        renderer_fields = 'Lexical declaration estimate across VulkanRenderer and VulkanRendererRuntime partial implementations; review before using as an ownership gate.'
        facade_gate = 'Counts non-partial VulkanRenderer declarations, direct AbstractRenderer<Vk> bases, physical lines in their declaring files, and the seven exact readonly authority-root field types.'
        method_spans = 'Structural lexical spans with comments and literals blanked at stable offsets; logical estimates exclude blank and brace-only lines. Findings remain review prompts rather than a substitute for control-flow review.'
        lifecycle_spine = 'An explicit checked-in manifest of the facade entry, desktop acquire-to-settlement orchestration, planner/scheduler/record/submit roots, transaction contracts, and telemetry roots. Leaf feature encoders and backend-object implementations are excluded by design.'
        source_budget = 'Global file count is informational because the repository requires one top-level type per file. The hard source ceiling is paired with per-file/per-method review lists so consolidation cannot be achieved by combining unrelated types or deleting supported behavior.'
        canonical_roles = 'Explicit role ledger requiring one named declaration family for each root scheduling, planning, descriptor, lifetime, command, and telemetry responsibility while rejecting retired competing owner names. Focused leaf algorithms are not classified as root authorities.'
        dependency_edges = 'Observed authority-name references in files which declare the source authority; approved-edge violations and renderer backlinks are reported separately.'
        retained_type_graph = 'Conservative retained graph of declared instance fields, one-line auto-properties, and primary-constructor parameters. Edges preserve declaring file, line, and member name; generic arguments are not edges. Authority roots terminate traversal. The hard gate reports two or more direct authority members or callable retained service-location members; transitive immutable-payload reach is advisory only.'
        facade_callbacks = 'A receiver declared with the concrete VulkanRenderer type and subsequently dereferenced in the same file; unrelated mesh, OpenGL, and target-capability variables named renderer are excluded.'
    }
}

$json = $result | ConvertTo-Json -Depth 8
if (-not [string]::IsNullOrWhiteSpace($OutputPath)) {
    $resolvedOutputPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
        [System.IO.Path]::GetFullPath($OutputPath)
    }
    else {
        [System.IO.Path]::GetFullPath((Join-Path $repoRoot $OutputPath))
    }
    [System.IO.Directory]::CreateDirectory(
        [System.IO.Path]::GetDirectoryName($resolvedOutputPath)) | Out-Null
    [System.IO.File]::WriteAllText(
        $resolvedOutputPath,
        $json,
        [System.Text.UTF8Encoding]::new($false))
}

$json
