[CmdletBinding()]
param(
    [string]$SourceRoot = 'XREngine.Runtime.Rendering.Vulkan\Rendering\API\Rendering\Vulkan',
    [string]$OutputPath = '',
    [ValidateRange(1, 200)]
    [int]$LargestFileCount = 30
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$resolvedSourceRoot = if ([System.IO.Path]::IsPathRooted($SourceRoot)) {
    [System.IO.Path]::GetFullPath($SourceRoot)
}
else {
    [System.IO.Path]::GetFullPath((Join-Path $repoRoot $SourceRoot))
}

if (-not [System.IO.Directory]::Exists($resolvedSourceRoot)) {
    throw "Vulkan source root does not exist: $resolvedSourceRoot"
}

function Get-PortableRelativePath([string]$BasePath, [string]$Path) {
    $baseWithSeparator = $BasePath.TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar) +
        [System.IO.Path]::DirectorySeparatorChar
    $baseUri = [Uri]::new($baseWithSeparator)
    $pathUri = [Uri]::new([System.IO.Path]::GetFullPath($Path))
    return [Uri]::UnescapeDataString(
        $baseUri.MakeRelativeUri($pathUri).ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

function Get-RelativePath([string]$Path) {
    return (Get-PortableRelativePath $repoRoot $Path).Replace('\', '/')
}

function Test-GeneratedSource([System.IO.FileInfo]$File, [string]$Source) {
    return $File.Name -match '\.(?:g|generated)\.cs$' -or
        $Source.IndexOf('<auto-generated', [System.StringComparison]::OrdinalIgnoreCase) -ge 0 -or
        $Source.IndexOf('[GeneratedCode(', [System.StringComparison]::Ordinal) -ge 0
}

function Get-DeclarationCount([string]$Source, [string]$Pattern) {
    return [regex]::Matches(
        $Source,
        $Pattern,
        [System.Text.RegularExpressions.RegexOptions]::Multiline).Count
}

function Get-MaxDirectoryDepth([System.IO.FileInfo[]]$Files) {
    $maximumDepth = 0
    foreach ($file in $Files) {
        $relativeDirectory = Get-PortableRelativePath $resolvedSourceRoot $file.DirectoryName
        $depth = if ($relativeDirectory -eq '.') {
            0
        }
        else {
            $relativeDirectory.Split(
                [System.IO.Path]::DirectorySeparatorChar,
                [System.StringSplitOptions]::RemoveEmptyEntries).Length
        }
        if ($depth -gt $maximumDepth) {
            $maximumDepth = $depth
        }
    }
    return $maximumDepth
}

function Get-MethodSpanEstimates(
    [System.IO.FileInfo]$File,
    [string]$Source) {
    $lines = $Source -split "`r?`n"
    $methods = [System.Collections.Generic.List[object]]::new()
    for ($lineIndex = 0; $lineIndex -lt $lines.Length; $lineIndex++) {
        $line = $lines[$lineIndex]
        if ($line -match '\b(?:class|struct|record|interface)\s+[A-Za-z_]') {
            continue
        }
        if ($line -notmatch '^\s*(?:(?:public|private|protected|internal|static|sealed|virtual|override|abstract|async|unsafe|extern|new|partial|readonly)\s+)+(?:[\w.<>\[\],?]+\s+)+(?<name>[A-Za-z_]\w*)\s*(?:<[^>]+>)?\s*\(') {
            continue
        }

        $methodName = $Matches.name
        $signatureEnd = $lineIndex
        while ($signatureEnd -lt $lines.Length - 1 -and
               $lines[$signatureEnd].IndexOf('{') -lt 0 -and
               $lines[$signatureEnd].IndexOf('=>') -lt 0 -and
               $lines[$signatureEnd].IndexOf(';') -lt 0) {
            $signatureEnd++
        }

        if ($lines[$signatureEnd].IndexOf('=>') -ge 0 -or
            $lines[$signatureEnd].TrimEnd().EndsWith(';')) {
            $methods.Add([ordered]@{
                path = Get-RelativePath $File.FullName
                method = $methodName
                start_line = $lineIndex + 1
                logical_line_estimate = $signatureEnd - $lineIndex + 1
            })
            $lineIndex = $signatureEnd
            continue
        }

        $braceDepth = 0
        $opened = $false
        $methodEnd = $signatureEnd
        for ($bodyLine = $signatureEnd; $bodyLine -lt $lines.Length; $bodyLine++) {
            $openCount = ([regex]::Matches($lines[$bodyLine], '\{')).Count
            $closeCount = ([regex]::Matches($lines[$bodyLine], '\}')).Count
            if ($openCount -gt 0) {
                $opened = $true
            }
            $braceDepth += $openCount - $closeCount
            $methodEnd = $bodyLine
            if ($opened -and $braceDepth -le 0) {
                break
            }
        }

        $methods.Add([ordered]@{
            path = Get-RelativePath $File.FullName
            method = $methodName
            start_line = $lineIndex + 1
            logical_line_estimate = $methodEnd - $lineIndex + 1
        })
        $lineIndex = $methodEnd
    }
    return @($methods)
}

$sourceFiles = @(
    Get-ChildItem -LiteralPath $resolvedSourceRoot -Recurse -File -Filter '*.cs' |
        Sort-Object FullName
)

$fileRecords = [System.Collections.Generic.List[object]]::new($sourceFiles.Count)
$rendererPartialFiles = [System.Collections.Generic.List[string]]::new()
$unsafeTypeFiles = [System.Collections.Generic.List[string]]::new()
$threadStaticFiles = [System.Collections.Generic.List[string]]::new()
$ambientThreadStateFiles = [System.Collections.Generic.List[string]]::new()
$facadeCallbackFiles = [System.Collections.Generic.List[string]]::new()
$ambientRendererLookupFiles = [System.Collections.Generic.List[string]]::new()
$methodRecords = [System.Collections.Generic.List[object]]::new()
$handWrittenLineCount = 0
$generatedLineCount = 0
$rendererPartialDeclarationCount = 0
$rendererFieldEstimate = 0

foreach ($file in $sourceFiles) {
    $source = [System.IO.File]::ReadAllText($file.FullName)
    $lineCount = if ($source.Length -eq 0) {
        0
    }
    else {
        1 + (Get-DeclarationCount $source "`n")
    }
    $generated = Test-GeneratedSource $file $source
    if ($generated) {
        $generatedLineCount += $lineCount
    }
    else {
        $handWrittenLineCount += $lineCount
    }

    # Count renamed implementation shells as renderer partials too. A partial
    # monolith does not become a facade merely by moving "Renderer" out of the
    # public type name and inheriting from it.
    $partialCount = Get-DeclarationCount $source '\bpartial\s+(?:(?:sealed|abstract|unsafe)\s+)*class\s+VulkanRenderer(?:Runtime)?\b'
    if ($partialCount -gt 0) {
        $rendererPartialDeclarationCount += $partialCount
        $rendererPartialFiles.Add((Get-RelativePath $file.FullName))
        $rendererFieldEstimate += Get-DeclarationCount $source '^[ \t]*(?:(?:public|private|protected|internal|static|readonly|volatile|unsafe|new|required)\s+)+[A-Za-z_][\w<>,.?\[\]: \t]*\s+[A-Za-z_]\w*\s*(?:=(?!>)|;)'
    }

    if ($source -match '\b(?:public|internal|private|protected)\s+unsafe\s+(?:partial\s+)?(?:class|struct|record)\b') {
        $unsafeTypeFiles.Add((Get-RelativePath $file.FullName))
    }
    $hasThreadStatic = $source.IndexOf('[ThreadStatic]', [System.StringComparison]::Ordinal) -ge 0 -or
        $source.IndexOf('ThreadStaticAttribute', [System.StringComparison]::Ordinal) -ge 0
    if ($hasThreadStatic) {
        $threadStaticFiles.Add((Get-RelativePath $file.FullName))
    }
    if ($hasThreadStatic -or $source -match '\bstatic\s+(?:readonly\s+)?ThreadLocal<') {
        $ambientThreadStateFiles.Add((Get-RelativePath $file.FullName))
    }
    if ($source -match '\b(?:_renderer|Renderer)\.[A-Za-z_]\w*\s*\(') {
        $facadeCallbackFiles.Add((Get-RelativePath $file.FullName))
    }
    if ($source -match '\b(?:AbstractRenderer\.Current|RuntimeRenderingHostServices\.FrameTiming\.CurrentRenderer)\b') {
        $ambientRendererLookupFiles.Add((Get-RelativePath $file.FullName))
    }

    $fileRecords.Add([ordered]@{
        path = Get-RelativePath $file.FullName
        lines = $lineCount
        generated = $generated
        renderer_partial_declarations = $partialCount
    })
    foreach ($methodRecord in @(Get-MethodSpanEstimates $file $source)) {
        $methodRecords.Add($methodRecord)
    }
}

$authorityPatterns = [ordered]@{
    device = 'VulkanDeviceContext'
    output = 'VulkanOutputRuntime|VulkanDesktopWsiTargetDriver|IVulkanRendererTargetDriver'
    frame_loop = 'VulkanFrameLoop|VulkanDesktopFrameCoordinator'
    planner = 'VulkanFramePlanner|VulkanResourcePlanCoordinator|VulkanRenderGraphRuntime'
    resources = 'VulkanResourceRuntime|VulkanResourceLifetimeTracker|VulkanDescriptorManager|VulkanPipelineManager'
    commands = 'VulkanCommandRuntime|VulkanCommandScheduler|VulkanCommandRecorder|VulkanQueueGateway'
    telemetry = 'VulkanFrameTelemetry|VulkanFrameTrace|VulkanFrameTiming'
}

$authorityMatches = [ordered]@{}
foreach ($entry in $authorityPatterns.GetEnumerator()) {
    $authorityFiles = [System.Collections.Generic.List[string]]::new()
    foreach ($file in $sourceFiles) {
        $source = [System.IO.File]::ReadAllText($file.FullName)
        # Source ownership is declaration-based. Classifying every file which merely
        # mentions an authority makes a facade composition file appear to own every
        # authority and produces meaningless all-to-all dependency edges.
        $declarationPattern = "\b(?:class|struct|interface|record(?:\s+(?:class|struct))?)\s+(?:$($entry.Value))\b"
        if ($source -match $declarationPattern) {
            $authorityFiles.Add((Get-RelativePath $file.FullName))
        }
    }
    $authorityMatches[$entry.Key] = @($authorityFiles)
}

$approvedAuthorityEdges = [ordered]@{
    device = @()
    output = @('device', 'telemetry')
    frame_loop = @('output', 'planner', 'resources', 'commands', 'device', 'telemetry')
    planner = @('resources', 'device', 'telemetry')
    resources = @('device', 'telemetry')
    commands = @('resources', 'device', 'telemetry')
    telemetry = @()
}

$authorityRendererBacklinkFiles = [System.Collections.Generic.List[string]]::new()
foreach ($entry in $authorityMatches.GetEnumerator()) {
    foreach ($sourceFilePath in @($entry.Value)) {
        $sourceFile = Join-Path $repoRoot $sourceFilePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $source = [System.IO.File]::ReadAllText($sourceFile)
        if ($source -match '\bVulkanRenderer\b') {
            $authorityRendererBacklinkFiles.Add($sourceFilePath)
        }
    }
}

$authorityDependencyEdges = [System.Collections.Generic.List[object]]::new()
foreach ($sourceEntry in $authorityPatterns.GetEnumerator()) {
    foreach ($sourceFilePath in @($authorityMatches[$sourceEntry.Key])) {
        $sourceFile = Join-Path $repoRoot $sourceFilePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $source = [System.IO.File]::ReadAllText($sourceFile)
        foreach ($targetEntry in $authorityPatterns.GetEnumerator()) {
            if ($targetEntry.Key -eq $sourceEntry.Key -or
                $source -notmatch "\b(?:$($targetEntry.Value))\b") {
                continue
            }
            $authorityDependencyEdges.Add([ordered]@{
                source_authority = $sourceEntry.Key
                target_authority = $targetEntry.Key
                path = $sourceFilePath
            })
        }
    }
}

$authorityDependencyViolations = [System.Collections.Generic.List[object]]::new()
foreach ($edge in $authorityDependencyEdges) {
    if ($approvedAuthorityEdges[$edge.source_authority] -notcontains $edge.target_authority) {
        $authorityDependencyViolations.Add($edge)
    }
}

$result = [ordered]@{
    schema_version = 1
    generated_utc = [DateTime]::UtcNow.ToString('O')
    repository_root = $repoRoot
    source_root = Get-RelativePath $resolvedSourceRoot
    totals = [ordered]@{
        files = $sourceFiles.Count
        hand_written_files = @($fileRecords | Where-Object { -not $_.generated }).Count
        generated_files = @($fileRecords | Where-Object generated).Count
        physical_lines = $handWrittenLineCount + $generatedLineCount
        hand_written_physical_lines = $handWrittenLineCount
        generated_physical_lines = $generatedLineCount
        maximum_directory_depth = Get-MaxDirectoryDepth $sourceFiles
    }
    facade = [ordered]@{
        renderer_partial_files = $rendererPartialFiles.Count
        renderer_partial_declarations = $rendererPartialDeclarationCount
        renderer_field_estimate = $rendererFieldEstimate
        unsafe_type_files = $unsafeTypeFiles.Count
        ambient_facade_callback_files = $facadeCallbackFiles.Count
        ambient_renderer_lookup_files = $ambientRendererLookupFiles.Count
        thread_static_files = $threadStaticFiles.Count
        ambient_thread_state_files = $ambientThreadStateFiles.Count
    }
    authority_matches = $authorityMatches
    authority_dependency_edges = @($authorityDependencyEdges)
    approved_authority_edges = $approvedAuthorityEdges
    authority_dependency_violations = @($authorityDependencyViolations)
    authority_renderer_backlink_files = @($authorityRendererBacklinkFiles | Sort-Object -Unique)
    largest_files = @(
        $fileRecords |
            Sort-Object { [int]$_.lines } -Descending |
            Select-Object -First $LargestFileCount)
    largest_method_span_estimates = @(
        $methodRecords |
            Sort-Object { [int]$_.logical_line_estimate } -Descending |
            Select-Object -First $LargestFileCount)
    renderer_partial_files = @($rendererPartialFiles)
    unsafe_type_files = @($unsafeTypeFiles)
    ambient_facade_callback_files = @($facadeCallbackFiles)
    ambient_renderer_lookup_files = @($ambientRendererLookupFiles)
    thread_static_files = @($threadStaticFiles)
    ambient_thread_state_files = @($ambientThreadStateFiles)
    methodology = [ordered]@{
        physical_lines = 'One plus LF count for non-empty source files.'
        generated_source = 'Filename suffix or auto-generated/GeneratedCode marker.'
        renderer_fields = 'Lexical declaration estimate across VulkanRenderer and VulkanRendererRuntime partial implementations; review before using as an ownership gate.'
        method_spans = 'Lexical brace-span estimates; braces in strings/comments can over-count and require review.'
        dependency_edges = 'Observed authority-name references in files which declare the source authority; approved-edge violations and renderer backlinks are reported separately.'
    }
}

$json = $result | ConvertTo-Json -Depth 8
if (-not [string]::IsNullOrWhiteSpace($OutputPath)) {
    $resolvedOutputPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
        [System.IO.Path]::GetFullPath($OutputPath)
    }
    else {
        [System.IO.Path]::GetFullPath((Join-Path $repoRoot $OutputPath))
    }
    [System.IO.Directory]::CreateDirectory(
        [System.IO.Path]::GetDirectoryName($resolvedOutputPath)) | Out-Null
    [System.IO.File]::WriteAllText(
        $resolvedOutputPath,
        $json,
        [System.Text.UTF8Encoding]::new($false))
}

$json
