using System;
using System.ComponentModel;
using System.Numerics;
using XREngine;
using XREngine.Data.Geometry;
using XREngine.Data.Rendering;
using XREngine.Diagnostics;
using XREngine.Rendering;
using XREngine.Rendering.Commands;
using XREngine.Rendering.Info;
using XREngine.Rendering.Models;
using XREngine.Rendering.Models.Materials;
using XREngine.Rendering.Tools;
using XREngine.Scene.Transforms;

namespace XREngine.Components.Scene.Mesh
{
    /// <summary>
    /// Renders a camera-facing quad that blends between 26 baked octahedral imposter views.
    /// </summary>
    [Serializable]
    [Category("Rendering")]
    [DisplayName("Octahedral Billboard")]
    [Description("Renders a camera-facing quad that samples a baked octahedral imposter texture array.")]
    public sealed class OctahedralBillboardComponent : XRComponent, IRenderable
    {
        private static readonly Vector2 s_minSize = new(0.01f);

        private readonly RenderCommandMesh3D _renderCommand;
        private readonly RenderInfo3D _renderInfo;
        private readonly RenderInfo[] _renderInfos;

        private Vector2 _billboardSize = Vector2.One;
        private Vector3 _billboardLocalCenter;
        private XRTexture2DArray? _imposterViews;
        private OctahedralBillboardAsset? _impostorAsset;
        private int _renderLayer;
        private bool _castsShadows;

        private XRMesh? _mesh;
        private XRMeshRenderer? _renderer;
        private XRMaterial? _material;
        private XRShader? _vertexShader;
        private XRShader? _fragmentShader;

        public OctahedralBillboardComponent()
        {
            _renderCommand = new RenderCommandMesh3D((int)EDefaultRenderPass.TransparentForward)
            {
                WorldMatrixIsModelMatrix = true,
                WorldMatrix = Matrix4x4.Identity,
                Instances = 1u
            };

            _renderInfo = RenderInfo3D.New(this, _renderCommand);
            _renderInfo.CastsShadows = false;
            _renderInfo.ReceivesShadows = false;
            _renderInfos = [_renderInfo];

            UpdateCullingVolume();
            UpdateRenderMatrices();
            RecreateRenderer();
        }

        /// <summary>
        /// Local width (X) and height (Y) of the billboard quad before billboarding is applied.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Quad Size")]
        [Description("Local width (X) and height (Y) of the billboard quad before billboarding is applied.")]
        public Vector2 BillboardSize
        {
            get => _billboardSize;
            set
            {
                Vector2 sanitized = SanitizeSize(value);
                if (SetField(ref _billboardSize, sanitized))
                {
                    UpdateCullingVolume();
                    RecreateRenderer();
                }
            }
        }

        /// <summary>
        /// Local-space center captured by the impostor bake. The billboard is rendered around this point.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Local Center")]
        [Description("Local-space center captured by the impostor bake. The billboard is rendered around this point.")]
        public Vector3 BillboardLocalCenter
        {
            get => _billboardLocalCenter;
            set
            {
                if (SetField(ref _billboardLocalCenter, value))
                    UpdateRenderMatrices();
            }
        }

        /// <summary>
        /// Texture array containing the 26 baked views generated by <see cref="OctahedralImposterGenerator"/>.
        /// Layer ordering must match <see cref="OctahedralImposterGenerator"/> and the runtime shader.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Imposter Views")]
        [Description("Texture array containing the 26 baked captures in the generator's order.")]
        public XRTexture2DArray? ImposterViews
        {
            get => _imposterViews;
            set
            {
                if (value is not null)
                    OctahedralBillboardAsset.ConfigureColorViewTexture(value);

                if (SetField(ref _imposterViews, value))
                    UpdateMaterialTexture();
            }
        }

        /// <summary>
        /// Persistent baked impostor asset containing the texture array and capture metadata.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Impostor Asset")]
        [Description("Persistent baked impostor asset containing the texture array and capture metadata.")]
        public OctahedralBillboardAsset? ImpostorAsset
        {
            get => _impostorAsset;
            set
            {
                if (SetField(ref _impostorAsset, value))
                    ApplyAsset(value, matchBounds: true);
            }
        }

        [Category("Rendering")]
        [DisplayName("Layer")]
        [Description("Render layer used by cameras for visibility filtering.")]
        public int RenderLayer
        {
            get => _renderLayer;
            set
            {
                int sanitized = Math.Clamp(value, 0, 31);
                if (SetField(ref _renderLayer, sanitized))
                    _renderInfo.Layer = sanitized;
            }
        }

        [Category("Rendering")]
        [DisplayName("Casts Shadows")]
        [Description("Whether this billboard contributes to shadow passes. Disabled by default for v1 color-only impostors.")]
        public bool CastsShadows
        {
            get => _castsShadows;
            set
            {
                if (SetField(ref _castsShadows, value))
                    _renderInfo.CastsShadows = value;
            }
        }

        public RenderInfo[] RenderedObjects => _renderInfos;

        /// <summary>
        /// Copies texture data and approximate sizing from a freshly baked impostor capture.
        /// </summary>
        public void ApplyCaptureResult(OctahedralImposterGenerator.Result result, bool matchBounds = true)
        {
            ArgumentNullException.ThrowIfNull(result);
            SetField(ref _impostorAsset, result.Asset, nameof(ImpostorAsset));
            ApplyAsset(result.Asset, matchBounds);
        }

        /// <summary>
        /// Applies a persistent baked impostor asset to this billboard.
        /// </summary>
        public void ApplyAsset(OctahedralBillboardAsset? asset, bool matchBounds = true)
        {
            ImposterViews = asset?.ColorViews;

            if (asset is null)
                return;

            BillboardLocalCenter = asset.CaptureCenterLocal;
            RenderLayer = asset.SourceLayer;
            CastsShadows = false;

            if (matchBounds)
                BillboardSize = asset.BillboardSize;
        }

        protected override void OnTransformRenderWorldMatrixChanged(TransformBase transform, Matrix4x4 renderMatrix)
        {
            base.OnTransformRenderWorldMatrixChanged(transform, renderMatrix);
            UpdateRenderMatrices();
        }

        protected override void OnDestroying()
        {
            base.OnDestroying();
            DisposeRenderer();
        }

        private void RecreateRenderer()
        {
            DisposeRenderer();

            XRMesh? mesh = BuildQuadMesh();
            XRMaterial? material = BuildMaterial();
            if (mesh is null || material is null)
            {
                Debug.RenderingWarning("Failed to build octahedral billboard renderer. Renderer will be inactive.");
                return;
            }

            _mesh = mesh;
            _material = material;
            _renderer = new XRMeshRenderer(mesh, material);

            _renderCommand.Mesh = _renderer;
            _renderCommand.RenderPass = material.RenderPass;
            _renderCommand.Instances = 1u;

            UpdateRenderMatrices();
        }

        private XRMesh? BuildQuadMesh()
        {
            XRMesh quad = XRMesh.Create(VertexQuad.PosZ(
                _billboardSize.X,
                _billboardSize.Y,
                0.0f,
                bottomLeftOrigin: false,
                flipVerticalUVCoord: false));
            quad.SupportsBillboarding = false;
            return quad;
        }

        private XRMaterial? BuildMaterial()
        {
            XRShader? vertex = LoadVertexShader();
            XRShader? fragment = LoadFragmentShader();
            if (vertex is null || fragment is null)
                return null;

            XRMaterial material = new(vertex, fragment)
            {
                BillboardMode = EMeshBillboardMode.None,
                RenderPass = (int)EDefaultRenderPass.TransparentForward,
                RenderOptions = new RenderingParameters
                {
                    CullMode = ECullMode.None,
                    BlendModeAllDrawBuffers = BlendMode.EnabledTransparent(),
                    DepthTest = new DepthTest
                    {
                        Enabled = ERenderParamUsage.Enabled,
                        Function = EComparison.Lequal,
                        UpdateDepth = false
                    },
                    RequiredEngineUniforms = EUniformRequirements.Camera
                }
            };

            UpdateMaterialTexture(material);
            return material;
        }

        private XRShader? LoadVertexShader()
        {
            if (_vertexShader is not null)
                return _vertexShader;

            XRShader? shader = Engine.Assets.LoadEngineAsset<XRShader>(JobPriority.Highest, "Shaders", "Scene3D", "OctahedralImposterBillboard.vs");
            if (shader is null)
                Debug.RenderingWarning("Unable to load OctahedralImposterBillboard.vs.");
            _vertexShader = shader;
            return shader;
        }

        private XRShader? LoadFragmentShader()
        {
            if (_fragmentShader is not null)
                return _fragmentShader;

            XRShader? shader = Engine.Assets.LoadEngineAsset<XRShader>(JobPriority.Highest, "Shaders", "Scene3D", "OctahedralImposterBillboard.fs");
            if (shader is null)
            {
                Debug.RenderingWarning("Unable to load OctahedralImposterBillboard.fs. Billboard imposters will render blank.");
                shader = new XRShader(EShaderType.Fragment, ShaderHelper.Frag_Nothing);
            }

            _fragmentShader = shader;
            return shader;
        }

        private void UpdateMaterialTexture(XRMaterial? targetMaterial = null)
        {
            var mat = targetMaterial ?? _material;
            if (mat is null)
                return;

            if (_imposterViews is not null)
                OctahedralBillboardAsset.ConfigureColorViewTexture(_imposterViews);

            if (mat.Textures.Count == 0)
            {
                mat.Textures.Add(_imposterViews);
            }
            else
            {
                mat.Textures[0] = _imposterViews;
            }
        }

        private void UpdateCullingVolume()
        {
            float halfWidth = _billboardSize.X * 0.5f;
            float halfHeight = _billboardSize.Y * 0.5f;
            float radius = MathF.Sqrt(halfWidth * halfWidth + halfHeight * halfHeight);
            Vector3 halfExtents = new(radius, radius, radius);
            _renderInfo.LocalCullingVolume = new AABB(-halfExtents, halfExtents);
        }

        private void UpdateRenderMatrices()
        {
            Matrix4x4 centeredMatrix = GetCenteredRenderMatrix();
            _renderCommand.WorldMatrix = centeredMatrix;
            _renderInfo.CullingOffsetMatrix = centeredMatrix;
        }

        private Matrix4x4 GetCenteredRenderMatrix()
            => Matrix4x4.CreateTranslation(_billboardLocalCenter) * Transform.RenderMatrix;

        private void DisposeRenderer()
        {
            _renderCommand.Mesh = null;

            _renderer?.Destroy();
            _renderer = null;

            _mesh?.Destroy();
            _mesh = null;

            _material?.Destroy();
            _material = null;
        }

        private static Vector2 SanitizeSize(Vector2 size)
        {
            float width = MathF.Max(s_minSize.X, float.IsFinite(size.X) ? size.X : s_minSize.X);
            float height = MathF.Max(s_minSize.Y, float.IsFinite(size.Y) ? size.Y : s_minSize.Y);
            return new Vector2(width, height);
        }
    }
}
