namespace XREngine;

public enum ERvcDebugViewMode
{
    Disabled,
    ViewSet,
    HiddenAreaMask,
    Depth,
    LinearDepth,
    VisibilityId,
    InstanceId,
    DrawOrMeshletId,
    PrimitiveId,
    MaterialId,
    TransformId,
    ReconstructionError,
    ShadeletDensity,
    PixelToShadelet,
    ShadeletKeyHash,
    MaterialBinOccupancy,
    ReuseSource,
    ReuseRejectionReason,
    HeadSpaceClusterId,
    ClusterOccupancy,
    ExactLightCount,
    AggregateContribution,
    ReservoirWeight,
    TemporalCacheAge,
    TemporalCacheConfidence,
    FinalResolve,
    TransparentForwardPlusOverlay,
    WideInsetComposition,
    PerformanceCounters,
}
