// <auto-generated />
// Generated by Tools/Generate-BrowserRegistrations.py from XREngine.Browser/browser-registration-manifest.json.
using System.Numerics;
using XREngine.Components;
using XREngine.Rendering;
using XREngine.Rendering.WebGPU;
using XREngine.Scene;
using XREngine.Scene.Transforms;

namespace XREngine.Browser;

/// <summary>Explicit factories and stable IDs for the portable browser scene format.</summary>
internal static class BrowserStaticRegistrations
{
    internal const string MeshComponentId = "xre.browser.v1.component.mesh";
    internal const string SpinComponentId = "xre.browser.v1.component.spin";
    internal const string SceneBootComponentId = "xre.browser.v1.component.scene-boot";
    internal const string TransformId = "xre.browser.v1.transform.trs";
    internal const string MeshId = "xre.browser.v1.resource.mesh";
    internal const string TextureId = "xre.browser.v1.resource.texture-rgba8";
    internal const string MaterialId = "xre.browser.v1.resource.material-unlit";
    internal const string SnapshotId = "xre.browser.v1.resource.scene-snapshot";
    internal const string SceneJsonId = "xre.browser.v1.serializer.scene-json";
    internal const string WebGpuModuleId = "xre.browser.v1.module.webgpu";

    internal static void Initialize()
        => TransformFactoryRegistry.Register<Transform>(static () => new Transform());

    internal static string GetRequiredTypeId(Type type)
    {
        ArgumentNullException.ThrowIfNull(type);
        return type == typeof(BrowserMeshComponent) ? MeshComponentId :
            type == typeof(BrowserSpinComponent) ? SpinComponentId :
            type == typeof(SceneBootComponent) ? SceneBootComponentId :
            type == typeof(Transform) ? TransformId :
            type == typeof(BrowserMeshData) ? MeshId :
            type == typeof(BrowserTextureData) ? TextureId :
            type == typeof(BrowserMaterialData) ? MaterialId :
            type == typeof(BrowserSceneSnapshot) ? SnapshotId :
            type == typeof(WebGpuRendererBackendModule) ? WebGpuModuleId :
            throw new NotSupportedException($"Type {type} is not included in the browser profile.");
    }

    internal static Type ResolveRequiredType(string id) => id switch
    {
        "xre.browser.v1.component.mesh" => typeof(global::XREngine.Browser.BrowserMeshComponent),
        "xre.browser.v1.component.scene-boot" => typeof(global::XREngine.Browser.SceneBootComponent),
        "xre.browser.v1.component.spin" => typeof(global::XREngine.Browser.BrowserSpinComponent),
        "xre.browser.v1.transform.trs" => typeof(global::XREngine.Scene.Transforms.Transform),
        "xre.browser.v1.resource.material-unlit" => typeof(global::XREngine.Rendering.BrowserMaterialData),
        "xre.browser.v1.resource.mesh" => typeof(global::XREngine.Rendering.BrowserMeshData),
        "xre.browser.v1.resource.scene-snapshot" => typeof(global::XREngine.Rendering.BrowserSceneSnapshot),
        "xre.browser.v1.resource.texture-rgba8" => typeof(global::XREngine.Rendering.BrowserTextureData),
        "xre.browser.v1.module.webgpu" => typeof(global::XREngine.Rendering.WebGPU.WebGpuRendererBackendModule),
        _ => throw new NotSupportedException($"Browser type ID {id} is unknown or unsupported.")
    };

    internal static XRComponent AddRequiredComponent(string id, SceneNode node)
    {
        ArgumentNullException.ThrowIfNull(node);
        XRComponent? component = id switch
        {
            MeshComponentId => node.AddComponent(static () => new BrowserMeshComponent()),
            SpinComponentId => node.AddComponent(static () => new BrowserSpinComponent()),
            SceneBootComponentId => node.AddComponent(static () => new SceneBootComponent()),
            _ => throw new NotSupportedException($"Browser component ID {id} is unknown or unsupported.")
        };
        return component ?? throw new InvalidOperationException("Browser component creation failed.");
    }

    internal static TransformBase CreateRequiredTransform(string id)
    {
        if (id != TransformId)
            throw new NotSupportedException($"Browser transform ID {id} is unknown or unsupported.");
        Initialize();
        return TransformFactoryRegistry.TryCreate(typeof(Transform), out TransformBase? transform)
            ? transform
            : throw new InvalidOperationException("Browser transform factory is unavailable.");
    }

    internal static BrowserMeshData CreateMesh(string id, ReadOnlySpan<float> vertices, ReadOnlySpan<uint> indices)
        => id == MeshId ? new BrowserMeshData(vertices, indices)
            : throw new NotSupportedException($"Browser mesh resource ID {id} is unknown or unsupported.");

    internal static BrowserTextureData CreateTexture(string id, int width, int height, ReadOnlySpan<byte> rgba)
        => id == TextureId ? new BrowserTextureData(width, height, rgba)
            : throw new NotSupportedException($"Browser texture resource ID {id} is unknown or unsupported.");

    internal static BrowserMaterialData CreateMaterial(string id, Vector4 tint, BrowserTextureData? texture = null)
        => id == MaterialId ? new BrowserMaterialData(tint, texture)
            : throw new NotSupportedException($"Browser material resource ID {id} is unknown or unsupported.");

    internal static BrowserSceneSnapshot DeserializeScene(string id, string json)
        => id == SceneJsonId ? BrowserSceneEnvelope.Deserialize(json)
            : throw new NotSupportedException($"Browser serializer ID {id} is unknown or unsupported.");

    internal static string SerializeScene(string id, BrowserSceneSnapshot scene)
    {
        ArgumentNullException.ThrowIfNull(scene);
        return id == SceneJsonId ? BrowserSceneEnvelope.Serialize(scene)
            : throw new NotSupportedException($"Browser serializer ID {id} is unknown or unsupported.");
    }

    internal static IRendererBackendModule CreateRendererModule(string id)
        => id == WebGpuModuleId ? new WebGpuRendererBackendModule()
            : throw new NotSupportedException($"Browser renderer module ID {id} is unknown or unsupported.");
}
