using XREngine.Data.Core;

namespace XREngine.Rendering.Models
{
    public class SubMeshLOD(
        XRMaterial? material,
        XRMesh? mesh,
        float maxVisibleDistance) : XRBase
    {
        private bool _isAutoGenerated;
        private float _generatedTargetIndexRatio;
        private float _generatedNormalizedError;
        private float _generatedObjectSpaceError;
        private float _minProjectedScreenRadiusPixels = float.NaN;

        public SubMeshLOD() 
            : this(null, null, 0) { }

        public SubMeshLOD(
            XRMaterial? material,
            XRMesh? mesh,
            float maxVisibleDistance,
            float minProjectedScreenRadiusPixels)
            : this(material, mesh, maxVisibleDistance)
        {
            _minProjectedScreenRadiusPixels = NormalizeProjectedRadius(minProjectedScreenRadiusPixels);
        }

        /// <summary>
        /// The material to use for this LOD.
        /// </summary>
        public XRMaterial? Material
        {
            get => material;
            set => SetField(ref material, value);
        }

        /// <summary>
        /// The mesh to render for this LOD.
        /// </summary>
        public XRMesh? Mesh
        {
            get => mesh;
            set => SetField(ref mesh, value);
        }

        public float MaxVisibleDistance
        {
            get => maxVisibleDistance;
            set => SetField(ref maxVisibleDistance, value);
        }

        /// <summary>
        /// Minimum projected bounding-sphere radius in pixels required to use this LOD in the GPU-driven path.
        /// NaN means the GPU scene should use its default projected-radius threshold for this LOD level.
        /// </summary>
        public float MinProjectedScreenRadiusPixels
        {
            get => _minProjectedScreenRadiusPixels;
            set => SetField(ref _minProjectedScreenRadiusPixels, NormalizeProjectedRadius(value));
        }

        private static float NormalizeProjectedRadius(float value)
            => float.IsFinite(value) ? System.MathF.Max(0.0f, value) : float.NaN;

        private bool _generateAsync;

        public bool GenerateAsync
        {
            get => _generateAsync;
            set => SetField(ref _generateAsync, value);
        }

        public bool IsAutoGenerated
        {
            get => _isAutoGenerated;
            set => SetField(ref _isAutoGenerated, value);
        }

        public float GeneratedTargetIndexRatio
        {
            get => _generatedTargetIndexRatio;
            set => SetField(ref _generatedTargetIndexRatio, value);
        }

        public float GeneratedNormalizedError
        {
            get => _generatedNormalizedError;
            set => SetField(ref _generatedNormalizedError, value);
        }

        public float GeneratedObjectSpaceError
        {
            get => _generatedObjectSpaceError;
            set => SetField(ref _generatedObjectSpaceError, value);
        }

        public XRMeshRenderer NewRenderer()
            => new(mesh, material) { GenerateAsync = GenerateAsync };
    }
}
