using XREngine.Data.Core;

namespace XREngine.Rendering.Models
{
    public class SubMeshLOD(
        XRMaterial? material,
        XRMesh? mesh,
        float maxVisibleDistance) : XRBase
    {
        private bool _isAutoGenerated;
        private float _generatedTargetIndexRatio;
        private float _generatedNormalizedError;
        private float _generatedObjectSpaceError;

        public SubMeshLOD() 
            : this(null, null, 0) { }

        /// <summary>
        /// The material to use for this LOD.
        /// </summary>
        public XRMaterial? Material
        {
            get => material;
            set => SetField(ref material, value);
        }

        /// <summary>
        /// The mesh to render for this LOD.
        /// </summary>
        public XRMesh? Mesh
        {
            get => mesh;
            set => SetField(ref mesh, value);
        }

        public float MaxVisibleDistance
        {
            get => maxVisibleDistance;
            set => SetField(ref maxVisibleDistance, value);
        }

        private bool _generateAsync;

        public bool GenerateAsync
        {
            get => _generateAsync;
            set => SetField(ref _generateAsync, value);
        }

        public bool IsAutoGenerated
        {
            get => _isAutoGenerated;
            set => SetField(ref _isAutoGenerated, value);
        }

        public float GeneratedTargetIndexRatio
        {
            get => _generatedTargetIndexRatio;
            set => SetField(ref _generatedTargetIndexRatio, value);
        }

        public float GeneratedNormalizedError
        {
            get => _generatedNormalizedError;
            set => SetField(ref _generatedNormalizedError, value);
        }

        public float GeneratedObjectSpaceError
        {
            get => _generatedObjectSpaceError;
            set => SetField(ref _generatedObjectSpaceError, value);
        }

        public XRMeshRenderer NewRenderer()
            => new(mesh, material) { GenerateAsync = GenerateAsync };
    }
}
