namespace XREngine.Rendering.API.Rendering.OpenXR;

public struct OpenXrSmokeFrameLedgerEntry
{
    public int RetainedIndex { get; set; }
    public long CompletedFrameCount { get; set; }
    public long SubmittedFrameCount { get; set; }
    public long NoLayerFrameCount { get; set; }
    public bool ProjectionLayerSubmitted { get; set; }
    public int EndFrameResult { get; set; }
    public uint EndFrameLayerCount { get; set; }
    public ulong RenderFrameId { get; set; }
    public double ElapsedMilliseconds { get; set; }
    public long LeftAcquireCount { get; set; }
    public long RightAcquireCount { get; set; }
    public long LeftAcquireDelta { get; set; }
    public long RightAcquireDelta { get; set; }
    public long LeftWaitCount { get; set; }
    public long RightWaitCount { get; set; }
    public long LeftWaitDelta { get; set; }
    public long RightWaitDelta { get; set; }
    public long LeftPublishCount { get; set; }
    public long RightPublishCount { get; set; }
    public long LeftPublishDelta { get; set; }
    public long RightPublishDelta { get; set; }
    public long LeftReleaseCount { get; set; }
    public long RightReleaseCount { get; set; }
    public long LeftReleaseDelta { get; set; }
    public long RightReleaseDelta { get; set; }
    public int LeftExternalImageSlot { get; set; }
    public int RightExternalImageSlot { get; set; }
    public long StrictSequentialFallbackAttemptCount { get; set; }
    public long StrictSequentialFallbackAttemptDelta { get; set; }
    public double FrameTotalMilliseconds { get; set; }
    public double FrameGpuMilliseconds { get; set; }
    public double FrameWaitFenceMilliseconds { get; set; }
    public double FrameRecordMilliseconds { get; set; }
    public double FrameSubmitMilliseconds { get; set; }
    public double FramePresentMilliseconds { get; set; }
    public int ValidationErrorCount { get; set; }
    public bool ValidationLayersEnabled { get; set; }
    public bool SynchronizationValidationEnabled { get; set; }
    public bool LifetimeValidationEnabled { get; set; }
    public bool LifetimeValidationPassed { get; set; }
    public int DeviceLocalAllocationCount { get; set; }
    public long DeviceLocalAllocatedBytes { get; set; }
    public int UploadAllocationCount { get; set; }
    public long UploadAllocatedBytes { get; set; }
    public int DescriptorPoolCreateCount { get; set; }
    public int DescriptorPoolDestroyCount { get; set; }
    public int DescriptorPoolResetCount { get; set; }
    public int ResourcePlanReplacementCount { get; set; }
    public int CommandBufferCleanReuseCount { get; set; }
    public int CommandBufferRecordCount { get; set; }
    public int PrimaryCommandBufferReuseCount { get; set; }
    public int PrimaryCommandBufferRecordCount { get; set; }
    public int GlobalFallbackInvalidationCount { get; set; }
    public int RetiredResourceCount { get; set; }
    public int LifetimeLiveResourceCount { get; set; }
    public int TrackedDescriptorSetCount { get; set; }
    public int LifetimePendingRetirementCount { get; set; }
    public long LifetimeOldestPendingRetirementAgeMilliseconds { get; set; }
    public int MeshFrameDataArenaChunkCount { get; set; }
    public long MeshFrameDataMappedBytes { get; set; }
    public long MeshFrameDataReservedBytes { get; set; }
    public int MeshFrameDataReservationCount { get; set; }
    public ulong MeshFrameDataGeneration { get; set; }
    public int MeshFrameDataRecordingLeases { get; set; }
    public int MeshFrameDataCachedLeases { get; set; }
    public int MeshFrameDataSubmittedLeases { get; set; }
    public int MeshFrameDataActiveGenerationCount { get; set; }
    public int MeshFrameDataLeaseRetainedGenerationCount { get; set; }
    public ulong MeshFrameDataManifestGeneration { get; set; }
    public long MeshFrameDataManifestPublicationCount { get; set; }
    public long MeshFrameDataManifestLateRegistrationCount { get; set; }
    public int MeshFrameDataManifestRendererCount { get; set; }
    public int MeshFrameDataManifestFamilyCount { get; set; }
    public bool MeshFrameDataManifestIsSealed { get; set; }
    public int MeshDescriptorAllocationVariants { get; set; }
    public int MeshDescriptorPools { get; set; }
    public int MeshDescriptorAllocatedSets { get; set; }
    public int MeshDescriptorReservedSets { get; set; }
    public int MeshFrameDataArenaChunkHighWater { get; set; }
    public long MeshFrameDataMappedBytesHighWater { get; set; }
    public long MeshFrameDataReservedBytesHighWater { get; set; }
    public int MeshFrameDataReservationHighWater { get; set; }
    public int MeshFrameDataLeaseHighWater { get; set; }
    public int MeshDescriptorAllocationVariantHighWater { get; set; }
    public int MeshDescriptorPoolHighWater { get; set; }
    public int MeshDescriptorSetHighWater { get; set; }
    public int QueueSubmitCount { get; set; }
    public bool SubmitCompleted { get; set; }
    public int SubmissionRejectionCount { get; set; }
    public int GlobalInFlightWaitCount { get; set; }
    public int ForceFlushCount { get; set; }
    public int UnapprovedPolicyEventCount { get; set; }
    public int PlannerPruneCount { get; set; }
    public int OutputMissedDeadlineCount { get; set; }
    public ulong OutputManifestFrameId { get; set; }
    public ulong OutputWorkloadIdentityHash { get; set; }
    public int OutputRequestCount { get; set; }
    public int OutputEventCount { get; set; }
    public int CollectEventCount { get; set; }
    public int SwapEventCount { get; set; }
    public int RenderEventCount { get; set; }
    public int SubmitEventCount { get; set; }
    public int OverlayEventCount { get; set; }
    public int PresentEventCount { get; set; }
    public int PlannerStateCount { get; set; }
    public int CommandVariantCount { get; set; }
    public ulong ResourcePlanGeneration { get; set; }
    public ulong CommandGeneration { get; set; }
    public string? MirrorMode { get; set; }
    public bool VrActive { get; set; }
    public int SceneSwapchainWriterCount { get; set; }
    public int SwapchainWriteCount { get; set; }
    public int MissingSceneSwapchainWriteCount { get; set; }
    public bool DesktopFinalWriteObserved { get; set; }
    public bool DesktopPresentObserved { get; set; }
    public int DesktopPresentAttemptCount { get; set; }
    public bool DesktopPresentAccepted { get; set; }
    public string? DesktopPresentResult { get; set; }
    public int CpuOcclusionTested { get; set; }
    public int CpuOcclusionCulled { get; set; }
    public int CpuOcclusionPassesActive { get; set; }
    public int CpuOcclusionQueriesSubmitted { get; set; }
    public int CpuOcclusionQueriesResolved { get; set; }
    public int CpuOcclusionPendingQueries { get; set; }
    public int CpuOcclusionForcedVisible { get; set; }
    public int CpuOcclusionMaxQueryAge { get; set; }
    public int CpuOcclusionViewScope { get; set; }
}
