namespace XREngine.Components.Animation
{
    public enum EHumanoidValue
    {
        // NOTE: Underlying int values are stable and relied upon by decoupled importers.
        LeftEyeDownUp = 0,
        LeftEyeInOut = 1,
        RightEyeDownUp = 2,
        RightEyeInOut = 3,

        SpineFrontBack = 4,
        SpineLeftRight = 5,
        SpineTwistLeftRight = 6,
        ChestFrontBack = 7,
        ChestLeftRight = 8,
        ChestTwistLeftRight = 9,
        UpperChestFrontBack = 10,
        UpperChestLeftRight = 11,
        UpperChestTwistLeftRight = 12,
        NeckNodDownUp = 13,
        NeckTiltLeftRight = 14,
        NeckTurnLeftRight = 15,
        HeadNodDownUp = 16,
        HeadTiltLeftRight = 17,
        HeadTurnLeftRight = 18,
        JawClose = 19,
        JawLeftRight = 20,

        LeftShoulderDownUp = 21,
        LeftShoulderFrontBack = 22,
        LeftArmDownUp = 23,
        LeftArmFrontBack = 24,
        LeftArmTwistInOut = 25,
        LeftForearmStretch = 26,
        LeftForearmTwistInOut = 27,
        LeftHandDownUp = 28,
        LeftHandInOut = 29,
        LeftUpperLegFrontBack = 30,
        LeftUpperLegInOut = 31,
        LeftUpperLegTwistInOut = 32,
        LeftLowerLegStretch = 33,
        LeftLowerLegTwistInOut = 34,
        LeftFootUpDown = 35,
        LeftFootTwistInOut = 36,
        LeftToesUpDown = 37,

        RightShoulderDownUp = 38,
        RightShoulderFrontBack = 39,
        RightArmDownUp = 40,
        RightArmFrontBack = 41,
        RightArmTwistInOut = 42,
        RightForearmStretch = 43,
        RightForearmTwistInOut = 44,
        RightHandDownUp = 45,
        RightHandInOut = 46,
        RightUpperLegFrontBack = 47,
        RightUpperLegInOut = 48,
        RightUpperLegTwistInOut = 49,
        RightLowerLegStretch = 50,
        RightLowerLegTwistInOut = 51,
        RightFootUpDown = 52,
        RightFootTwistInOut = 53,
        RightToesUpDown = 54,

        LeftHandIndexSpread = 55,
        LeftHandIndex1Stretched = 56,
        LeftHandIndex2Stretched = 57,
        LeftHandIndex3Stretched = 58,
        LeftHandMiddleSpread = 59,
        LeftHandMiddle1Stretched = 60,
        LeftHandMiddle2Stretched = 61,
        LeftHandMiddle3Stretched = 62,
        LeftHandRingSpread = 63,
        LeftHandRing1Stretched = 64,
        LeftHandRing2Stretched = 65,
        LeftHandRing3Stretched = 66,
        LeftHandLittleSpread = 67,
        LeftHandLittle1Stretched = 68,
        LeftHandLittle2Stretched = 69,
        LeftHandLittle3Stretched = 70,
        LeftHandThumbSpread = 71,
        LeftHandThumb1Stretched = 72,
        LeftHandThumb2Stretched = 73,
        LeftHandThumb3Stretched = 74,

        RightHandIndexSpread = 75,
        RightHandIndex1Stretched = 76,
        RightHandIndex2Stretched = 77,
        RightHandIndex3Stretched = 78,
        RightHandMiddleSpread = 79,
        RightHandMiddle1Stretched = 80,
        RightHandMiddle2Stretched = 81,
        RightHandMiddle3Stretched = 82,
        RightHandRingSpread = 83,
        RightHandRing1Stretched = 84,
        RightHandRing2Stretched = 85,
        RightHandRing3Stretched = 86,
        RightHandLittleSpread = 87,
        RightHandLittle1Stretched = 88,
        RightHandLittle2Stretched = 89,
        RightHandLittle3Stretched = 90,
        RightHandThumbSpread = 91,
        RightHandThumb1Stretched = 92,
        RightHandThumb2Stretched = 93,
        RightHandThumb3Stretched = 94,
    }
}
