namespace XREngine.Rendering.Vulkan.DeviceBootstrap;

[Flags]
internal enum EVulkanDeviceCapability : ulong
{
    None = 0,
    Anisotropy = 1UL << 0,
    MultipleGraphicsQueues = 1UL << 1,
    TimelineSemaphores = 1UL << 2,
    Synchronization2 = 1UL << 3,
    DescriptorIndexing = 1UL << 4,
    DescriptorHeap = 1UL << 5,
    BufferDeviceAddress = 1UL << 6,
    DynamicRendering = 1UL << 7,
    DynamicRenderingLocalRead = 1UL << 8,
    Maintenance4 = 1UL << 9,
    Maintenance5 = 1UL << 10,
    MemoryBudget = 1UL << 11,
    MemoryPriority = 1UL << 12,
    ShaderObject = 1UL << 13,
    AccelerationStructure = 1UL << 14,
    RayTracingPipeline = 1UL << 15,
    RayQuery = 1UL << 16,
    DeviceGeneratedCommands = 1UL << 17,
    DeviceFault = 1UL << 18,
    DeviceFaultVendorBinary = 1UL << 19,
    DeviceAddressBindingReport = 1UL << 20,
    NvDiagnosticCheckpoints = 1UL << 21,
    NvDiagnosticsConfig = 1UL << 22,
    NvMemoryDecompression = 1UL << 23,
    NvCopyMemoryIndirect = 1UL << 24,
    DepthClipControl = 1UL << 25,
    MeshShader = 1UL << 26,
    GraphicsPipelineLibrary = 1UL << 27,
    TransformFeedback = 1UL << 28,
    HostQueryReset = 1UL << 29,
    FragmentShadingRate = 1UL << 30,
    FragmentDensityMap = 1UL << 31,
    IndexTypeUint8 = 1UL << 32,
    DrawIndirectCount = 1UL << 33,
    MultiDrawIndirect = 1UL << 34,
    DrawIndirectFirstInstance = 1UL << 35,
    GeometryShader = 1UL << 36,
    FragmentStoresAndAtomics = 1UL << 37,
    VertexPipelineStoresAndAtomics = 1UL << 38,
    Vulkan14 = 1UL << 39,
}
