namespace XREngine.Audio.Steam;

public enum IPLBakedDataVariation
{
    IPL_BAKEDDATAVARIATION_REVERB,
    IPL_BAKEDDATAVARIATION_STATICSOURCE,
    IPL_BAKEDDATAVARIATION_STATICLISTENER,
    IPL_BAKEDDATAVARIATION_DYNAMIC
}