namespace XREngine.Audio.Steam;

public enum IPLReflectionEffectType
{
    IPL_REFLECTIONEFFECTTYPE_CONVOLUTION,
    IPL_REFLECTIONEFFECTTYPE_PARAMETRIC,
    IPL_REFLECTIONEFFECTTYPE_HYBRID,
    IPL_REFLECTIONEFFECTTYPE_TAN
}