using XREngine.Rendering;
using XREngine.Rendering.Models;

namespace XREngine;

internal static class ModelImportMeshIslandSplitter
{
    public static IReadOnlyList<SubMesh> SplitSubMesh(SubMesh subMesh, bool separateMeshIslands)
    {
        if (!separateMeshIslands)
            return [subMesh];

        if (subMesh.LODs.Count != 1)
            return [subMesh];

        SubMeshLOD sourceLod = subMesh.LODs.Min!;
        XRMesh? sourceMesh = sourceLod.Mesh;
        if (sourceMesh is null)
            return [subMesh];

        IReadOnlyList<XRMesh> islandMeshes = sourceMesh.SeparateTriangleIslands();
        if (islandMeshes.Count == 0 || (islandMeshes.Count == 1 && ReferenceEquals(islandMeshes[0], sourceMesh)))
            return [subMesh];

        List<SubMesh> islandSubMeshes = new(islandMeshes.Count);
        for (int islandIndex = 0; islandIndex < islandMeshes.Count; islandIndex++)
        {
            SubMesh islandSubMesh = new(CopyLod(sourceLod, islandMeshes[islandIndex]))
            {
                Name = FormatIslandName(subMesh.Name, islandIndex),
                RootTransform = subMesh.RootTransform,
                RootBone = subMesh.RootBone,
                CullingBounds = subMesh.CullingBounds,
                MeshOptimizer = subMesh.MeshOptimizer,
            };

            islandSubMeshes.Add(islandSubMesh);
        }

        return islandSubMeshes;
    }

    public static void AddMeshes(IReadOnlyList<SubMesh> subMeshes, Action<XRMesh> addMesh)
    {
        for (int subMeshIndex = 0; subMeshIndex < subMeshes.Count; subMeshIndex++)
        {
            foreach (SubMeshLOD lod in subMeshes[subMeshIndex].LODs)
            {
                if (lod.Mesh is not null)
                    addMesh(lod.Mesh);
            }
        }
    }

    private static SubMeshLOD CopyLod(SubMeshLOD source, XRMesh mesh)
        => new(source.Material, mesh, source.MaxVisibleDistance, source.MinProjectedScreenRadiusPixels)
        {
            GenerateAsync = source.GenerateAsync,
            IsAutoGenerated = source.IsAutoGenerated,
            GeneratedTargetIndexRatio = source.GeneratedTargetIndexRatio,
            GeneratedNormalizedError = source.GeneratedNormalizedError,
            GeneratedObjectSpaceError = source.GeneratedObjectSpaceError,
        };

    private static string FormatIslandName(string? sourceName, int islandIndex)
    {
        string baseName = string.IsNullOrWhiteSpace(sourceName) ? "Mesh" : sourceName!;
        return $"{baseName} Island {islandIndex}";
    }
}
