using XREngine.Rendering;
using XREngine.Rendering.Models;

namespace XREngine;

internal static class ModelImportMeshIslandSplitter
{
    public static IReadOnlyList<SubMesh> SplitSubMesh(
        SubMesh subMesh,
        bool separateMeshIslands,
        int spatialPartitionMaxTriangles = 0)
    {
        if (!separateMeshIslands && spatialPartitionMaxTriangles <= 0)
            return [subMesh];

        if (subMesh.LODs.Count != 1)
            return [subMesh];

        SubMeshLOD sourceLod = subMesh.LODs.Min!;
        XRMesh? sourceMesh = sourceLod.Mesh;
        if (sourceMesh is null)
            return [subMesh];

        IReadOnlyList<XRMesh> baseMeshes = separateMeshIslands
            ? sourceMesh.SeparateTriangleIslands()
            : [sourceMesh];
        List<XRMesh> finalMeshes = [];
        for (int meshIndex = 0; meshIndex < baseMeshes.Count; meshIndex++)
        {
            IReadOnlyList<XRMesh> partitions = baseMeshes[meshIndex]
                .PartitionTrianglesSpatially(spatialPartitionMaxTriangles);
            for (int partitionIndex = 0; partitionIndex < partitions.Count; partitionIndex++)
                finalMeshes.Add(partitions[partitionIndex]);
        }

        if (finalMeshes.Count == 0 || (finalMeshes.Count == 1 && ReferenceEquals(finalMeshes[0], sourceMesh)))
            return [subMesh];

        List<SubMesh> islandSubMeshes = new(finalMeshes.Count);
        for (int islandIndex = 0; islandIndex < finalMeshes.Count; islandIndex++)
        {
            // Each island gets a freshly-defaulted MeshOptimizer (avoid sharing a single
            // settings instance across islands so later edits don't bleed between siblings)
            // and a null CullingBounds (the auto-computed SubMesh.Bounds derived from the
            // island's own geometry is a tighter fit than the source submesh's override).
            SubMesh islandSubMesh = new(CopyLod(sourceLod, finalMeshes[islandIndex]))
            {
                Name = FormatIslandName(subMesh.Name, islandIndex),
                RootTransform = subMesh.RootTransform,
                RootBone = subMesh.RootBone,
            };

            islandSubMeshes.Add(islandSubMesh);
        }

        return islandSubMeshes;
    }

    public static void AddMeshes(IReadOnlyList<SubMesh> subMeshes, Action<XRMesh> addMesh)
    {
        for (int subMeshIndex = 0; subMeshIndex < subMeshes.Count; subMeshIndex++)
        {
            foreach (SubMeshLOD lod in subMeshes[subMeshIndex].LODs)
            {
                if (lod.Mesh is not null)
                    addMesh(lod.Mesh);
            }
        }
    }

    private static SubMeshLOD CopyLod(SubMeshLOD source, XRMesh mesh)
        => new(source.Material, mesh, source.MaxVisibleDistance, source.MinProjectedScreenRadiusPixels)
        {
            GenerateAsync = source.GenerateAsync,
            IsAutoGenerated = source.IsAutoGenerated,
            GeneratedTargetIndexRatio = source.GeneratedTargetIndexRatio,
            GeneratedNormalizedError = source.GeneratedNormalizedError,
            GeneratedObjectSpaceError = source.GeneratedObjectSpaceError,
        };

    private static string FormatIslandName(string? sourceName, int islandIndex)
    {
        string baseName = string.IsNullOrWhiteSpace(sourceName) ? "Mesh" : sourceName!;
        return $"{baseName} Island {islandIndex}";
    }
}
