<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../XREngine.Runtime.Core/XREngine.Runtime.Core.csproj" />
    <ProjectReference Include="../../XREngine.Runtime.Rendering/XREngine.Runtime.Rendering.csproj" />
    <ProjectReference Include="../../XREngine.Runtime.InputIntegration/XREngine.Runtime.InputIntegration.csproj" />
  </ItemGroup>
</Project>
