using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace XREngine.SourceGenerators;

/// <summary>Emits factory registrations from resolved runtime types and constructors.</summary>
[Generator]
public sealed class RuntimeFactoryGenerator : IIncrementalGenerator
{
    private const string PortableAssemblies = ";XREngine.Extensions;XREngine.Data;XREngine.Animation;XREngine.Audio;XREngine.Input;XREngine.Runtime.Core;XREngine.Runtime.Rendering;XREngine.Runtime.AnimationIntegration;XREngine.Runtime.AudioIntegration;XREngine.Runtime.InputIntegration;XREngine.Runtime.Host;";
    private const string DesktopAssemblies = ";XREngine.Runtime.Bootstrap;XREngine.Runtime.ModelAssetPipeline;XREngine.Runtime.ModelingIntegration;XREngine.Runtime.UI.Skia;XREngine.Runtime.UI.Rive;XREngine.Audio.Audio2Face;XREngine.Audio.SteamAudio;XREngine.Runtime.Physics.PhysX;XREngine.Runtime.Net.Osc;XREngine.Runtime.Net.Sockets;";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mode = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.XREngineRuntimeContractMode", out var value) ? value : "");
        context.RegisterSourceOutput(context.CompilationProvider.Combine(mode),
            static (output, pair) => Generate(output, pair.Left, pair.Right));
    }

    private static void Generate(SourceProductionContext context, Compilation compilation, string mode)
    {
        if (mode != "Portable" && mode != "Desktop" && mode != "CommandsOnly")
            return;

        var assemblies = new List<IAssemblySymbol> { compilation.Assembly };
        foreach (var reference in compilation.References)
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                assemblies.Add(assembly);

        var types = new List<INamedTypeSymbol>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var assembly in assemblies)
        {
            var name = assembly.Identity.Name;
            if (mode == "CommandsOnly" ? name != "XREngine.Runtime.Rendering" :
                mode == "Portable" ? !PortableAssemblies.Contains(";" + name + ";") : !DesktopAssemblies.Contains(";" + name + ";"))
                continue;
            Collect(assembly.GlobalNamespace, types, seen, compilation);
        }

        types.Sort(static (left, right) => StringComparer.Ordinal.Compare(Name(left), Name(right)));
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n#pragma warning disable CA2255, CS0618\nusing System.Runtime.CompilerServices;\nnamespace XREngine.Generated;\ninternal static class GeneratedRuntimeFactoryRegistrations\n{\n    [ModuleInitializer]\n    internal static void Register()\n    {\n");
        var localDefault = false;
        var remoteDefault = false;
        foreach (var type in types)
        {
            var fullName = Name(type);
            var create = "new " + fullName + "()";
            var parameterless = HasConstructor(type, compilation);
            if (mode != "CommandsOnly" && Inherits(type, "XREngine.Scene.Transforms.TransformBase") && parameterless)
                Line(source, "global::XREngine.Scene.Transforms.TransformFactoryRegistry.Register(typeof(" + fullName + "), static () => " + create + ");");
            if (mode != "CommandsOnly" && Inherits(type, "XREngine.Components.XRComponent") && parameterless)
                Line(source, "global::XREngine.Components.RuntimeComponentFactoryRegistry.Register(typeof(" + fullName + "), static () => " + create + ");");
            if (Inherits(type, "XREngine.Rendering.Pipelines.Commands.ViewportRenderCommand") && parameterless &&
                (mode == "CommandsOnly" || type.ContainingAssembly.Identity.Name != "XREngine.Runtime.Rendering"))
            {
                Line(source, "global::XREngine.Rendering.Pipelines.Commands.ViewportRenderCommandContainer.RegisterBuiltInCommandFactory(typeof(" + fullName + "), static () => " + create + ");");
                if (type.GetAttributes().Any(static attribute => attribute.AttributeClass?.Name == "RenderPipelineScriptCommandAttribute"))
                    Line(source, "global::XREngine.Rendering.RenderPipelineScript.RegisterCommandScriptName(typeof(" + fullName + "), null, true);");
            }
            if (mode == "CommandsOnly")
                continue;
            if (Inherits(type, "XREngine.Rendering.XRCameraParameters"))
            {
                var factory = HasConstructor(type, compilation, SpecialType.System_Single, SpecialType.System_Single)
                    ? "static (nearZ, farZ) => new " + fullName + "(nearZ, farZ)"
                    : HasConstructor(type, compilation, SpecialType.System_Boolean, SpecialType.System_Single, SpecialType.System_Single)
                        ? "static (nearZ, farZ) => new " + fullName + "(true, nearZ, farZ)"
                        : parameterless ? "static (_, _) => " + create : null;
                if (factory != null)
                    Line(source, "global::XREngine.Rendering.XRCameraParameters.RegisterFactory(typeof(" + fullName + "), " + factory + ");");
            }
            if (Inherits(type, "XREngine.Rendering.PostProcessSettings") && parameterless)
                Line(source, "global::XREngine.Rendering.PostProcessing.PostProcessBackingFactoryRegistry.Register(typeof(" + fullName + "), static () => " + create + ");");
            if (Inherits(type, "XREngine.Rendering.RenderPipeline") && parameterless)
                Line(source, "global::XREngine.Rendering.RenderPipeline.RegisterOpenXrPipelineFactory(typeof(" + fullName + "), static source => new " + fullName + " { IsShadowPass = source.IsShadowPass });");
            if (type.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (InheritsConstructed(type, "PlayerController", "LocalInputInterface") && HasConstructorNamed(type, compilation, "ELocalPlayerIndex"))
            {
                Line(source, "global::XREngine.Input.RuntimePlayerControllerServices.RegisterLocalControllerFactory(typeof(" + fullName + "), static index => new " + fullName + "(index), makeDefault: " + (!localDefault ? "true" : "false") + ");");
                localDefault = true;
            }
            if (InheritsConstructed(type, "PlayerController", "ServerInputInterface") && HasConstructor(type, compilation, SpecialType.System_Int32))
            {
                Line(source, "global::XREngine.Input.RuntimePlayerControllerServices.RegisterRemoteControllerFactory(typeof(" + fullName + "), static serverPlayerIndex => new " + fullName + "(serverPlayerIndex), makeDefault: " + (!remoteDefault ? "true" : "false") + ");");
                remoteDefault = true;
            }
        }
        source.Append("    }\n}\n");
        context.AddSource("GeneratedRuntimeFactoryRegistrations.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void Collect(INamespaceSymbol space, List<INamedTypeSymbol> types, HashSet<string> seen, Compilation compilation)
    {
        foreach (var member in space.GetMembers())
        {
            if (member is INamespaceSymbol child)
                Collect(child, types, seen, compilation);
            else if (member is INamedTypeSymbol type)
                CollectType(type, types, seen, compilation);
        }
    }

    private static void CollectType(INamedTypeSymbol type, List<INamedTypeSymbol> types, HashSet<string> seen, Compilation compilation)
    {
        if (type.TypeKind == TypeKind.Class && !type.IsAbstract && !type.IsStatic && !type.IsGenericType &&
            type.ContainingType?.IsGenericType != true && compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) && seen.Add(Name(type)))
            types.Add(type);
        foreach (var nested in type.GetTypeMembers())
            CollectType(nested, types, seen, compilation);
    }

    private static bool HasConstructor(INamedTypeSymbol type, Compilation compilation, params SpecialType[] parameters) =>
        type.InstanceConstructors.Any(ctor => ConstructorSatisfiesRequiredMembers(type, ctor) && ctor.Parameters.Length == parameters.Length &&
            compilation.IsSymbolAccessibleWithin(ctor, compilation.Assembly) &&
            ctor.Parameters.Select(static p => p.Type.SpecialType).SequenceEqual(parameters));

    private static bool HasConstructorNamed(INamedTypeSymbol type, Compilation compilation, string parameterName) =>
        type.InstanceConstructors.Any(ctor => ConstructorSatisfiesRequiredMembers(type, ctor) && ctor.Parameters.Length == 1 && ctor.Parameters[0].Type.Name == parameterName &&
            compilation.IsSymbolAccessibleWithin(ctor, compilation.Assembly));

    private static bool ConstructorSatisfiesRequiredMembers(INamedTypeSymbol type, IMethodSymbol ctor)
    {
        for (var current = type; current != null; current = current.BaseType)
        {
            if (!current.GetMembers().Any(static member => member is IPropertySymbol { IsRequired: true } or IFieldSymbol { IsRequired: true }))
                continue;
            return ctor.GetAttributes().Any(static attribute => attribute.AttributeClass?.ToDisplayString() == "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute");
        }
        return true;
    }

    private static bool Inherits(INamedTypeSymbol type, string fullName)
    {
        for (var current = type.BaseType; current != null; current = current.BaseType)
            if (current.ToDisplayString() == fullName)
                return true;
        return false;
    }

    private static bool InheritsConstructed(INamedTypeSymbol type, string baseName, string argumentName)
    {
        for (var current = type.BaseType; current != null; current = current.BaseType)
            if (current.Name == baseName && current.TypeArguments.Length == 1 && current.TypeArguments[0].Name == argumentName)
                return true;
        return false;
    }

    private static string Name(INamedTypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static void Line(StringBuilder builder, string line) => builder.Append("        ").Append(line).Append('\n');
}
