using System.Collections.Concurrent;
using System.ComponentModel;
using System.Numerics;
using System.Threading.Tasks;
using MagicPhysX;
using XREngine.Components.Scene.Mesh;
using XREngine.Core.Attributes;
using XREngine.Data.Tools;
using XREngine.Rendering.Physics.Physx;
using XREngine.Scene;
using XREngine.Scene.Physics.Jolt;
using XREngine.Scene.Transforms;
using XREngine;
using XREngine.Networking;

namespace XREngine.Components.Physics
{
    [RequiresTransform(typeof(RigidBodyTransform))]
    [Category("Physics")]
    [DisplayName("Static Rigid Body")]
    [Description("Fixed collider that participates in the physics simulation without moving.")]
    [XRComponentEditor("XREngine.Editor.ComponentEditors.StaticRigidBodyComponentEditor")]
    public class StaticRigidBodyComponent : PhysicsActorComponent, IPhysicsReplicationTarget
    {
        private static readonly ConcurrentDictionary<string, byte> s_loggedNoValidAutoGeneratedHullWarnings = new();

        public RigidBodyTransform RigidBodyTransform => SceneNode.GetTransformAs<RigidBodyTransform>(true)!;

        protected override ModelComponent? ResolveModelComponentForColliders()
            => TargetModelComponent ?? base.ResolveModelComponentForColliders();

        private int _rigidBodyOwnershipSyncDepth;

        private IAbstractStaticRigidBody? _rigidBody;
        private AbstractPhysicsScene? _registeredPhysicsScene;
        private bool _autoCreateRigidBody = true;
        private bool _gravityEnabled = true;
        private bool _simulationEnabled = true;
        private bool _debugVisualization;
        private bool _sendSleepNotifies;
        private ushort _collisionGroup;
        private PhysicsGroupsMask _groupsMask = PhysicsGroupsMask.Empty;
        private byte _dominanceGroup;
        private byte _physxOwnerClient;
        private PhysicsReplicationAuthority _replicationAuthority = PhysicsReplicationAuthority.LocalSimulation;
        private NetworkEntityId _networkEntityId;
        private string? _ownerClientId;
        private int _ownerServerPlayerIndex = -1;
        private string? _actorName;
        private AbstractPhysicsMaterial? _material;
        private PhysicsMaterialDefinition? _materialDefinition;
        private IPhysicsGeometry? _geometry;
        private List<PhysicsColliderShape> _colliderShapes = [];
        private Vector3 _shapeOffsetTranslation = Vector3.Zero;
        private Quaternion _shapeOffsetRotation = Quaternion.Identity;
        private bool _autoGenerateConvexCollidersFromSiblingModel;
        private bool _autoConvexColliderGenerationQueued;
        private bool _autoConvexColliderGenerationStarted;
        private bool _autoConvexCollidersAttached;
        private WeakReference<ModelComponent>? _targetModelComponentRef;
        private IReadOnlyList<ModelComponent>? _targetModelComponents;

        [Browsable(false)]
        [RuntimeOnly]
        public IAbstractStaticRigidBody? RigidBody
        {
            get => _rigidBody;
            set => SetField(ref _rigidBody, value);
        }

        internal void SetRigidBodyFromRigidBodyOwner(IAbstractStaticRigidBody? body)
        {
            try
            {
                _rigidBodyOwnershipSyncDepth++;
                RigidBody = body;
            }
            finally
            {
                _rigidBodyOwnershipSyncDepth--;
            }
        }

        [Category("Initialization")]
        [DisplayName("Auto Create Rigid Body")]
        [Description("Whether to auto-create the rigid body on world registration.")]
        public bool AutoCreateRigidBody
        {
            get => _autoCreateRigidBody;
            set => SetField(ref _autoCreateRigidBody, value);
        }

        [Category("Shape")]
        [DisplayName("Material")]
        [Description("The physics material defining friction and restitution.")]
        public AbstractPhysicsMaterial? Material
        {
            get => _material;
            set => SetField(ref _material, value);
        }

        [Category("Shape")]
        [DisplayName("Material Definition")]
        [Description("Backend-neutral authored material settings. Native backend materials are generated from this definition when needed.")]
        public PhysicsMaterialDefinition? MaterialDefinition
        {
            get => _materialDefinition;
            set => SetField(ref _materialDefinition, value);
        }

        [Category("Shape")]
        [DisplayName("Compound Colliders")]
        [Description("Backend-neutral collider shape list. The first enabled shape is the primary shape; PhysX attaches additional enabled shapes as a compound actor.")]
        public List<PhysicsColliderShape> ColliderShapes
        {
            get => _colliderShapes;
            set => SetField(ref _colliderShapes, value ?? []);
        }

        [Category("Shape")]
        [DisplayName("Geometry")]
        [Description("The legacy single collision geometry shape. Used when Compound Colliders is empty.")]
        public IPhysicsGeometry? Geometry
        {
            get => _geometry;
            set => SetField(ref _geometry, value);
        }

        [Category("Shape")]
        [DisplayName("Shape Offset Translation")]
        [Description("Local translation offset for the collision shape.")]
        public Vector3 ShapeOffsetTranslation
        {
            get => _shapeOffsetTranslation;
            set => SetField(ref _shapeOffsetTranslation, value);
        }

        [Category("Shape")]
        [DisplayName("Shape Offset Rotation")]
        [Description("Local rotation offset for the collision shape.")]
        public Quaternion ShapeOffsetRotation
        {
            get => _shapeOffsetRotation;
            set => SetField(ref _shapeOffsetRotation, value);
        }

        [Category("Shape")]
        [DisplayName("Auto Generate CoACD Colliders")]
        [Description("Waits for a sibling model to finish importing, runs CoACD, and attaches one PhysX convex shape per generated hull.")]
        public bool AutoGenerateConvexCollidersFromSiblingModel
        {
            get => _autoGenerateConvexCollidersFromSiblingModel;
            set => SetField(ref _autoGenerateConvexCollidersFromSiblingModel, value);
        }

        /// <summary>
        /// When set, CoACD collider generation will use this specific ModelComponent
        /// instead of the first sibling ModelComponent on the node.
        /// This is necessary when a node has multiple ModelComponents (e.g. split submesh import).
        /// </summary>
        [Browsable(false)]
        public ModelComponent? TargetModelComponent
        {
            get => _targetModelComponentRef is not null && _targetModelComponentRef.TryGetTarget(out var target) ? target : null;
            set => SetField(ref _targetModelComponentRef, value is not null ? new WeakReference<ModelComponent>(value) : null);
        }

        /// <summary>
        /// When set, CoACD collider generation combines all listed model components into this
        /// static rigid body's local space and attaches every generated shape to this component.
        /// </summary>
        [Browsable(false)]
        public IReadOnlyList<ModelComponent>? TargetModelComponents
        {
            get => _targetModelComponents;
            set => SetField(ref _targetModelComponents, value);
        }

        private protected override bool HasCollisionTargetForColliders()
            => TargetModelComponents is { Count: > 0 } || base.HasCollisionTargetForColliders();

        private protected override ConvexHullInputCollection? CollectCollisionInputCollectionForColliders()
            => TargetModelComponents is { Count: > 0 } targetModelComponents
                ? ConvexHullUtility.CollectCollisionInputCollection(targetModelComponents, Transform)
                : base.CollectCollisionInputCollectionForColliders();

        private protected override string DescribeCollisionTargetForColliders()
        {
            if (TargetModelComponents is { Count: > 0 } targetModelComponents)
            {
                string nodeLabel = SceneNode?.Name ?? "<unnamed>";
                return $"{nodeLabel}/{targetModelComponents.Count} model components#{GetHashCode():X8}";
            }

            return base.DescribeCollisionTargetForColliders();
        }

        [Category("Forces")]
        [DisplayName("Gravity Enabled")]
        [Description("Whether gravity affects this body (typically false for static).")]
        public bool GravityEnabled
        {
            get => RigidBody is PhysxActor actor ? actor.GravityEnabled : _gravityEnabled;
            set
            {
                if (!SetField(ref _gravityEnabled, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.GravityEnabled = value;
            }
        }

        [Category("Simulation")]
        [DisplayName("Simulation Enabled")]
        [Description("Whether the physics simulation is enabled.")]
        public bool SimulationEnabled
        {
            get => RigidBody is PhysxActor actor ? actor.SimulationEnabled : _simulationEnabled;
            set
            {
                if (!SetField(ref _simulationEnabled, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.SimulationEnabled = value;
            }
        }

        [Category("Debug")]
        [DisplayName("Debug Visualization")]
        [Description("Show physics debug visualization.")]
        public bool DebugVisualization
        {
            get => RigidBody is PhysxActor actor ? actor.DebugVisualize : _debugVisualization;
            set
            {
                if (!SetField(ref _debugVisualization, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.DebugVisualize = value;
            }
        }

        [Category("Sleep")]
        [DisplayName("Send Sleep Notifies")]
        [Description("Whether to notify when sleep state changes.")]
        public bool SendSleepNotifies
        {
            get => RigidBody is PhysxActor actor ? actor.SendSleepNotifies : _sendSleepNotifies;
            set
            {
                if (!SetField(ref _sendSleepNotifies, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.SendSleepNotifies = value;
            }
        }

        [Category("Collision")]
        [DisplayName("Collision Group")]
        [Description("The collision group this body belongs to.")]
        public ushort CollisionGroup
        {
            get => RigidBody is PhysxActor actor ? actor.CollisionGroup : _collisionGroup;
            set
            {
                if (!SetField(ref _collisionGroup, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.CollisionGroup = value;
            }
        }

        [Category("Collision")]
        [DisplayName("Groups Mask")]
        [Description("Collision filter mask for collision filtering.")]
        public PhysicsGroupsMask GroupsMask
        {
            get => RigidBody is PhysxActor actor ? FromPhysxGroupsMask(actor.GroupsMask) : _groupsMask;
            set
            {
                if (!SetField(ref _groupsMask, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.GroupsMask = ToPhysxGroupsMask(value);
            }
        }

        [Category("Collision")]
        [DisplayName("Dominance Group")]
        [Description("Collision resolution dominance (higher wins).")]
        public byte DominanceGroup
        {
            get => RigidBody is PhysxActor actor ? actor.DominanceGroup : _dominanceGroup;
            set
            {
                if (!SetField(ref _dominanceGroup, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.DominanceGroup = value;
            }
        }

        [Category("Physics / PhysX Extensions")]
        [DisplayName("PhysX Owner Client")]
        [Description("Legacy PhysX owner-client byte. Network authority uses OwnerClientId and OwnerServerPlayerIndex.")]
        public byte PhysxOwnerClient
        {
            get => RigidBody is PhysxActor actor ? actor.OwnerClient : _physxOwnerClient;
            set
            {
                if (!SetField(ref _physxOwnerClient, value))
                    return;
                if (RigidBody is PhysxActor physx)
                {
                    // PhysX disallows changing ownerClient while the actor is already in a scene.
                    if (physx.Scene is null)
                        physx.OwnerClient = value;
                }
            }
        }


        [Category("Networking")]
        [DisplayName("Replication Authority")]
        [Description("Defines which peer is authoritative for replicated physics state. This is metadata for networking handoff and does not change local simulation by itself.")]
        public PhysicsReplicationAuthority ReplicationAuthority
        {
            get => _replicationAuthority;
            set => SetField(ref _replicationAuthority, value);
        }

        [Category("Debug")]
        [DisplayName("Actor Name")]
        [Description("Debug name for the physics actor.")]
        public string? ActorName
        {
            get => RigidBody is PhysxActor actor ? actor.Name : _actorName;
            set
            {
                if (!SetField(ref _actorName, value))
                    return;
                if (RigidBody is PhysxActor physx)
                    physx.Name = value ?? string.Empty;
            }
        }

        protected override void OnComponentActivated()
        {
            base.OnComponentActivated();

            if (ShouldDeferAutoGeneratedConvexRigidBodyConstruction())
            {
                TryScheduleAutoGeneratedConvexColliders();
                return;
            }

            bool hadRigidBody = RigidBody is not null;
            EnsureRigidBodyConstructed();

            if (!hadRigidBody)
            {
                TryScheduleAutoGeneratedConvexColliders();
                return;
            }

            if (Engine.IsPhysicsThread)
            {
                ApplyCachedProperties();
            }
            else
            {
                Engine.EnqueuePhysicsThreadTask(() =>
                {
                    if (!IsActive || RigidBody is null)
                        return;
                    ApplyCachedProperties();
                });
            }
            TryRegisterRigidBodyWithScene();
            TryScheduleAutoGeneratedConvexColliders();
        }

        private bool ShouldDeferAutoGeneratedConvexRigidBodyConstruction()
            => RigidBody is null
            && Geometry is null
            && AutoGenerateConvexCollidersFromSiblingModel
            && !_autoConvexCollidersAttached
            && WorldAs<XREngine.Rendering.XRWorldInstance>()?.PhysicsScene is PhysxScene;

        protected override void OnComponentDeactivated()
        {
            base.OnComponentDeactivated();
            RemoveRigidBodyFromScene();
        }

        private void TryScheduleAutoGeneratedConvexColliders()
        {
            if (!AutoGenerateConvexCollidersFromSiblingModel || _autoConvexCollidersAttached)
                return;

            if (RigidBody is PhysxRigidActor existingActor && existingActor.ShapeCount > 0)
            {
                _autoConvexCollidersAttached = true;
                return;
            }

            if (!HasAutoGeneratedColliderInput())
                return;

            if (HasAutoGeneratedColliderMeshData())
            {
                BeginAutoGeneratedConvexColliderBuild();
                return;
            }

            if (_autoConvexColliderGenerationQueued)
                return;

            _autoConvexColliderGenerationQueued = true;
            Engine.AddAppThreadCoroutine(() =>
            {
                if (!AutoGenerateConvexCollidersFromSiblingModel || !IsActive)
                {
                    _autoConvexColliderGenerationQueued = false;
                    return true;
                }

                if (!HasAutoGeneratedColliderInput())
                {
                    _autoConvexColliderGenerationQueued = false;
                    return true;
                }

                if (!HasAutoGeneratedColliderMeshData())
                    return false;

                _autoConvexColliderGenerationQueued = false;
                BeginAutoGeneratedConvexColliderBuild();
                return true;
            });
        }

        private static bool HasCollisionMeshData(ModelComponent modelComponent)
            => modelComponent.Meshes.Count > 0 || (modelComponent.Model?.Meshes.Count ?? 0) > 0;

        private bool HasAutoGeneratedColliderInput()
            => TargetModelComponents is { Count: > 0 } || TargetModelComponent is not null || GetSiblingComponent<ModelComponent>() is not null;

        private bool HasAutoGeneratedColliderMeshData()
        {
            if (TargetModelComponents is { Count: > 0 } targetModelComponents)
            {
                for (int i = 0; i < targetModelComponents.Count; i++)
                    if (HasCollisionMeshData(targetModelComponents[i]))
                        return true;

                return false;
            }

            ModelComponent? modelComponent = TargetModelComponent ?? GetSiblingComponent<ModelComponent>();
            return modelComponent is not null && HasCollisionMeshData(modelComponent);
        }

        private void BeginAutoGeneratedConvexColliderBuild()
        {
            if (_autoConvexColliderGenerationStarted || _autoConvexCollidersAttached)
                return;

            _autoConvexColliderGenerationStarted = true;
            _ = GenerateAndAttachAutoGeneratedConvexCollidersAsync();
        }

        private async Task GenerateAndAttachAutoGeneratedConvexCollidersAsync()
        {
            BeginConvexHullGeneration("Preparing auto-generated convex colliders...");

            try
            {
                ConvexHullInputCollection? inputCollection = CollectCollisionInputCollectionForColliders();
                string colliderLabel = DescribeCollisionTargetForColliders();

                if (WorldAs<XREngine.Rendering.XRWorldInstance>()?.PhysicsScene is not PhysxScene)
                {
                    CompleteConvexHullGeneration("Auto-generated CoACD colliders require PhysX.");
                    Debug.LogWarning($"[StaticRigidBodyComponent] Auto-generated CoACD colliders currently require PhysX: {colliderLabel}");
                    return;
                }

                if (inputCollection is ConvexHullInputCollection inputs)
                    LogAutoGeneratedColliderInputs(colliderLabel, inputs);

                var progress = new Progress<ConvexHullGenerationProgress>(ReportConvexHullGenerationProgress);
                IReadOnlyList<PhysxConvexMesh> convexMeshes = await CreatePhysxConvexMeshesAsync(progress: progress, cancellationToken: default).ConfigureAwait(false);
                if (convexMeshes.Count == 0)
                {
                    IReadOnlyList<CoACD.ConvexHullMesh>? cachedHulls = GetCachedConvexHulls();
                    string failureReason = cachedHulls is { Count: > 0 }
                        ? $"PhysX rejected all {cachedHulls.Count} generated convex hulls"
                        : "CoACD produced no usable convex hulls";

                    CompleteConvexHullGeneration("No valid convex hulls generated.");
                    LogNoValidAutoGeneratedHullWarning(colliderLabel, inputCollection, failureReason);
                    return;
                }

                ReportConvexHullGenerationMessage("Attaching convex collider shapes...");

                void AttachShapes()
                {
                    if (!IsActive)
                    {
                        _autoConvexColliderGenerationStarted = false;
                        CompleteConvexHullGeneration("Auto-generated convex collider attachment canceled.");
                        return;
                    }

                    EnsureRigidBodyConstructed();
                    if (RigidBody is not PhysxStaticRigidBody body)
                    {
                        _autoConvexColliderGenerationStarted = false;
                        CompleteConvexHullGeneration("Static rigid body was not available for convex collider attachment.");
                        return;
                    }

                    if (body.ShapeCount > 0)
                    {
                        _autoConvexCollidersAttached = true;
                        CompleteConvexHullGeneration("Auto-generated convex colliders already attached.");
                        return;
                    }

                    PhysxMaterial material = ResolvePhysxExtensionMaterial();

                    for (int i = 0; i < convexMeshes.Count; i++)
                    {
                        PhysxConvexMesh convexMesh = convexMeshes[i];
                            unsafe
                            {
                                var geometry = new PhysxConvexMeshGeometryExtension(
                                    convexMesh.ConvexMeshPtr,
                                    Vector3.One,
                                    Quaternion.Identity,
                                    tightBounds: false);
                                var shape = new PhysxShape(
                                    geometry,
                                    material,
                                    PxShapeFlags.SimulationShape | PxShapeFlags.SceneQueryShape | PxShapeFlags.Visualization,
                                    isExclusive: true);
                                shape.LocalPose = (ShapeOffsetTranslation, ShapeOffsetRotation);
                                body.AttachShape(shape);
                            }
                    }

                    _autoConvexCollidersAttached = body.ShapeCount > 0;
                    if (_autoConvexCollidersAttached)
                    {
                        CompleteConvexHullGeneration($"Attached {body.ShapeCount} auto-generated convex collider shapes.");
                        Debug.Physics(
                            "[StaticRigidBodyComponent] Attached {0} auto-generated convex hull shapes to {1}",
                            body.ShapeCount,
                            colliderLabel);
                    }
                    else
                    {
                        CompleteConvexHullGeneration("No convex collider shapes were attached.");
                    }
                }

                if (Engine.IsPhysicsThread)
                    AttachShapes();
                else
                    Engine.EnqueuePhysicsThreadTask(AttachShapes);
            }
            catch (Exception ex)
            {
                _autoConvexColliderGenerationStarted = false;
                CompleteConvexHullGeneration($"Failed: {ex.Message}");
                Debug.PhysicsException(ex, $"Failed to auto-generate convex colliders for {DescribeCollisionTargetForColliders()}.");
            }
        }

        private void LogNoValidAutoGeneratedHullWarning(string colliderLabel, ConvexHullInputCollection? inputs, string failureReason)
        {
            if (s_loggedNoValidAutoGeneratedHullWarnings.TryAdd(colliderLabel, 0))
            {
                if (inputs is ConvexHullInputCollection inputReport)
                {
                    Debug.LogWarning(
                        $"[StaticRigidBodyComponent] No valid auto-generated colliders were produced for {colliderLabel}. Reason: {failureReason}. Runtime inputs={inputReport.Runtime.InputCount}/{inputReport.Runtime.SourceMeshCount}, Asset inputs={inputReport.Asset.InputCount}/{inputReport.Asset.SourceMeshCount}.");
                }
                else
                {
                    Debug.LogWarning($"[StaticRigidBodyComponent] No valid auto-generated colliders were produced for {colliderLabel}. Reason: {failureReason}.");
                }
                return;
            }

            Debug.Physics("[StaticRigidBodyComponent] Skipping repeated no-valid-hull warning for {0}", colliderLabel);
        }

        private void LogAutoGeneratedColliderInputs(string colliderLabel, ConvexHullInputCollection inputs)
        {
            Debug.Physics(
                "[StaticRigidBodyComponent] Auto-generated collider inputs for {0}: runtime={1} inputs across {2} render meshes ({3} verts/{4} tris), asset={5} inputs across {6} submeshes ({7} verts/{8} tris)",
                colliderLabel,
                inputs.Runtime.InputCount,
                inputs.Runtime.SourceMeshCount,
                inputs.Runtime.VertexCount,
                inputs.Runtime.TriangleCount,
                inputs.Asset.InputCount,
                inputs.Asset.SourceMeshCount,
                inputs.Asset.VertexCount,
                inputs.Asset.TriangleCount);
        }

        private void EnsureRigidBodyConstructed()
        {
            AbstractPhysicsScene? physicsScene = WorldAs<XREngine.Rendering.XRWorldInstance>()?.PhysicsScene;
            if (!AutoCreateRigidBody || RigidBody is not null || physicsScene is null)
                return;

            RigidBody = physicsScene.BackendService.CreateStaticRigidBody(BuildRigidBodyCreateInfo());
        }

        private PhysicsRigidBodyCreateInfo BuildRigidBodyCreateInfo()
        {
            LayerMask layerMask = CollisionGroup == 0
                ? new LayerMask(1)
                : new LayerMask(1 << CollisionGroup);

            return new PhysicsRigidBodyCreateInfo(
                    ColliderShapes,
                    Geometry,
                    Material,
                    MaterialDefinition,
                    GetSpawnPose(),
                    ShapeOffsetTranslation,
                    ShapeOffsetRotation,
                    0.0f,
                    layerMask)
                {
                    GravityEnabled = GravityEnabled,
                };
        }

        [Browsable(false)]
        public override IAbstractPhysicsActor? PhysicsActor => RigidBody;

        private PhysxMaterial ResolvePhysxExtensionMaterial()
        {
            if (Material is PhysxMaterial physxMaterial)
                return physxMaterial;

            PhysicsMaterialDefinition? definition = MaterialDefinition;
            var created = definition is null
                ? new PhysxMaterial(0.5f, 0.5f, 0.1f)
                : new PhysxMaterial(
                    definition.StaticFriction,
                    definition.DynamicFriction,
                    definition.Restitution)
                {
                    Damping = definition.Damping,
                };
            Material = created;
            return created;
        }

        [Category("Networking")]
        public NetworkEntityId NetworkEntityId
        {
            get => _networkEntityId;
            set => SetField(ref _networkEntityId, value);
        }

        [Category("Networking")]
        public string? OwnerClientId
        {
            get => _ownerClientId;
            set => SetField(ref _ownerClientId, value);
        }

        [Category("Networking")]
        public int OwnerServerPlayerIndex
        {
            get => _ownerServerPlayerIndex;
            set => SetField(ref _ownerServerPlayerIndex, value);
        }

        public void RebuildCollisionShapes(bool wakeOnLostTouch = true)
        {
            IAbstractStaticRigidBody? oldBody = RigidBody;
            AbstractPhysicsScene? physicsScene = WorldAs<XREngine.Rendering.XRWorldInstance>()?.PhysicsScene;
            if (oldBody is not null
                && physicsScene is not null
                && physicsScene.BackendService.TryReplaceCollisionShapes(oldBody, BuildRigidBodyCreateInfo()))
            {
                return;
            }

            RigidBody = null;
            oldBody?.Destroy(wakeOnLostTouch);
            EnsureRigidBodyConstructed();
        }

        protected override bool OnPropertyChanging<T>(string? propName, T field, T @new)
        {
            bool change = base.OnPropertyChanging(propName, field, @new);
            if (change && propName == nameof(RigidBody) && RigidBody is not null)
            {
                RemoveRigidBodyFromScene();

                if (_rigidBodyOwnershipSyncDepth == 0)
                {
                    if (RigidBody.OwningComponent == this)
                        RigidBody.OwningComponent = null;
                }

                if (RigidBodyTransform.RigidBody == RigidBody)
                    RigidBodyTransform.RigidBody = null;
            }
            return change;
        }

        protected override void OnPropertyChanged<T>(string? propName, T prev, T field)
        {
            base.OnPropertyChanged(propName, prev, field);
            if (propName == nameof(RigidBody))
            {
                NotifyPhysicsActorChanged(
                    prev is IAbstractPhysicsActor previousActor ? previousActor : null,
                    RigidBody);
                if (RigidBody is null)
                    return;

                if (_rigidBodyOwnershipSyncDepth == 0)
                    RigidBody.OwningComponent = this;
                RigidBodyTransform.RigidBody = RigidBody;
                ApplyCachedProperties();
                TryRegisterRigidBodyWithScene();
                return;
            }
        }

        private void ApplyCachedProperties()
        {
            ApplyCachedProperties(RigidBody);
        }

        private void ApplyCachedProperties(IAbstractStaticRigidBody? body)
        {
            if (body is PhysxActor actor)
            {
                ApplyCachedProperties(actor);
                return;
            }

            if (body is JoltStaticRigidBody jolt)
            {
                jolt.SetObjectLayer(_collisionGroup, _groupsMask.Word0);
                if (!_simulationEnabled)
                    Debug.Physics("[StaticRigidBodyComponent] Jolt does not currently support SimulationEnabled parity for static bodies; value cached only.");
            }
        }

        private void ApplyCachedProperties(PhysxActor actor)
        {
            actor.GravityEnabled = _gravityEnabled;
            actor.SimulationEnabled = _simulationEnabled;
            actor.DebugVisualize = _debugVisualization;
            actor.SendSleepNotifies = _sendSleepNotifies;
            actor.CollisionGroup = _collisionGroup;
            actor.GroupsMask = ToPhysxGroupsMask(_groupsMask);
            actor.DominanceGroup = _dominanceGroup;
            // PhysX disallows setting ownerClient once the actor is inserted into a scene.
            if (actor.Scene is null)
                actor.OwnerClient = _physxOwnerClient;
            if (_actorName is not null)
                actor.Name = _actorName;

            Debug.Physics(
                "[StaticRigidBodyComponent] Applied cached props to {0} actorType={1} group={2} mask={3}",
                SceneNode?.Name ?? "<unnamed>",
                actor.GetType().Name,
                actor.CollisionGroup,
                FormatGroupsMask(actor.GroupsMask));
        }

        private static PhysicsGroupsMask FromPhysxGroupsMask(PxGroupsMask mask)
            => new(mask.bits0, mask.bits1, mask.bits2, mask.bits3);

        private static PxGroupsMask ToPhysxGroupsMask(PhysicsGroupsMask mask)
        {
            PxGroupsMask m;
            m.bits0 = (ushort)mask.Word0;
            m.bits1 = (ushort)mask.Word1;
            m.bits2 = (ushort)mask.Word2;
            m.bits3 = (ushort)mask.Word3;
            return m;
        }

        private void TryRegisterRigidBodyWithScene()
        {
            if (!IsActive || RigidBody is null)
                return;

            var scene = WorldAs<XREngine.Rendering.XRWorldInstance>()?.PhysicsScene;
            if (scene is null)
                return;

            if (_registeredPhysicsScene == scene)
                return;

            if (_registeredPhysicsScene is not null && _registeredPhysicsScene != scene)
                _registeredPhysicsScene.RemoveActor(RigidBody);

            scene.AddActor(RigidBody);
            _registeredPhysicsScene = scene;
            if (RigidBody is PhysxActor actor)
            {
                Debug.Physics(
                    "[StaticRigidBodyComponent] Registered actorType={0} with scene {1} (group={2}, mask={3})",
                    actor.GetType().Name,
                    scene.GetType().Name,
                    actor.CollisionGroup,
                    FormatGroupsMask(actor.GroupsMask));
            }
        }

        private void RemoveRigidBodyFromScene()
        {
            if (RigidBody is null)
            {
                _registeredPhysicsScene = null;
                return;
            }

            if (_registeredPhysicsScene is not null)
            {
                _registeredPhysicsScene.RemoveActor(RigidBody);
                if (RigidBody is PhysxActor actor)
                {
                    Debug.Physics(
                        "[StaticRigidBodyComponent] Removed actorType={0} from scene {1}",
                        actor.GetType().Name,
                        _registeredPhysicsScene.GetType().Name);
                }
                _registeredPhysicsScene = null;
            }
        }

        private static string FormatGroupsMask(PxGroupsMask mask)
            => $"{mask.bits0:X4}:{mask.bits1:X4}:{mask.bits2:X4}:{mask.bits3:X4}";
    }
}
