using XREngine.Rendering.Commands;

namespace XREngine.Rendering;

/// <summary>
/// Canonical owner of logical texture and sampler rows. Handles are generated by
/// the contained tables and are never derived from backend descriptor identities.
/// </summary>
public sealed partial class AdvancedGlobalResourceDatabase
{
    private ulong _textureGeneration;
    private ulong _samplerGeneration;
    private ulong _lightGeneration;
    private ulong _shadowGeneration;
    private ulong _probeGeneration;
    private ulong _environmentGeneration;
    private ulong _decalGeneration;
    private ulong _giResourceGeneration;

    public AdvancedGlobalResourceDatabase(
        uint textureCapacity,
        uint samplerCapacity,
        uint lightCapacity = 0u,
        uint shadowCapacity = 0u,
        uint probeCapacity = 0u,
        uint environmentCapacity = 0u,
        uint decalCapacity = 0u,
        uint giResourceCapacity = 0u)
    {
        Textures = new AdvancedGpuRecordTable<AdvancedTextureRecord>(textureCapacity);
        Samplers = new AdvancedGpuRecordTable<AdvancedSamplerRecord>(samplerCapacity);
        Lights = new AdvancedGpuRecordTable<AdvancedLightRecord>(lightCapacity);
        Shadows = new AdvancedGpuRecordTable<AdvancedShadowRecord>(shadowCapacity);
        Probes = new AdvancedGpuRecordTable<AdvancedProbeRecord>(probeCapacity);
        Environments = new AdvancedGpuRecordTable<AdvancedEnvironmentRecord>(environmentCapacity);
        Decals = new AdvancedGpuRecordTable<AdvancedDecalRecord>(decalCapacity);
        GiResources = new AdvancedGpuRecordTable<AdvancedGiResourceRecord>(giResourceCapacity);
    }

    /// <summary>Stable, generation-checked logical texture rows.</summary>
    public AdvancedGpuRecordTable<AdvancedTextureRecord> Textures { get; }

    /// <summary>Stable, generation-checked logical sampler rows.</summary>
    public AdvancedGpuRecordTable<AdvancedSamplerRecord> Samplers { get; }

    /// <summary>Canonical native-shading light rows.</summary>
    public AdvancedGpuRecordTable<AdvancedLightRecord> Lights { get; }

    /// <summary>Canonical shadow-map and transform rows.</summary>
    public AdvancedGpuRecordTable<AdvancedShadowRecord> Shadows { get; }

    /// <summary>Canonical irradiance and reflection probe rows.</summary>
    public AdvancedGpuRecordTable<AdvancedProbeRecord> Probes { get; }

    /// <summary>Canonical global environment rows.</summary>
    public AdvancedGpuRecordTable<AdvancedEnvironmentRecord> Environments { get; }

    /// <summary>Canonical deferred decal rows.</summary>
    public AdvancedGpuRecordTable<AdvancedDecalRecord> Decals { get; }

    /// <summary>Canonical global-illumination resource rows.</summary>
    public AdvancedGpuRecordTable<AdvancedGiResourceRecord> GiResources { get; }

    /// <summary>Current independent owner-domain generations.</summary>
    public AdvancedGlobalResourceDatabaseGenerations Generations
        => new(
            Textures.Generations,
            Samplers.Generations,
            Lights.Generations,
            Shadows.Generations,
            Probes.Generations,
            Environments.Generations,
            Decals.Generations,
            GiResources.Generations);

    /// <summary>Adds one logical texture and stamps its canonical identity.</summary>
    public bool TryAddTexture(in AdvancedTextureRecord source, out AdvancedGpuHandle handle)
    {
        if (source.DefaultSampler.IsValid && !Samplers.IsCurrent(source.DefaultSampler))
        {
            handle = AdvancedGpuHandle.Invalid;
            return false;
        }

        AdvancedTextureRecord record = source;
        record.StableTextureId = 0u;
        record.Generation = 0u;
        if (!Textures.TryAdd(record, out handle))
            return false;

        record.StableTextureId = handle.Index;
        record.Generation = handle.Generation;
        if (!Textures.TryReplace(handle, record))
            throw new InvalidOperationException("Newly inserted texture could not be initialized.");

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Replaces a current logical texture without changing its identity.</summary>
    public bool TryReplaceTexture(AdvancedGpuHandle handle, in AdvancedTextureRecord source)
    {
        if (!Textures.IsCurrent(handle) ||
            (source.DefaultSampler.IsValid && !Samplers.IsCurrent(source.DefaultSampler)))
            return false;

        AdvancedTextureRecord record = source;
        record.StableTextureId = handle.Index;
        record.Generation = handle.Generation;
        if (!Textures.TryReplace(handle, record))
            return false;

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Adds one logical sampler and stamps its canonical identity.</summary>
    public bool TryAddSampler(in AdvancedSamplerRecord source, out AdvancedGpuHandle handle)
    {
        AdvancedSamplerRecord record = source;
        record.StableSamplerId = 0u;
        record.Generation = 0u;
        if (!Samplers.TryAdd(record, out handle))
            return false;

        record.StableSamplerId = handle.Index;
        record.Generation = handle.Generation;
        if (!Samplers.TryReplace(handle, record))
            throw new InvalidOperationException("Newly inserted sampler could not be initialized.");

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Replaces a current logical sampler without changing its identity.</summary>
    public bool TryReplaceSampler(AdvancedGpuHandle handle, in AdvancedSamplerRecord source)
    {
        if (!Samplers.IsCurrent(handle))
            return false;

        AdvancedSamplerRecord record = source;
        record.StableSamplerId = handle.Index;
        record.Generation = handle.Generation;
        if (!Samplers.TryReplace(handle, record))
            return false;

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Tombstones a texture until its publication is safe to reclaim.</summary>
    public bool RemoveTexture(AdvancedGpuHandle handle)
    {
        if (!Textures.TryTombstone(handle))
            return false;

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Tombstones a sampler until its publication is safe to reclaim.</summary>
    public bool RemoveSampler(AdvancedGpuHandle handle)
    {
        if (!Samplers.TryTombstone(handle))
            return false;

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Gets the exact current texture record for a canonical handle.</summary>
    public bool TryGetTexture(AdvancedGpuHandle handle, out AdvancedTextureRecord record)
        => Textures.TryGet(handle, out record);

    /// <summary>Gets the exact current sampler record for a canonical handle.</summary>
    public bool TryGetSampler(AdvancedGpuHandle handle, out AdvancedSamplerRecord record)
        => Samplers.TryGet(handle, out record);

    /// <summary>Tests whether a texture handle is current and has not been tombstoned.</summary>
    public bool IsCurrentTexture(AdvancedGpuHandle handle) => Textures.IsCurrent(handle);

    /// <summary>Tests whether a sampler handle is current and has not been tombstoned.</summary>
    public bool IsCurrentSampler(AdvancedGpuHandle handle) => Samplers.IsCurrent(handle);

    /// <summary>Grows both resource tables only at an explicit structural boundary.</summary>
    public void GrowAtFrameBoundary(uint textureCapacity, uint samplerCapacity)
    {
        Textures.GrowAtBoundary(textureCapacity);
        Samplers.GrowAtBoundary(samplerCapacity);
    }

    /// <summary>Grows all global scene tables at an explicit structural boundary.</summary>
    public void GrowAtFrameBoundary(
        uint textureCapacity,
        uint samplerCapacity,
        uint lightCapacity,
        uint shadowCapacity,
        uint probeCapacity,
        uint environmentCapacity,
        uint decalCapacity,
        uint giResourceCapacity)
    {
        GrowAtFrameBoundary(textureCapacity, samplerCapacity);
        Lights.GrowAtBoundary(lightCapacity);
        Shadows.GrowAtBoundary(shadowCapacity);
        Probes.GrowAtBoundary(probeCapacity);
        Environments.GrowAtBoundary(environmentCapacity);
        Decals.GrowAtBoundary(decalCapacity);
        GiResources.GrowAtBoundary(giResourceCapacity);
    }

    private static void IncrementGeneration(ref ulong generation)
    {
        unchecked { ++generation; }
        if (generation == 0u)
            generation = 1u;
    }
}
