using XREngine.Rendering.Commands;

namespace XREngine.Rendering;

/// <summary>
/// Canonical owner of logical texture and sampler rows. Handles are generated by
/// the contained tables and are never derived from backend descriptor identities.
/// </summary>
public sealed class AdvancedGlobalResourceDatabase
{
    private ulong _textureGeneration;
    private ulong _samplerGeneration;

    public AdvancedGlobalResourceDatabase(uint textureCapacity, uint samplerCapacity)
    {
        Textures = new AdvancedGpuRecordTable<AdvancedTextureRecord>(textureCapacity);
        Samplers = new AdvancedGpuRecordTable<AdvancedSamplerRecord>(samplerCapacity);
    }

    /// <summary>Stable, generation-checked logical texture rows.</summary>
    public AdvancedGpuRecordTable<AdvancedTextureRecord> Textures { get; }

    /// <summary>Stable, generation-checked logical sampler rows.</summary>
    public AdvancedGpuRecordTable<AdvancedSamplerRecord> Samplers { get; }

    /// <summary>Current independent table content generations.</summary>
    public AdvancedGlobalResourceDatabaseGenerations Generations
        => new(_textureGeneration, _samplerGeneration);

    /// <summary>Adds one logical texture and stamps its canonical identity.</summary>
    public bool TryAddTexture(in AdvancedTextureRecord source, out AdvancedGpuHandle handle)
    {
        if (source.DefaultSampler.IsValid && !Samplers.IsCurrent(source.DefaultSampler))
        {
            handle = AdvancedGpuHandle.Invalid;
            return false;
        }

        AdvancedTextureRecord record = source;
        record.StableTextureId = 0u;
        record.Generation = 0u;
        if (!Textures.TryAdd(record, out handle))
            return false;

        record.StableTextureId = handle.Index;
        record.Generation = handle.Generation;
        if (!Textures.TryReplace(handle, record))
            throw new InvalidOperationException("Newly inserted texture could not be initialized.");

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Replaces a current logical texture without changing its identity.</summary>
    public bool TryReplaceTexture(AdvancedGpuHandle handle, in AdvancedTextureRecord source)
    {
        if (!Textures.IsCurrent(handle) ||
            (source.DefaultSampler.IsValid && !Samplers.IsCurrent(source.DefaultSampler)))
            return false;

        AdvancedTextureRecord record = source;
        record.StableTextureId = handle.Index;
        record.Generation = handle.Generation;
        if (!Textures.TryReplace(handle, record))
            return false;

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Adds one logical sampler and stamps its canonical identity.</summary>
    public bool TryAddSampler(in AdvancedSamplerRecord source, out AdvancedGpuHandle handle)
    {
        AdvancedSamplerRecord record = source;
        record.StableSamplerId = 0u;
        record.Generation = 0u;
        if (!Samplers.TryAdd(record, out handle))
            return false;

        record.StableSamplerId = handle.Index;
        record.Generation = handle.Generation;
        if (!Samplers.TryReplace(handle, record))
            throw new InvalidOperationException("Newly inserted sampler could not be initialized.");

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Replaces a current logical sampler without changing its identity.</summary>
    public bool TryReplaceSampler(AdvancedGpuHandle handle, in AdvancedSamplerRecord source)
    {
        if (!Samplers.IsCurrent(handle))
            return false;

        AdvancedSamplerRecord record = source;
        record.StableSamplerId = handle.Index;
        record.Generation = handle.Generation;
        if (!Samplers.TryReplace(handle, record))
            return false;

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Tombstones a texture until its publication is safe to reclaim.</summary>
    public bool RemoveTexture(AdvancedGpuHandle handle)
    {
        if (!Textures.TryTombstone(handle))
            return false;

        IncrementGeneration(ref _textureGeneration);
        return true;
    }

    /// <summary>Tombstones a sampler until its publication is safe to reclaim.</summary>
    public bool RemoveSampler(AdvancedGpuHandle handle)
    {
        if (!Samplers.TryTombstone(handle))
            return false;

        IncrementGeneration(ref _samplerGeneration);
        return true;
    }

    /// <summary>Gets the exact current texture record for a canonical handle.</summary>
    public bool TryGetTexture(AdvancedGpuHandle handle, out AdvancedTextureRecord record)
        => Textures.TryGet(handle, out record);

    /// <summary>Gets the exact current sampler record for a canonical handle.</summary>
    public bool TryGetSampler(AdvancedGpuHandle handle, out AdvancedSamplerRecord record)
        => Samplers.TryGet(handle, out record);

    /// <summary>Tests whether a texture handle is current and has not been tombstoned.</summary>
    public bool IsCurrentTexture(AdvancedGpuHandle handle) => Textures.IsCurrent(handle);

    /// <summary>Tests whether a sampler handle is current and has not been tombstoned.</summary>
    public bool IsCurrentSampler(AdvancedGpuHandle handle) => Samplers.IsCurrent(handle);

    /// <summary>Grows both resource tables only at an explicit structural boundary.</summary>
    public void GrowAtFrameBoundary(uint textureCapacity, uint samplerCapacity)
    {
        Textures.GrowAtBoundary(textureCapacity);
        Samplers.GrowAtBoundary(samplerCapacity);
    }

    private static void IncrementGeneration(ref ulong generation)
    {
        unchecked { ++generation; }
        if (generation == 0u)
            generation = 1u;
    }
}
