using System.Buffers;
using Silk.NET.Vulkan;

namespace XREngine.Rendering.Vulkan;

internal sealed partial class VkTexture2DArray
{
    /// <summary>Copies the authored mip chain; prefilter mips must never be regenerated by filtering.</summary>
    private void PushGpuLayerSources()
    {
        XRTexture2D[] sources = Data.Textures;
        if (sources.Length == 0 || Data.AutoGenerateMipmaps || Data.MultiSample)
            throw new InvalidOperationException("GPU array copies require non-empty, single-sample sources and authored mips.");

        TextureLayout layout = DescribeTexture();
        int regionCount = checked(sources.Length * (int)layout.MipLevels);
        VulkanTextureArrayCopyRegion[]? rented = null;
        Span<VulkanTextureArrayCopyRegion> regions = regionCount <= 64
            ? stackalloc VulkanTextureArrayCopyRegion[regionCount]
            : (rented = ArrayPool<VulkanTextureArrayCopyRegion>.Shared.Rent(regionCount)).AsSpan(0, regionCount);
        try
        {
            // Resolve source generations without generating or uploading them:
            // stale CPU data must never overwrite a completed GPU producer.
            for (int layer = 0; layer < sources.Length; layer++)
            {
                if (GetBackendWrapper(sources[layer], generateNow: false) is not VkTexture2D source)
                    throw new InvalidOperationException($"GPU texture array '{Data.Name}' layer {layer} has no live Vulkan source.");
                IVkFrameBufferAttachmentSource attachment = source;
                lock (attachment.DescriptorSnapshotSyncRoot)
                {
                    if (!attachment.TryGetDescriptorSnapshot(null, null, "ArrayGpuCopy", false, out VkImageDescriptorSnapshot snapshot) ||
                        snapshot.Samples != SampleCountFlags.Count1Bit || snapshot.Aspect != ImageAspectFlags.ColorBit ||
                        snapshot.ArrayLayers != 1 || snapshot.MipLevels != layout.MipLevels ||
                        (snapshot.Usage & ImageUsageFlags.TransferSrcBit) == 0)
                        throw new InvalidOperationException($"GPU texture array '{Data.Name}' layer {layer} has an unavailable or incompatible source/mip chain.");

                    ulong generation = BackendContext.GetResourceGeneration(ObjectType.Image, snapshot.Image.Handle);
                    if (generation == 0)
                        throw new InvalidOperationException("GPU texture array source generation is retiring.");
                    for (uint mip = 0; mip < layout.MipLevels; mip++)
                    {
                        Extent3D extent = new(Math.Max(1u, layout.Extent.Width >> (int)mip), Math.Max(1u, layout.Extent.Height >> (int)mip), 1);
                        ImageLayout sourceLayout = attachment.GetAttachmentTrackedLayout((int)mip, 0);
                        if (snapshot.Format != VkFormatConversions.FromSizedFormat(Data.SizedInternalFormat) ||
                            !attachment.TryGetAttachmentExtent((int)mip, 0, out Extent2D sourceExtent) ||
                            sourceExtent.Width != extent.Width || sourceExtent.Height != extent.Height ||
                            sourceLayout is ImageLayout.Undefined or ImageLayout.Preinitialized)
                            throw new InvalidOperationException($"GPU texture array '{Data.Name}' layer {layer}, mip {mip} is incompatible or uninitialized.");
                        regions[layer * (int)layout.MipLevels + (int)mip] = new(snapshot.Image, generation, sourceLayout, mip, (uint)layer, extent);
                    }
                }
            }

            RecreateImageForFullTextureDataUpload("GPU texture array assembly");
            Generate();
            if ((Usage & ImageUsageFlags.TransferDstBit) == 0 || SampleCount != SampleCountFlags.Count1Bit ||
                ResolvedMipLevels != layout.MipLevels || ResolvedArrayLayers != (uint)sources.Length ||
                ResolvedFormat != VkFormatConversions.FromSizedFormat(Data.SizedInternalFormat))
                throw new InvalidOperationException("GPU texture array destination does not support single-sample transfer writes.");
            foreach (ref readonly VulkanTextureArrayCopyRegion region in regions)
                if (region.Source.Handle == Image.Handle)
                    throw new InvalidOperationException("GPU texture array source aliases its destination.");

            ImageLayout finalLayout = (Usage & ImageUsageFlags.StorageBit) != 0
                ? ImageLayout.General : ImageLayout.ShaderReadOnlyOptimal;
            ulong destinationGeneration = BackendContext.GetResourceGeneration(ObjectType.Image, Image.Handle);
            if (destinationGeneration == 0)
                throw new InvalidOperationException("GPU texture array destination generation is retiring.");
            ResourceCommandPort.CopyTextureArrayLayers(Image,
                destinationGeneration, CurrentImageLayout,
                finalLayout, layout.MipLevels, (uint)sources.Length, regions);
            ((IVkFrameBufferAttachmentSource)this).UpdateTrackedLayout(finalLayout);
        }
        finally
        {
            if (rented is not null)
                ArrayPool<VulkanTextureArrayCopyRegion>.Shared.Return(rented);
        }
    }
}
