using System;
using System.ComponentModel;
using System.Numerics;
using System.Runtime.InteropServices;
using XREngine;
using XREngine.Data.Geometry;
using XREngine.Data.Rendering;
using XREngine.Diagnostics;
using XREngine.Rendering;
using XREngine.Rendering.Commands;
using XREngine.Rendering.Info;
using XREngine.Rendering.Models;
using XREngine.Rendering.Models.Materials;
using XREngine.Rendering.Tools;
using XREngine.Scene.Transforms;

namespace XREngine.Components.Scene.Mesh
{
    /// <summary>
    /// Renders a camera-facing quad that blends between 26 baked octahedral imposter views.
    /// </summary>
    [Serializable]
    [Category("Rendering")]
    [DisplayName("Octahedral Billboard")]
    [Description("Renders a camera-facing quad that samples a baked octahedral imposter texture array.")]
    public sealed class OctahedralBillboardComponent : XRComponent, IRenderable
    {
        private static readonly Vector2 s_minSize = new(0.01f);

        [StructLayout(LayoutKind.Sequential)]
        private struct OctahedralInstanceGpuData
        {
            public Matrix4x4 CurrentModel;
            public Matrix4x4 PreviousModel;
        }

        private readonly RenderCommandMesh3D _renderCommand;
        private readonly RenderInfo3D _renderInfo;
        private readonly RenderInfo[] _renderInfos;

        private Vector2 _billboardSize = Vector2.One;
        private XRTexture2DArray? _imposterViews;

        private XRMesh? _mesh;
        private XRMeshRenderer? _renderer;
        private XRMaterial? _material;
        private XRShader? _vertexShader;
        private XRShader? _fragmentShader;
        private XRDataBuffer? _instanceBuffer;

        private OctahedralInstanceGpuData _instanceData;
        private bool _instanceDirty = true;
        private bool _hasPrevMatrix;

        public OctahedralBillboardComponent()
        {
            _renderCommand = new RenderCommandMesh3D((int)EDefaultRenderPass.TransparentForward)
            {
                WorldMatrixIsModelMatrix = true,
                WorldMatrix = Matrix4x4.Identity,
                Instances = 1u
            };
            _renderCommand.PreRender += OnPreRender;

            _renderInfo = RenderInfo3D.New(this, _renderCommand);
            _renderInfos = [_renderInfo];

            UpdateCullingVolume();
            RecreateRenderer();
        }

        /// <summary>
        /// Local width (X) and height (Y) of the billboard quad before billboarding is applied.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Quad Size")]
        [Description("Local width (X) and height (Y) of the billboard quad before billboarding is applied.")]
        public Vector2 BillboardSize
        {
            get => _billboardSize;
            set
            {
                Vector2 sanitized = SanitizeSize(value);
                if (SetField(ref _billboardSize, sanitized))
                {
                    UpdateCullingVolume();
                    RecreateRenderer();
                }
            }
        }

        /// <summary>
        /// Texture array containing the 26 baked views generated by <see cref="OctahedralImposterGenerator"/>.
        /// Layer ordering must match <see cref="OctahedralImposterGenerator"/> and the runtime shader.
        /// </summary>
        [Category("Octahedral Billboard")]
        [DisplayName("Imposter Views")]
        [Description("Texture array containing the 26 baked captures in the generator's order.")]
        public XRTexture2DArray? ImposterViews
        {
            get => _imposterViews;
            set
            {
                if (SetField(ref _imposterViews, value))
                    UpdateMaterialTexture();
            }
        }

        public RenderInfo[] RenderedObjects => _renderInfos;

        /// <summary>
        /// Copies texture data and approximate sizing from a freshly baked impostor capture.
        /// </summary>
        public void ApplyCaptureResult(OctahedralImposterGenerator.Result result, bool matchBounds = true)
        {
            ArgumentNullException.ThrowIfNull(result);
            ImposterViews = result.Views;

            if (matchBounds)
            {
                Vector3 boundsSize = result.LocalBounds.Size;
                float width = MathF.Max(boundsSize.X, boundsSize.Z);
                float height = boundsSize.Y;
                BillboardSize = new Vector2(width, height);
            }
        }

        protected override void OnTransformRenderWorldMatrixChanged(TransformBase transform, Matrix4x4 renderMatrix)
        {
            base.OnTransformRenderWorldMatrixChanged(transform, renderMatrix);
            _renderInfo.CullingOffsetMatrix = renderMatrix;
            UpdateInstanceMatrices();
        }

        protected override void OnDestroying()
        {
            base.OnDestroying();
            DisposeRenderer();
        }

        private void OnPreRender()
            => UploadInstanceData();

        private void RecreateRenderer()
        {
            DisposeRenderer();

            XRMesh? mesh = BuildQuadMesh();
            XRMaterial? material = BuildMaterial();
            if (mesh is null || material is null)
            {
                Debug.LogWarning("Failed to build octahedral billboard renderer. Renderer will be inactive.");
                return;
            }

            _mesh = mesh;
            _material = material;
            _renderer = new XRMeshRenderer(mesh, material);

            _instanceBuffer = CreateInstanceBuffer();
            if (_instanceBuffer is not null)
                _renderer.Buffers.Add(_instanceBuffer.AttributeName, _instanceBuffer);

            _renderCommand.Mesh = _renderer;
            _renderCommand.RenderPass = material.RenderPass;
            _renderCommand.Instances = 1u;

            _instanceDirty = true;
            UpdateInstanceMatrices(forceUpload: true);
        }

        private XRMesh? BuildQuadMesh()
        {
            XRMesh quad = XRMesh.Create(VertexQuad.PosZ(
                _billboardSize.X,
                _billboardSize.Y,
                0.0f,
                bottomLeftOrigin: false,
                flipVerticalUVCoord: false));
            quad.SupportsBillboarding = false;
            return quad;
        }

        private XRMaterial? BuildMaterial()
        {
            XRShader? vertex = LoadVertexShader();
            XRShader? fragment = LoadFragmentShader();
            if (vertex is null || fragment is null)
                return null;

            XRMaterial material = new(vertex, fragment)
            {
                BillboardMode = EMeshBillboardMode.None,
                RenderPass = (int)EDefaultRenderPass.TransparentForward,
                RenderOptions = new RenderingParameters
                {
                    CullMode = ECullMode.None,
                    BlendModeAllDrawBuffers = BlendMode.EnabledTransparent(),
                    DepthTest = new DepthTest
                    {
                        Enabled = ERenderParamUsage.Enabled,
                        Function = EComparison.Lequal,
                        UpdateDepth = false
                    },
                    RequiredEngineUniforms = EUniformRequirements.Camera
                }
            };

            UpdateMaterialTexture(material);
            return material;
        }

        private XRShader? LoadVertexShader()
        {
            if (_vertexShader is not null)
                return _vertexShader;

            XRShader? shader = Engine.Assets.LoadEngineAsset<XRShader>(JobPriority.Highest, "Shaders", "Scene3D", "OctahedralImposterBillboard.vs");
            if (shader is null)
                Debug.LogWarning("Unable to load OctahedralImposterBillboard.vs.");
            _vertexShader = shader;
            return shader;
        }

        private XRShader? LoadFragmentShader()
        {
            if (_fragmentShader is not null)
                return _fragmentShader;

            XRShader? shader = Engine.Assets.LoadEngineAsset<XRShader>(JobPriority.Highest, "Shaders", "Scene3D", "OctahedralImposterBillboard.fs");
            if (shader is null)
            {
                Debug.LogWarning("Unable to load OctahedralImposterBillboard.fs. Billboard imposters will render blank.");
                shader = new XRShader(EShaderType.Fragment, ShaderHelper.Frag_Nothing);
            }

            _fragmentShader = shader;
            return shader;
        }

        private XRDataBuffer? CreateInstanceBuffer()
        {
            uint stride = (uint)Marshal.SizeOf<OctahedralInstanceGpuData>();
            XRDataBuffer buffer = new("OctahedralImposters", EBufferTarget.ShaderStorageBuffer, 1, EComponentType.Struct, stride, false, false)
            {
                Usage = EBufferUsage.StreamDraw,
                DisposeOnPush = false,
                PadEndingToVec4 = true
            };
            buffer.PushData();
            return buffer;
        }

        private void UpdateMaterialTexture(XRMaterial? targetMaterial = null)
        {
            var mat = targetMaterial ?? _material;
            if (mat is null)
                return;

            if (mat.Textures.Count == 0)
            {
                if (_imposterViews is not null)
                    mat.Textures.Add(_imposterViews);
            }
            else
            {
                mat.Textures[0] = _imposterViews;
            }
        }

        private void UpdateCullingVolume()
        {
            Vector3 halfExtents = new(_billboardSize.X * 0.5f, _billboardSize.Y * 0.5f, 0.01f);
            _renderInfo.LocalCullingVolume = new AABB(-halfExtents, halfExtents);
        }

        private void UpdateInstanceMatrices(bool forceUpload = false)
        {
            if (_renderer is null)
                return;

            Matrix4x4 current = Transform.RenderMatrix;
            _renderCommand.WorldMatrix = current;

            if (!_hasPrevMatrix)
            {
                _instanceData.PreviousModel = current;
                _hasPrevMatrix = true;
            }
            else
            {
                _instanceData.PreviousModel = _instanceData.CurrentModel;
            }

            _instanceData.CurrentModel = current;
            _instanceDirty = true;

            if (forceUpload)
                UploadInstanceData();
        }

        private void UploadInstanceData()
        {
            if (!_instanceDirty || _instanceBuffer is null)
                return;

            _instanceBuffer.Set(0, _instanceData);
            _instanceBuffer.PushSubData();
            _instanceDirty = false;
        }

        private void DisposeRenderer()
        {
            _renderCommand.Mesh = null;

            _instanceBuffer?.Destroy();
            _instanceBuffer = null;

            _renderer?.Destroy();
            _renderer = null;

            _mesh?.Destroy();
            _mesh = null;

            _material?.Destroy();
            _material = null;

            _hasPrevMatrix = false;
            _instanceDirty = true;
        }

        private static Vector2 SanitizeSize(Vector2 size)
        {
            float width = MathF.Max(s_minSize.X, float.IsFinite(size.X) ? size.X : s_minSize.X);
            float height = MathF.Max(s_minSize.Y, float.IsFinite(size.Y) ? size.Y : s_minSize.Y);
            return new Vector2(width, height);
        }
    }
}
