using Assimp;
using Extensions;
using System.Numerics;
using XREngine;
using XREngine.Animation;
using XREngine.Animation.IK;
using XREngine.Components;
using XREngine.Components.Capture;
using XREngine.Components.Physics;
using XREngine.Components.Animation;
using XREngine.Components.Movement;
using XREngine.Components.Scene.Mesh;
using XREngine.Components.Scene.Transforms;
using XREngine.Data.Colors;
using XREngine.Data.Components;
using XREngine.Data.Core;
using XREngine.Data.Geometry;
using XREngine.Data.Rendering;
using XREngine.Rendering;
using XREngine.Rendering.Models;
using XREngine.Rendering.Models.Materials;
using XREngine.Scene;
using XREngine.Scene.Transforms;
using Quaternion = System.Numerics.Quaternion;

namespace XREngine.Editor;

public static partial class EditorUnitTests
{
    public static class Models
    {
        private static ModelImporter.DelMakeMaterialAction ResolveMakeMaterialAction(Settings.ModelImportSettings model)
        {
            ModelImporter.DelMakeMaterialAction baseAction = model.MaterialMode switch
            {
                ModelImportMaterialMode.Deferred => ModelImporter.MakeMaterialDeferred,
                ModelImportMaterialMode.Forward => ModelImporter.MakeMaterialForwardPlusTextured,
                ModelImportMaterialMode.Uber => ModelImporter.MakeMaterialForwardPlusUberShader,
                _ => ModelImporter.MakeMaterialDeferred,
            };

            // When deferred mode is active and the user wants forward rendering for transparent
            // textures, wrap the factory so that materials with alpha fall back to the lit forward path.
            if (model.MaterialMode == ModelImportMaterialMode.Deferred && model.UseForwardForTransparent)
            {
                return (textureList, textures, name) =>
                {
                    bool hasTransparency = ModelImporter.ResolveTransparencyMode(textureList, textures)
                        is not ETransparencyMode.Opaque;
                    return hasTransparency
                        ? ModelImporter.MakeMaterialForwardPlusTextured(textureList, textures, name)
                        : baseAction(textureList, textures, name);
                };
            }

            return baseAction;
        }

        private static Matrix4x4? GetOptionalRootTransformMatrix(Settings.ModelImportSettings model)
        {
            if (model is null)
                return null;

            Matrix4x4 transform = Matrix4x4.Identity;

            if (model.YawPitchRoll is not null)
            {
                // JSON values are degrees; Quaternion APIs expect radians.
                var ypr = model.YawPitchRoll;
                var rot = Quaternion.CreateFromYawPitchRoll(
                    XRMath.DegToRad(ypr.Yaw),
                    XRMath.DegToRad(ypr.Pitch),
                    XRMath.DegToRad(ypr.Roll));

                transform *= Matrix4x4.CreateFromQuaternion(rot);
            }

            if (model.Translation is not null)
            {
                var translation = model.Translation;
                transform *= Matrix4x4.CreateTranslation(translation.X, translation.Y, translation.Z);
            }

            return transform == Matrix4x4.Identity ? null : transform;
        }

        private static FbxImportBackend ResolveFbxBackend(Settings.ModelImportSettings model)
            => model.ImporterBackend switch
            {
                ModelImportBackendPreference.AssimpOnly => FbxImportBackend.AssimpLegacy,
                _ => FbxImportBackend.Auto,
            };

        private static GltfImportBackend ResolveGltfBackend(Settings.ModelImportSettings model)
            => model.ImporterBackend switch
            {
                ModelImportBackendPreference.AssimpOnly => GltfImportBackend.AssimpLegacy,
                _ => GltfImportBackend.Auto,
            };

        internal static ModelImportOptions? CreateImportOptions(Settings.ModelImportSettings model)
        {
            bool splitSubmeshes = model.SplitSubmeshesIntoSeparateModelComponents
                || (model.Kind is UnitTestModelImportKind.Static && model.GenerateCoacdCollidersPerSubmesh);

            bool needsImportOptions = splitSubmeshes
                || model.ImporterBackend is ModelImportBackendPreference.AssimpOnly;

            if (!needsImportOptions)
                return null;

            return new ModelImportOptions
            {
                LegacyPostProcessSteps = model.ImportFlags,
                ScaleConversion = model.Scale,
                ZUp = model.ZUp,
                FbxBackend = ResolveFbxBackend(model),
                GltfBackend = ResolveGltfBackend(model),
                SplitSubmeshesIntoSeparateModelComponents = splitSubmeshes,
            };
        }

        private static void AttachAutoGeneratedStaticColliders(SceneNode rootNode)
        {
            int colliderCount = 0;
            rootNode.IterateComponents<ModelComponent>(component =>
            {
                // When multiple ModelComponents exist on one node (split import), each
                // StaticRigidBodyComponent must target its specific ModelComponent.
                var staticBody = component.SceneNode.AddComponent<StaticRigidBodyComponent>();
                if (staticBody is null)
                    return;

                staticBody.TargetModelComponent = component;
                staticBody.AutoGenerateConvexCollidersFromSiblingModel = true;
                colliderCount++;
            }, true);

            Debug.Out($"[StaticModel] Enabled auto-generated CoACD colliders for {colliderCount} imported model components under '{rootNode.Name}'.");
        }

        public static void ImportModels(string desktopDir, SceneNode rootNode, SceneNode characterParentNode)
        {
            if (Toggles.CreateUnitBox)
            {
                SceneNode boxNode = new(rootNode) { Name = "UnitBox" };
                ModelComponent boxComp = boxNode.AddComponent<ModelComponent>()!;
                var mesh = XRMesh.Shapes.SolidBox(new Vector3(-0.5f), new Vector3(0.5f), true, XRMesh.Shapes.ECubemapTextureUVs.None);
                var material = XRMaterial.CreateUnlitColorMaterialForward(ColorF4.Red);
                material.RenderOptions.CullMode = ECullMode.None;
                material.RenderPass = (int)EDefaultRenderPass.OpaqueForward;
                boxComp.Model = new Model([new SubMesh(mesh, material)
                {
                    CullingBounds = 
                        new AABB(new Vector3(-0.5f),
                        new Vector3(0.5f)),
                }]);
            }

            if (!Toggles.HasAnyModelsToImport)
                return;

            SceneNode? importedStaticModelsRootNode = null;
            object importedStaticRootsLock = new();
            var importedStaticRoots = new List<SceneNode>();

            // Count static models so we know when all imports have completed.
            int pendingStaticImports = 0;
            foreach (var m in Toggles.ModelsToImport)
            {
                if (m is not null && m.Enabled && !string.IsNullOrWhiteSpace(m.Path) && m.Kind is UnitTestModelImportKind.Static)
                    pendingStaticImports++;
            }
            int totalStaticImports = pendingStaticImports;

            foreach (var model in Toggles.ModelsToImport)
            {
                if (model is null || !model.Enabled || string.IsNullOrWhiteSpace(model.Path))
                    continue;

                string resolvedPath = ResolveModelPath(desktopDir, model.Path);
                if (!File.Exists(resolvedPath))
                {
                    Debug.LogWarning($"[UnitTestingWorld] Model file not found at '{resolvedPath}' (raw='{model.Path}')");
                    continue;
                }

                switch (model.Kind)
                {
                    case UnitTestModelImportKind.Animated:
                    {
                        SceneNode? ImportAnimated()
                        {
                            ModelImportOptions? importOptions = CreateImportOptions(model);
                            using var importer = new ModelImporter(resolvedPath, null, null);
                            importer.MakeMaterialAction = ResolveMakeMaterialAction(model);
                            importer.MakeTextureAction = CreateHardcodedTexture;
                            importer.ImportOptions = importOptions;
                                return importer.Import(
                                model.ImportFlags,
                                preservePivots: true,
                                removeAssimpFBXNodes: true,
                                scaleConversion: model.Scale,
                                zUp: model.ZUp,
                                multiThread: true,
                                rootTransformMatrix: GetOptionalRootTransformMatrix(model));
                        }

                            Task.Run(ImportAnimated).ContinueWith(nodeTask =>
                            {
                                if (nodeTask.IsCanceled)
                                {
                                    Debug.LogWarning($"[AnimatedModel] Import was canceled: {resolvedPath}");
                                    return;
                                }

                                if (nodeTask.IsFaulted)
                                {
                                    Debug.LogException(nodeTask.Exception?.GetBaseException() ?? new InvalidOperationException("Animated model import failed without an exception."), $"[AnimatedModel] Failed to import animated model: {resolvedPath}");
                                    return;
                                }

                                SceneNode? importedNode = nodeTask.Result;
                                _ = Engine.InvokeOnMainThread(() =>
                                {
                                    if (characterParentNode != null && importedNode != null && importedNode.Transform.Parent != characterParentNode.Transform)
                                        characterParentNode.Transform.AddChild(importedNode.Transform, false, EParentAssignmentMode.Immediate);

                                    OnFinishedImportingAvatar(importedNode, characterParentNode);
                                }, $"UnitTestingWorld: Finish animated avatar import '{Path.GetFileName(resolvedPath)}'", executeNowIfAlreadyMainThread: true);
                            });
                        break;
                    }
                    case UnitTestModelImportKind.Static:
                    default:
                    {
                        importedStaticModelsRootNode ??= new SceneNode(rootNode) { Name = "Static Model Root", Layer = DefaultLayers.StaticIndex };
                        ModelImporter.DelMakeMaterialAction makeMaterialAction = ResolveMakeMaterialAction(model);
                        ModelImportOptions? importOptions = CreateImportOptions(model);

                        // Capture the root node ref for the closure below.
                        SceneNode staticRoot = importedStaticModelsRootNode;

                        _ = ModelImporter.ScheduleImportJob(
                            resolvedPath,
                            model.ImportFlags,
                            onFinished: result =>
                            {
                                if (result.RootNode is null)
                                    Debug.LogWarning($"[StaticModel] Import finished but RootNode is null: {resolvedPath}");
                                else
                                {
                                    if (model.GenerateCoacdCollidersPerSubmesh)
                                        AttachAutoGeneratedStaticColliders(result.RootNode);
                                    lock (importedStaticRootsLock)
                                        importedStaticRoots.Add(result.RootNode);
                                    Debug.Out($"[StaticModel] Import completed: {resolvedPath} ({result.Meshes.Count} meshes, {result.Materials.Count} materials)");
                                }

                                if (Interlocked.Decrement(ref pendingStaticImports) == 0)
                                    QueueLightProbeSpawnerModelBoundsWiring(rootNode, importedStaticRootsLock, importedStaticRoots);
                            },
                            onError: ex =>
                            {
                                Debug.LogException(ex, $"[StaticModel] Failed to import static model: {resolvedPath}");
                                if (Interlocked.Decrement(ref pendingStaticImports) == 0)
                                    QueueLightProbeSpawnerModelBoundsWiring(rootNode, importedStaticRootsLock, importedStaticRoots);
                            },
                            onCanceled: () =>
                            {
                                Debug.LogWarning($"[StaticModel] Import was canceled: {resolvedPath}");
                                if (Interlocked.Decrement(ref pendingStaticImports) == 0)
                                    QueueLightProbeSpawnerModelBoundsWiring(rootNode, importedStaticRootsLock, importedStaticRoots);
                            },
                            onProgress: progress => Debug.Out($"[StaticModel] Progress ({Path.GetFileName(resolvedPath)}): {progress:P0}"),
                            cancellationToken: default,
                            parent: importedStaticModelsRootNode,
                            scaleConversion: model.Scale,
                            zUp: model.ZUp,
                            rootTransformMatrix: GetOptionalRootTransformMatrix(model),
                            materialFactory: null,
                            makeMaterialAction: makeMaterialAction,
                            importOptions: importOptions,
                            layer: DefaultLayers.StaticIndex);

                        break;
                    }
                }
            }
        }

        private static void QueueLightProbeSpawnerModelBoundsWiring(SceneNode rootNode, object importedStaticRootsLock, List<SceneNode> importedStaticRoots)
        {
            Engine.InvokeOnAppThread(() =>
            {
                SceneNode[] importedRoots;
                lock (importedStaticRootsLock)
                    importedRoots = [.. importedStaticRoots];

                WireLightProbeSpawnerToImportedModels(rootNode, importedRoots);
            }, "UnitTestingWorld.Models.QueueLightProbeSpawnerModelBoundsWiring", executeNowIfAlreadyAppThread: true);
        }

        /// <summary>
        /// Called once all static model imports have completed. Finds the light probe grid spawner
        /// in the scene tree and sets its <see cref="LightProbeGridSpawnerComponent.PlacementBoundsModels"/>
        /// to the imported <see cref="ModelComponent"/> instances so probes fill the models' combined volume.
        /// </summary>
        private static void WireLightProbeSpawnerToImportedModels(SceneNode rootNode, SceneNode[] importedStaticRoots)
        {
            var spawners = rootNode.FindAllDescendantComponents<LightProbeGridSpawnerComponent>();
            if (spawners.Length == 0)
            {
                Debug.Out("[LightProbeGrid] No LightProbeGridSpawnerComponent found — skipping model-bounds wiring.");
                return;
            }

            var models = new List<ModelComponent>();
            foreach (SceneNode importedRoot in importedStaticRoots)
                importedRoot.IterateComponents<ModelComponent>(m => models.Add(m), iterateChildHierarchy: true);

            if (models.Count == 0)
            {
                Debug.Out("[LightProbeGrid] No ModelComponents found under imported static models — skipping model-bounds wiring.");
                return;
            }

            ModelComponent[] modelsArray = [.. models];
            foreach (var spawner in spawners)
            {
                if (!spawner.UsePlacementBoundsModels)
                    continue;

                spawner.ConfigurePlacementBoundsModels(modelsArray, enabled: true);
                Debug.Out($"[LightProbeGrid] Wired {modelsArray.Length} imported ModelComponents as placement bounds for '{spawner.Name}'.");
            }
        }

        private static string ResolveModelPath(string desktopDir, string rawPath)
        {
            if (Path.IsPathRooted(rawPath))
                return rawPath;

            string candidate = Path.Combine(desktopDir, rawPath);
            if (File.Exists(candidate))
                return candidate;

            candidate = Path.Combine(Engine.Assets.EngineAssetsPath, rawPath);
            if (File.Exists(candidate))
                return candidate;

            // Convenience for the common "Models/..." layout under engine assets.
            if (!rawPath.StartsWith("Models\\", StringComparison.OrdinalIgnoreCase) &&
                !rawPath.StartsWith("Models/", StringComparison.OrdinalIgnoreCase))
            {
                candidate = Path.Combine(Engine.Assets.EngineAssetsPath, "Models", rawPath);
                if (File.Exists(candidate))
                    return candidate;
            }

            return candidate;
        }

        private static string ResolveUnitTestAssetPath(string desktopDir, string rawPath)
        {
            if (Path.IsPathRooted(rawPath))
                return rawPath;

            rawPath = rawPath.Replace('/', Path.DirectorySeparatorChar);
            string cwd = Environment.CurrentDirectory;

            // Mirrors how Rive loads assets: treat names as relative to the current working directory.
            // The editor is usually launched with cwd = 'XREngine.Editor' (see Start-Editor.bat).
            string candidate = Path.Combine(cwd, rawPath);
            if (File.Exists(candidate))
                return candidate;

            // Support repo-relative paths like 'XREngine.Editor\\Assets\\...'
            // when cwd already *is* 'XREngine.Editor'.
            if (string.Equals(Path.GetFileName(cwd), "XREngine.Editor", StringComparison.OrdinalIgnoreCase))
            {
                const string prefix = "XREngine.Editor\\";
                if (rawPath.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    candidate = Path.Combine(cwd, rawPath[prefix.Length..]);
                    if (File.Exists(candidate))
                        return candidate;
                }
            }

            // Common caller convenience: allow paths relative to the editor's Assets folder.
            candidate = Path.Combine(cwd, "Assets", rawPath);
            if (File.Exists(candidate))
                return candidate;

            // Also try repo root (parent of XREngine.Editor) for repo-relative paths.
            var parent = Directory.GetParent(cwd);
            if (parent is not null)
            {
                candidate = Path.Combine(parent.FullName, rawPath);
                if (File.Exists(candidate))
                    return candidate;

                candidate = Path.Combine(parent.FullName, "XREngine.Editor", rawPath);
                if (File.Exists(candidate))
                    return candidate;
            }

            candidate = Path.Combine(desktopDir, rawPath);
            if (File.Exists(candidate))
                return candidate;

            candidate = Path.Combine(Engine.Assets.GameAssetsPath, rawPath);
            if (File.Exists(candidate))
                return candidate;

            candidate = Path.Combine(Engine.Assets.EngineAssetsPath, rawPath);
            if (File.Exists(candidate))
                return candidate;

            return Path.GetFullPath(candidate);
        }

        private static string ResolveUnitTestArtifactPath(string rawPath)
        {
            if (Path.IsPathRooted(rawPath))
                return rawPath;

            rawPath = rawPath.Replace('/', Path.DirectorySeparatorChar);
            string cwd = Environment.CurrentDirectory;
            string baseDir = string.Equals(Path.GetFileName(cwd), "XREngine.Editor", StringComparison.OrdinalIgnoreCase)
                ? Directory.GetParent(cwd)?.FullName ?? cwd
                : cwd;

            return Path.GetFullPath(Path.Combine(baseDir, rawPath));
        }

        public static void AddSkybox(SceneNode rootNode, XRTexture2D? skyEquirect)
        {
            var skybox = new SceneNode(rootNode) { Name = "TestSkyboxNode" };
            if (!skybox.TryAddComponent<SkyboxComponent>(out var skyboxComp))
                return;

            skyboxComp!.Name = "TestSkybox";
            skyboxComp.Intensity = 1.0f;

            if (skyEquirect is null)
            {
                skyboxComp.Mode = ESkyboxMode.Gradient;
            }
            else
            {
                skyboxComp.Mode = ESkyboxMode.Texture;
                skyboxComp.Projection = ESkyboxProjection.Equirectangular;
                skyboxComp.Texture = skyEquirect;
            }
        }

        private static void OnFinishedAvatarAsync(Task<(SceneNode? rootNode, IReadOnlyCollection<XRMaterial> materials, IReadOnlyCollection<XRMesh> meshes)> task)
        {
            if (task.IsCanceled || task.IsFaulted)
                return;

            (SceneNode? rootNode, IReadOnlyCollection<XRMaterial> materials, IReadOnlyCollection<XRMesh> meshes) = task.Result;
            OnFinishedImportingAvatar(rootNode);
        }

        private sealed class AvatarStartupClipLoadResult
        {
            public AnimationClip? VmdClip { get; init; }
            public AnimationClip? AnimClip { get; init; }
            public string? AnimClipPath { get; init; }
            public bool AnimClipFileExists { get; init; }
            public bool RunPoseAudit { get; init; }
        }

        public static void OnFinishedImportingAvatar(SceneNode? rootNode)
            => OnFinishedImportingAvatar(rootNode, characterParentNode: null);

        private static AvatarStartupClipLoadResult? LoadAvatarStartupClips()
        {
            if (!Toggles.AnimationClipVMD && !Toggles.AnimationClipAnim)
                return null;

            var desktopDir = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);

            AnimationClip? vmdClip = null;
            if (Toggles.AnimationClipVMD)
                vmdClip = Engine.Assets.Load<AnimationClip>(Path.Combine(desktopDir, "test.vmd"));

            string? animClipPath = null;
            bool animClipFileExists = false;
            AnimationClip? animClip = null;
            if (Toggles.AnimationClipAnim)
            {
                animClipPath = ResolveUnitTestAssetPath(desktopDir, Toggles.AnimClipPath);
                animClipFileExists = File.Exists(animClipPath);
                if (animClipFileExists)
                    animClip = Engine.Assets.Load<AnimationClip>(animClipPath);
            }

            return new AvatarStartupClipLoadResult
            {
                VmdClip = vmdClip,
                AnimClip = animClip,
                AnimClipPath = animClipPath,
                AnimClipFileExists = animClipFileExists,
                RunPoseAudit = Toggles.HumanoidPoseAuditEnabled || !string.IsNullOrWhiteSpace(Toggles.HumanoidPoseAuditReferencePath),
            };
        }

        public static void OnFinishedImportingAvatar(SceneNode? rootNode, SceneNode? characterParentNode)
            => OnFinishedImportingAvatar(rootNode, characterParentNode, startupClips: null);

        private static void OnFinishedImportingAvatar(SceneNode? rootNode, SceneNode? characterParentNode, AvatarStartupClipLoadResult? startupClips)
        {
            if (rootNode is null)
                return;

            //Debug.Out(rootNode.PrintTree());

            var humanComp = rootNode.AddComponent<HumanoidComponent>()!;

            var animator = rootNode.AddComponent<AnimStateMachineComponent>()!;

            // VRHeightScaleComponent depends on VRState. For desktop locomotion we just scale once to fit the capsule.
            HeightScaleBaseComponent? heightScale = null;
            if (Toggles.VRPawn)
                heightScale = rootNode.AddComponent<VRHeightScaleComponent>()!;
            else
            {
                var desktopHeightScale = rootNode.AddComponent<HeightScaleComponent>()!;
                heightScale = desktopHeightScale;
                TryScaleAvatarToFitDesktopCapsule(rootNode, humanComp, desktopHeightScale, characterParentNode);
            }
            
            if (Toggles.FaceTracking)
            {
                const string vrcftPrefix = "/avatar/parameters/";
                var ftOscReceiver = rootNode.AddComponent<FaceTrackingReceiverComponent>()!;
                ftOscReceiver.ParameterPrefix = vrcftPrefix;
                ftOscReceiver.GenerateARKitStateMachine();

                var ftOscSender = rootNode.AddComponent<OscSenderComponent>()!;
                ftOscSender.ParameterPrefix = vrcftPrefix;

                /// <summary>
                /// Called when a variable changes in a state machine.
                /// </summary>
                /// <param name="variable"></param>
                void StateMachineVariableChanged(AnimVar variable)
                {
                    string address = variable.ParameterName;
                    switch (variable)
                    {
                        case AnimFloat f:
                            ftOscSender.Send(address, f.Value);
                            break;
                        case AnimInt i:
                            ftOscSender.Send(address, i.Value);
                            break;
                        case AnimBool b:
                            ftOscSender.Send(address, b.Value);
                            break;
                    }
                }

                animator!.StateMachine.VariableChanged += StateMachineVariableChanged;
            }

            VRIKSolverComponent? vrIKSolver = null;
            if (Toggles.AddCharacterIK)
            {
                if (!Toggles.VRPawn)
                {
                    var humanik = rootNode.AddComponent<HumanoidIKSolverComponent>()!;

                    humanik.SetIKPositionWeight(ELimbEndEffector.LeftHand, 1.0f);
                    humanik.SetIKRotationWeight(ELimbEndEffector.LeftHand, 1.0f);

                    humanik.SetIKPositionWeight(ELimbEndEffector.RightHand, 1.0f);
                    humanik.SetIKRotationWeight(ELimbEndEffector.RightHand, 1.0f);

                    humanik.SetIKPositionWeight(ELimbEndEffector.LeftFoot, 1.0f);
                    humanik.SetIKRotationWeight(ELimbEndEffector.LeftFoot, 1.0f);

                    humanik.SetIKPositionWeight(ELimbEndEffector.RightFoot, 1.0f);
                    humanik.SetIKRotationWeight(ELimbEndEffector.RightFoot, 1.0f);

                    humanik.SetSpineWeight(0.0f);

                    SceneNode leftFootIkTargetNode = rootNode.NewChild("LeftFootIKTargetNode");
                    var leftFootTfm = humanComp.Left.Foot.Node!.GetTransformAs<Transform>(true)!;
                    leftFootIkTargetNode.GetTransformAs<Transform>(true)!.SetFrameState(new TransformState()
                    {
                        Order = ETransformOrder.TRS,
                        Rotation = leftFootTfm.WorldRotation,
                        Scale = new Vector3(1.0f),
                        Translation = leftFootTfm.WorldTranslation
                    });

                    SceneNode rightFootIkTargetNode = rootNode.NewChild("RightFootIKTargetNode");
                    var rightFootTfm = humanComp.Right.Foot.Node!.GetTransformAs<Transform>(true)!;
                    rightFootIkTargetNode.GetTransformAs<Transform>(true)!.SetFrameState(new TransformState()
                    {
                        Order = ETransformOrder.TRS,
                        Rotation = rightFootTfm.WorldRotation,
                        Scale = new Vector3(1.0f),
                        Translation = rightFootTfm.WorldTranslation
                    });

                    SceneNode leftHandIkTargetNode = rootNode.NewChild("LeftHandIKTargetNode");
                    var leftHandTfm = humanComp.Left.Wrist.Node!.GetTransformAs<Transform>(true)!;
                    leftHandIkTargetNode.GetTransformAs<Transform>(true)!.SetFrameState(new TransformState()
                    {
                        Order = ETransformOrder.TRS,
                        Rotation = leftHandTfm.WorldRotation,
                        Scale = new Vector3(1.0f),
                        Translation = leftHandTfm.WorldTranslation
                    });

                    SceneNode rightHandIkTargetNode = rootNode.NewChild("RightHandIKTargetNode");
                    var rightHandTfm = humanComp.Right.Wrist.Node!.GetTransformAs<Transform>(true)!;
                    rightHandIkTargetNode.GetTransformAs<Transform>(true)!.SetFrameState(new TransformState()
                    {
                        Order = ETransformOrder.TRS,
                        Rotation = rightHandTfm.WorldRotation,
                        Scale = new Vector3(1.0f),
                        Translation = rightHandTfm.WorldTranslation
                    });

                    humanik.GetGoalIK(ELimbEndEffector.LeftFoot)!.TargetIKTransform = leftFootIkTargetNode.Transform;
                    humanik.GetGoalIK(ELimbEndEffector.RightFoot)!.TargetIKTransform = rightFootIkTargetNode.Transform;
                    humanik.GetGoalIK(ELimbEndEffector.LeftHand)!.TargetIKTransform = leftHandIkTargetNode.Transform;
                    humanik.GetGoalIK(ELimbEndEffector.RightHand)!.TargetIKTransform = rightHandIkTargetNode.Transform;
                    UserInterface.EnableTransformToolForNode(leftFootIkTargetNode);
                    UserInterface.EnableTransformToolForNode(rightFootIkTargetNode);
                    UserInterface.EnableTransformToolForNode(leftHandIkTargetNode);
                    UserInterface.EnableTransformToolForNode(rightHandIkTargetNode);
                    Selection.SceneNode = leftFootIkTargetNode;
                }
                else
                {
                    var vrik = rootNode.AddComponent<VRIKSolverComponent>()!;
                    vrik.IsActive = false;
                    vrIKSolver = vrik;
                    //rootNode.AddComponent<VRIKRootControllerComponent>();
                    //vrik.GuessHandOrientations();
                }
            }

            //TODO: only remove the head in VR
            //if (Toggles.VRPawn || !Toggles.ThirdPersonPawn)
            //{
            //    var headTfm = humanComp.Head?.Node?.GetTransformAs<Transform>();
            //    if (headTfm is not null)
            //        headTfm.Scale = Vector3.Zero;
            //}

            if (Toggles.Locomotion)
                Pawns.InitializeLocomotion(rootNode, humanComp, heightScale, vrIKSolver);
            
            if (Toggles.TestAnimation)
            {
                var knee = humanComp!.Right.Knee?.Node?.Transform;
                var leg = humanComp!.Right.Leg?.Node?.Transform;

                leg?.RegisterAnimationTick<Transform>(t => t.Rotation = Quaternion.CreateFromAxisAngle(Globals.Right, XRMath.DegToRad(180 - 90.0f * (MathF.Cos(Engine.ElapsedTime) * 0.5f + 0.5f))));
                knee?.RegisterAnimationTick<Transform>(t => t.Rotation = Quaternion.CreateFromAxisAngle(Globals.Right, XRMath.DegToRad(90.0f * (MathF.Cos(Engine.ElapsedTime) * 0.5f + 0.5f))));

                //var rootTfm = rootNode.FirstChild.GetTransformAs<Transform>(true)!;
                ////rotate the root node in a circle, but still facing forward
                //rootTfm.RegisterAnimationTick<Transform>(t =>
                //{
                //    t.Translation = new Vector3(0, MathF.Sin(Engine.ElapsedTime), 0);
                //});

                //For testing blendshape morphing
                //Technically we should only register animation tick on scene node if any lods have blendshapes,
                //but at this point the model's meshes are still loading. So we'll just be lazy and check in the animation tick since it's just for testing.
                rootNode.IterateComponents<ModelComponent>(comp =>
                {
                    comp.SceneNode.RegisterAnimationTick<SceneNode>(t =>
                    {
                        var renderers = comp.Meshes.SelectMany(x => x.LODs).Select(x => x.Renderer).Where(x => x?.Mesh?.HasBlendshapes ?? false);
                        foreach (var renderer in renderers)
                        {
                            //for (int r = 0; r < xrMesh!.BlendshapeCount; r++)
                            int r = 0;
                            renderer?.SetBlendshapeWeightNormalized((uint)r, MathF.Sin(Engine.ElapsedTime) * 0.5f + 0.5f);
                        }
                    });
                }, true);
            }

            if (Toggles.PhysicsChain)
                CreateHardcodedPhysicsChains(humanComp);
            
            if (Toggles.TransformTool)
            {
                //Show the transform tool for testing
                var root = humanComp!.SceneNode;
                if (root is null)
                    return;

                UserInterface.EnableTransformToolForNode(root);
            }

            if (Toggles.VMC)
            {
                var vmc = rootNode.AddComponent<VMCCaptureComponent>()!;
                vmc.Humanoid = humanComp;
            }

            if (Toggles.FaceMotion3D)
            {
                var face = rootNode.AddComponent<FaceMotion3DCaptureComponent>()!;
                face.Humanoid = humanComp;
                //deactivate glasses node
                var glasses = humanComp.SceneNode?.FindDescendant(x => x.Name?.Contains("glasses", StringComparison.InvariantCultureIgnoreCase) ?? false);
                glasses?.IsActiveSelf = false;
            }

            OVRLipSyncComponent? lipSync = null;
            if (Toggles.AttachMicToAnimatedModel)
            {
                var headNode = humanComp!.Head?.Node?.Transform?.SceneNode;
                if (headNode is not null)
                    Audio.AttachMicTo(headNode, out _, out _, out lipSync);
            }
            else if (Toggles.LipSync)
                lipSync = (Engine.State.MainPlayer?.ControlledPawnComponent as PawnComponent)?.SceneNode?.GetComponent<OVRLipSyncComponent>();

            if (lipSync is not null)
            {
                var face = rootNode.FindDescendantByName("Face", StringComparison.InvariantCultureIgnoreCase);
                if (face is not null)
                {
                    if (face.TryGetComponent<ModelComponent>(out var comp))
                        lipSync.ModelComponent = comp;
                    else
                    {
                        face.ComponentAdded += SetModel;
                        void SetModel((SceneNode node, XRComponent comp) x)
                        {
                            if (x.comp is ModelComponent model)
                                lipSync.ModelComponent = model;
                            face.ComponentAdded -= SetModel;
                        }
                    }
                }
            }

            if (startupClips is not null)
                AttachAvatarStartupClips(rootNode, humanComp, startupClips);
            else
                QueueAvatarStartupClipAttachment(rootNode);
        }

        private static void QueueAvatarStartupClipAttachment(SceneNode rootNode)
        {
            if (!Toggles.AnimationClipVMD && !Toggles.AnimationClipAnim)
                return;

            Task.Run(LoadAvatarStartupClips).ContinueWith(loadTask =>
            {
                if (loadTask.IsCanceled)
                {
                    Debug.LogWarning("[UnitTestingWorld] Avatar startup clip load was canceled.");
                    return;
                }

                if (loadTask.IsFaulted)
                {
                    Debug.LogException(loadTask.Exception?.GetBaseException() ?? new InvalidOperationException("Avatar startup clip load failed without an exception."), "[UnitTestingWorld] Failed to load avatar startup clips.");
                    return;
                }

                AvatarStartupClipLoadResult? startupClips = loadTask.Result;
                if (startupClips is null)
                    return;

                _ = Engine.InvokeOnMainThread(() =>
                {
                    if (!rootNode.TryGetComponent<HumanoidComponent>(out var humanComp) || humanComp is null)
                        return;

                    AttachAvatarStartupClips(rootNode, humanComp, startupClips);
                }, $"UnitTestingWorld: Attach startup clips to '{rootNode.Name}'", executeNowIfAlreadyMainThread: true);
            });
        }

        private static void AttachAvatarStartupClips(SceneNode rootNode, HumanoidComponent humanComp, AvatarStartupClipLoadResult startupClips)
        {
            if (startupClips.VmdClip is AnimationClip vmdClip)
            {
                vmdClip.Looped = true;

                var anim = rootNode.AddComponent<AnimationClipComponent>()!;
                anim.StartOnActivate = true;
                anim.Animation = vmdClip;
            }

            if (!Toggles.AnimationClipAnim)
                return;

            if (!startupClips.AnimClipFileExists)
            {
                string resolvedPath = startupClips.AnimClipPath ?? Toggles.AnimClipPath;
                Debug.LogWarning($"[UnitTestingWorld] .anim clip not found at '{resolvedPath}' (raw='{Toggles.AnimClipPath}')");
                return;
            }

            if (startupClips.AnimClip is not AnimationClip clip)
                return;

            clip.Looped = Toggles.AnimLooped;

            bool runPoseAudit = startupClips.RunPoseAudit;

            var animClipComponent = rootNode.AddComponent<AnimationClipComponent>()!;
            animClipComponent.StartOnActivate = true;
            animClipComponent.Animation = clip;

            if (clip.ClipKind == EAnimationClipKind.UnityHumanoidMuscle && !runPoseAudit)
            {
                Debug.LogWarning($"[UnitTestingWorld] Loaded Unity humanoid clip '{clip.Name}' and started playback. Raw .anim humanoid curves still do not fully match Unity HumanPose semantics; enable HumanoidPoseAudit* settings if you need to compare that path precisely.");
            }

            if (clip.ClipKind == EAnimationClipKind.UnityHumanoidMuscle
                && rootNode.TryGetComponent<HumanoidIKSolverComponent>(out var humanoidIK)
                && humanoidIK is not null)
            {
                humanoidIK.IsActive = false;
                Debug.Out($"[UnitTestingWorld] Disabled HumanoidIKSolverComponent for humanoid clip '{clip.Name}' to inspect raw muscle playback.");
            }

            if (!runPoseAudit)
                return;

            var desktopDir = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
            var audit = rootNode.AddComponent<HumanoidPoseAuditComponent>()!;
            audit.TargetClipComponent = animClipComponent;
            audit.TargetHumanoid = humanComp;
            audit.OutputPath = ResolveUnitTestArtifactPath(Toggles.HumanoidPoseAuditOutputPath);
            audit.ReferencePath = string.IsNullOrWhiteSpace(Toggles.HumanoidPoseAuditReferencePath)
                ? null
                : ResolveUnitTestAssetPath(desktopDir, Toggles.HumanoidPoseAuditReferencePath);
            audit.ComparisonOutputPath = string.IsNullOrWhiteSpace(Toggles.HumanoidPoseAuditComparisonOutputPath)
                ? null
                : ResolveUnitTestArtifactPath(Toggles.HumanoidPoseAuditComparisonOutputPath);
            audit.SampleRateOverride = Toggles.HumanoidPoseAuditSampleRateOverride ?? 0;

            Debug.Out($"[UnitTestingWorld] Enabled humanoid pose audit export for clip '{clip.Name}' -> '{audit.OutputPath}'.");
        }

        private static void TryScaleAvatarToFitDesktopCapsule(
            SceneNode avatarRoot,
            HumanoidComponent humanoid,
            HeightScaleComponent heightScale,
            SceneNode? characterParentNode)
        {
            // Determine the character capsule dimensions from the desktop character movement component.
            var characterNode = characterParentNode?.Parent;
            var movement = characterNode?.GetComponent<CharacterMovement3DComponent>();
            if (movement is null)
                return;

            // Measure model height in bind space using the humanoid head vs root, similar to VRHeightScaleComponent.MeasureAvatarHeight.
            var headNode = humanoid.Head.Node;
            if (headNode is null)
                return;

            float headY = headNode.Transform.BindMatrix.Translation.Y;
            float rootY = humanoid.SceneNode.Transform.BindMatrix.Translation.Y;
            float modelHeight = headY - rootY;
            if (!float.IsFinite(modelHeight) || modelHeight <= 0.001f)
                return;

            float capsuleOuterHeight = movement.CurrentHeight + 2.0f * (movement.Radius + movement.ContactOffset);
            if (!float.IsFinite(capsuleOuterHeight) || capsuleOuterHeight <= 0.001f)
                return;

            // Use the HeightScaleComponent that was just added to apply measured height + a single uniform scale.
            // Keep the desktop character capsule as the source of truth: only scale down (never up) to fit.
            float rawRatio = capsuleOuterHeight / modelHeight;
            if (!float.IsFinite(rawRatio) || rawRatio <= 0.0f)
                return;
            float ratio = MathF.Min(1.0f, rawRatio);

            // Ensure the component has what it needs without letting it resize the character capsule.
            heightScale.HumanoidComponent = humanoid;
            heightScale.CharacterMovementComponent = null;

            heightScale.ApplyMeasuredHeight(modelHeight);
            heightScale.RealWorldHeightRatio = ratio;
        }

        #region Hardcoded stuff, varies per model
        private static void CreateHardcodedPhysicsChains(HumanoidComponent humanComp)
        {
            //Add physics chain to the breast bone
            var chest = humanComp!.Chest?.Node?.Transform;
            //Find breast bone
            if (chest is not null)
            {
                var earR = chest.FindDescendant(x =>
                    (x.Name?.Contains("KittenEarR", StringComparison.InvariantCultureIgnoreCase) ?? false));
                if (earR?.SceneNode is not null)
                {
                    var phys = earR.SceneNode.AddComponent<PhysicsChainComponent>()!;
                    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Default;
                    phys.UpdateRate = 60;
                    phys.Damping = 0.1f;
                    phys.Inert = 0.0f;
                    phys.Stiffness = 0.05f;
                    //phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                    phys.Elasticity = 0.2f;
                    phys.Multithread = false;
                }

                var earL = chest.FindDescendant(x =>
                    (x.Name?.Contains("KittenEarL", StringComparison.InvariantCultureIgnoreCase) ?? false));
                if (earL?.SceneNode is not null)
                {
                    var phys = earL.SceneNode.AddComponent<PhysicsChainComponent>()!;
                    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Default;
                    phys.UpdateRate = 60;
                    phys.Damping = 0.1f;
                    phys.Inert = 0.0f;
                    phys.Stiffness = 0.05f;
                    //phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                    phys.Elasticity = 0.2f;
                    phys.Multithread = false;
                }

                var breastL = chest.FindDescendant(x =>
                    (x.Name?.Contains("BreastUpper2_LRoot", StringComparison.InvariantCultureIgnoreCase) ?? false) ||
                    (x.Name?.Contains("Boob.L", StringComparison.InvariantCultureIgnoreCase) ?? false));
                if (breastL?.SceneNode is not null)
                {
                    var phys = breastL.SceneNode.AddComponent<PhysicsChainComponent>()!;
                    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Default;
                    phys.UpdateRate = 60;
                    phys.Damping = 0.1f;
                    phys.Inert = 0.0f;
                    phys.Stiffness = 0.05f;
                    //phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                    phys.Elasticity = 0.2f;
                    phys.Multithread = false;
                }

                var breastR = chest.FindDescendant(x =>
                    (x.Name?.Contains("BreastUpper2_RRoot", StringComparison.InvariantCultureIgnoreCase) ?? false) ||
                    (x.Name?.Contains("Boob.R", StringComparison.InvariantCultureIgnoreCase) ?? false));
                if (breastR?.SceneNode is not null)
                {
                    var phys = breastR.SceneNode.AddComponent<PhysicsChainComponent>()!;
                    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Default;
                    phys.UpdateRate = 60;
                    phys.Damping = 0.1f;
                    phys.Inert = 0.0f;
                    phys.Stiffness = 0.05f;
                    //phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                    phys.Elasticity = 0.2f;
                    phys.Multithread = false;
                }

                //var breastCenter = chest.FindChild(x => (x.Name?.Contains("Boob_Root", StringComparison.InvariantCultureIgnoreCase) ?? false));
                //if (breastCenter?.SceneNode is not null)
                //{
                //    var phys = breastCenter.SceneNode.AddComponent<PhysicsChainComponent>()!;
                //    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Normal;
                //    phys.UpdateRate = 60;
                //    phys.Damping = 0.1f;
                //    phys.Inert = 0.0f;
                //    phys.Stiffness = 0.05f;
                //    phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                //    phys.Elasticity = 0.2f;
                //    phys.Multithread = false;
                //}

                var tail = humanComp.Hips?.Node?.Transform.FindDescendant(x =>
                    x.Name?.Contains("Hair_1_2", StringComparison.InvariantCultureIgnoreCase) ?? false);
                if (tail?.SceneNode is not null)
                {
                    var phys = tail.SceneNode.AddComponent<PhysicsChainComponent>()!;
                    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Default;
                    phys.UpdateRate = 60;
                    phys.Damping = 0.1f;
                    phys.Inert = 0.5f;
                    phys.Stiffness = 0.05f;
                    phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                    phys.Gravity = new Vector3(0.0f, -0.1f, 0.0f);
                    phys.Elasticity = 0.01f;
                    phys.Multithread = false;
                }

                //var longHair = humanComp.Head?.Node?.Transform.FindDescendant(x =>
                //    x.Name?.Contains("Long Hair", StringComparison.InvariantCultureIgnoreCase) ?? false);
                //if (longHair?.SceneNode is not null)
                //{
                //    //longHair.SceneNode.IsActiveSelf = false;
                //    var phys = longHair.SceneNode.AddComponent<PhysicsChainComponent>()!;
                //    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.Normal;
                //    phys.UpdateRate = 60;
                //    phys.Damping = 0.1f;
                //    phys.Inert = 0.0f;
                //    phys.Stiffness = 0.05f;
                //    phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                //    phys.Elasticity = 0.2f;
                //}

                //var zafHair = humanComp.Head?.Node?.Transform.FindChild(x => x.Name?.Contains("Zaf Hair", StringComparison.InvariantCultureIgnoreCase) ?? false);
                //if (zafHair?.SceneNode is not null)
                //{
                //    var phys = zafHair.SceneNode.AddComponent<PhysicsChainComponent>()!;
                //    phys.UpdateMode = PhysicsChainComponent.EUpdateMode.FixedUpdate;
                //    phys.UpdateRate = 60;
                //    phys.Damping = 0.01f;
                //    phys.Inert = 0.0f;
                //    phys.Stiffness = 0.01f;
                //    phys.Force = new Vector3(0.0f, 0.0f, 0.0f);
                //    phys.Elasticity = 0.1f;
                //}
            }
        }

        //Hardcoded materials for testing until UI
        public static void CreateHardcodedMaterial(XRMaterial mat, XRTexture[] textureList, List<TextureSlot> textures, string name)
        {
            //Debug.Out($"Making material for {name}: {string.Join(", ", textureList.Select(x => x?.Name ?? "<missing name>"))}");

            // Clear current shader list
            mat.Shaders.Clear();

            XRShader color = ShaderHelper.LitColorFragDeferred()!;
            XRShader albedo = ShaderHelper.LitTextureFragDeferred()!;
            XRShader albedoNormal = ShaderHelper.LitTextureNormalFragDeferred()!;
            XRShader albedoNormalMetallic = ShaderHelper.LitTextureNormalMetallicFragDeferred()!;
            XRShader albedoMetallic = ShaderHelper.LitTextureMetallicFragDeferred()!;
            XRShader albedoNormalRoughnessMetallic = ShaderHelper.LitTextureNormalRoughnessMetallicDeferred()!;
            XRShader albedoRoughness = ShaderHelper.LitTextureRoughnessFragDeferred()!;
            XRShader albedoMatcap = ShaderHelper.LitTextureMatcapDeferred()!;
            XRShader albedoEmissive = ShaderHelper.LitTextureEmissiveDeferred();

            switch (name)
            {
                //case "Boots": // "BaseColor, Roughness, BaseColor, , Roughness"
                //              //textureList[0].Load3rdParty();
                //    mat.Shaders.Add(albedoRoughness);
                //    mat.Textures =
                //    [
                //        textureList[0],
                //    textureList[1],
                //];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Metal": // "T_MainTex_D, T_MainTex_D"
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    mat.SetVector3("BaseColor", new Vector3(0.6f));
                //    mat.SetFloat("Roughness", 0.5f);
                //    mat.SetFloat("Metallic", 1.0f);
                //    mat.SetFloat("Specular", 1.0f);
                //    break;

                //case "BackHair": // "HairEarTail Texture, HairEarTail Texture"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures =
                //    [
                //        textureList[0],
                //];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Goth_Bunny_Straps": // "Arm matcaps, Arm matcaps"
                //    mat.Shaders.Add(albedoMatcap);
                //    mat.Textures =
                //    [
                //        textureList.TryGet(0),
                //];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "black_1": // "T_MainTex_D, T_MainTex_D, "
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Ears": // "ears emiss, ears emiss"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures =
                //    [
                //        textureList[0],
                //];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Material #130": // no textures provided
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Material #132": // "BLACK, NORMAL, METALIC, Regular_Roughness"
                //    mat.Shaders.Add(albedoNormalRoughnessMetallic);
                //    mat.Textures =
                //    [
                //        textureList[0],
                //    textureList[1],
                //    textureList[2],
                //    textureList[3],
                //];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "1": // "No Saturation 06 (1), No Saturation 06 (1)
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "2": // "61, 61"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Goth_Bunny_Thigh_Highs": // "generator5, generator5"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "LEFT_EYE": // "Eye_5, left eye by nanna, Eye_5"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Back_hair": // "Hair1, hairglow-mono_emission, Hair1"
                //    mat.Shaders.Add(albedoEmissive);
                //    mat.Textures = [textureList[0], textureList[1]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "New_002": // "lis_dlcu_029_02_base_PP1_K, lis_dlcu_029_02_base_PP1_K"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Mat_Glow": // "T_MainTex_D, T_MainTex_D"
                //    mat.Shaders.Add(color);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "FABRIC 1_FRONT_1830": // No textures given
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Material #131": // "7"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "tail": // "T_MainTex_D, EM backhair, T_MainTex_D"
                //    mat.Shaders.Add(albedoEmissive);
                //    mat.Textures = [textureList[0], textureList[1]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "hoodie": // "low poly_defaultMat.001_BaseColor.1001, low poly_defaultMat.001_Roughness.1001, "
                //    mat.Shaders.Add(albedoRoughness);
                //    mat.Textures = [textureList[0], textureList[1]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Face": // "googleface, googleface"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Material #98": // "Shorts_bake_Merge, Shorts_Normal_OpenGL"
                //    mat.Shaders.Add(albedoNormal);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Material.002": // Empty setup
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                //case "metal.002": // Empty setup
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                //case "Body": // "Body, Body"
                //    mat.Shaders.Add(albedo);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "RIGHT_EYE": // "Eye_5, right eye by nanna, Eye_5"
                //    mat.Shaders.Add(color);
                //    mat.Textures = [textureList[0]];
                //    MakeDefaultParameters(mat);
                //    break;

                //case "TEETH___SOCK": // "T_MainTex_D, T_MainTex_D"
                //    mat.Shaders.Add(color);
                //    MakeDefaultParameters(mat);
                //    break;

                default:
                    // Default material setup - use textured deferred if we have valid albedo textures
                    if (textureList.Length > 0 && textureList[0] is not null)
                    {
                        mat.Shaders.Add(albedo);
                        mat.Textures = [textureList[0]];
                    }
                    else
                    {
                        mat.Shaders.Add(color);
                    }
                    MakeDefaultParameters(mat);
                    break;
            }
            mat.Name = name;
            // Set a default render pass (opaque deferred lighting in this example)
            mat.RenderPass = (int)EDefaultRenderPass.OpaqueDeferred;
        }
        public static XRTexture2D CreateHardcodedTexture(string path)
        {
            Dictionary<string, string> pathRemap = new()
            {
                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Adidas_Superstar\\BLACK\\BLACK.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Adidas_Superstar\\BLACK\\BLACK.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Adidas_Superstar\\NORMAL.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Adidas_Superstar\\NORMAL.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Adidas_Superstar\\METALIC.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Adidas_Superstar\\METALIC.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Adidas_Superstar\\Regular_Roughness.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Adidas_Superstar\\Regular_Roughness.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\1\\T_MainTex_D.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\T_MainTex_D.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Leather High Boots Extended\\Leather High Boots Extended\\2k_base\\BaseColor.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Leather High Boots Extended\\Leather High Boots Extended\\2k_base\\BaseColor.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Shoes\\Leather High Boots Extended\\Leather High Boots Extended\\2k_base\\Roughness.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Shoes\\Leather High Boots Extended\\Leather High Boots Extended\\2k_base\\Roughness.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\T_MainTex_D.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\T_MainTex_D.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\generator5.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\generator5.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\ears emiss.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\ears emiss.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Underwear\\Female Bombshell Bra\\Female Bombshell Bra\\Texture_Valentines Bra Black Lace trans.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Underwear\\Female Bombshell Bra\\Female Bombshell Bra\\Texture_Valentines Bra Black Lace trans.png"
                },

                {
                    "D:\\Documents\\Avatar2\\Assets\\Zafira Model By Luuy\\Tex\\lis_dlcu_029_02_base_PP1_K.png",
                    ""
                },

                {
                    "D:\\Documents\\Avatar2\\Assets\\Zafira Model By Luuy\\Tex\\Hair1.png",
                    ""
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Tops\\Shawty hoodie - Zinpia\\7.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Tops\\Shawty hoodie - Zinpia\\7.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Hair\\BedHead v2 by Nessy\\Textures\\61.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Hair\\HairPack WetCat\\Textures\\61.png"
                },

                {
                    "D:\\Documents\\Avatar2\\Assets\\Zafira Model By Luuy\\Tex\\hairglow-mono_emission.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\R\\Avatar-Lovelylove-Asset-bundle-2.file_ad87b39f-eb28-49ba-bae7-ab7bc0f312fc.1.vrca\\Assets\\Texture2D\\hairglow-mono_emission 1.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\Misc\\Main\\X\\Val\\Jax.fbm\\Eye_5.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\Eye_5.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\Misc\\Main\\X\\Val\\Texture2D\\Body.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Texture2D\\Body.png" },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\left eye by nanna.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\left eye by nanna.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\EM backhair.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\EM backhair.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Hair\\Bedhead by Nessy\\Textures\\No Saturation 01.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Textures\\Cici Hair\\No Saturation 01.png"
                },

                {
                    "D:\\Documents\\Avatar2\\Assets\\Main\\Avatars\\MAD LOVE\\Materials\\Textures\\HairEarTail Texture.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Texture2D\\HairEarTail Texture.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\Misc\\Main\\X\\Val\\Jax.fbm\\googleface.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\googleface.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Tops\\panda split dye hoodie by clally#6969\\split dye hoodie for panda.fbm\\low poly_defaultMat.001_BaseColor.1001.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Tops\\panda split dye hoodie by clally#6969\\split dye hoodie for panda.fbm\\low poly_defaultMat.001_BaseColor.1001.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Tops\\panda split dye hoodie by clally#6969\\split dye hoodie for panda.fbm\\low poly_defaultMat.001_Roughness.1001.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Tops\\panda split dye hoodie by clally#6969\\split dye hoodie for panda.fbm\\low poly_defaultMat.001_Roughness.1001.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\Arm matcaps.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\Arm matcaps.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Hair\\BedHead v2 by Nessy\\Textures\\51.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Hair\\Jen by Nessy\\Textures\\51.png"
                },

                {
                    "D:\\Documents\\Avatar2\\Assets\\Main\\Rips\\worker_lXgVip0x3vX06jqcB6_zGr9UoSbJw1C1PGuPZ-tmp1\\Assets\\Texture2D\\T_MainTex_D.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\T_MainTex_D.png"
                },

                {
                    "C:\\Users\\black\\OneDrive\\Desktop\\misc\\..\\..\\..\\VRChat Assets\\Hair\\Bedhead by Nessy\\Textures\\No Saturation 06 (1).png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\VRChat Assets\\Textures\\Cici Hair\\No Saturation 06.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\VRChat Assets\\Pants\\Shorts by Zeit\\Shorts_By_Zeit_rar\\Shorts_bake_Merge.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Jax VRM Export\\Jax VRM2.Textures\\Shorts_bake_Merge.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\VRChat Assets\\Pants\\Shorts by Zeit\\Shorts_By_Zeit_rar\\Shorts_Normal_OpenGL.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\! Saint By Hate\\Textures\\Shorts_Normal_OpenGL.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\right eye by nanna.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\Misc\\Main\\X\\Val\\Jax.fbm\\right eye by nanna.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\VRChat Assets\\Pants\\Shorts by Zeit\\Shorts_By_Zeit_rar\\Shorts_bake_Merge_metal.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\!Textures\\Split By Yumiko\\Shorts_bake_Merge_metal.png"
                },

                {
                    "L:\\CustomAvatars2\\Assets\\VRChat Assets\\Pants\\Shorts by Zeit\\Shorts_By_Zeit_rar\\Metal_Normal_OpenGL.png",
                    "C:\\Users\\black\\OneDrive\\Documents\\VRC-Avatars\\Assets\\JaxVRCToolkit_Autogenerated\\AshOld\\Textures\\Metal_Normal_OpenGL.png"
                }
            };

            if (!File.Exists(path) && pathRemap.TryGetValue(path, out string? newPath) && !string.IsNullOrEmpty(newPath))
                path = newPath;

            var tex = Engine.Assets.Load<XRTexture2D>(path);
            if (tex is null)
            {
                Debug.Out($"Failed to load texture: {path}");
                tex = new XRTexture2D()
                {
                    Name = Path.GetFileNameWithoutExtension(path),
                    MagFilter = ETexMagFilter.Linear,
                    MinFilter = ETexMinFilter.Linear,
                    UWrap = ETexWrapMode.Repeat,
                    VWrap = ETexWrapMode.Repeat,
                    AlphaAsTransparency = true,
                    AutoGenerateMipmaps = true,
                    Resizable = true,
                };
            }
            else
            {
                //Debug.Out($"Loaded texture: {path}");
                tex.MagFilter = ETexMagFilter.Linear;
                tex.MinFilter = ETexMinFilter.Linear;
                tex.UWrap = ETexWrapMode.Repeat;
                tex.VWrap = ETexWrapMode.Repeat;
                tex.AlphaAsTransparency = true;
                tex.AutoGenerateMipmaps = true;
                tex.Resizable = false;
                tex.SizedInternalFormat = ESizedInternalFormat.Rgba8;
            }
            return tex;
        }
        #endregion

        private static void MakeDefaultParameters(XRMaterial mat)
            => mat.Parameters =
            [
                new ShaderVector3(new Vector3(1.0f, 1.0f, 1.0f), "BaseColor"),
                new ShaderFloat(1.0f, "Opacity"),
                new ShaderFloat(1.0f, "Roughness"),
                new ShaderFloat(0.0f, "Metallic"),
                new ShaderFloat(0.0f, "Specular"),
                new ShaderFloat(0.0f, "Emission"),
            ];
    }
}
