using XREngine.Data.Rendering;
using XREngine.Rendering.API.Rendering.OpenXR;
using XREngine.Rendering.Occlusion;
using XREngine.Rendering.Vulkan;

namespace XREngine.Rendering;

/// <summary>
/// Scalar fallback values used by <see cref="RuntimeRenderingHostServices"/> when no concrete host is installed.
/// </summary>
public static class RuntimeRenderingHostServiceDefaults
{
    public const bool AllowShaderPipelines = false;
    public const bool EnableExactTransparencyTechniques = false;
    public const bool UseInterleavedMeshBuffer = false;
    public const bool UseIntegerUniformsInShaders = false;
    public const bool RemapBlendshapeDeltas = false;
    public const bool AllowBlendshapes = true;
    public const bool PopulateVertexDataInParallel = true;
    public const bool ProcessMeshImportsAsynchronously = false;
    public const bool AllowSkinning = true;
    public const bool CalculateSkinningInComputeShader = false;
    public const bool CalculateBlendshapesInComputeShader = false;
    public const bool EnableBlendshapePrecombinePass = false;
    public const bool EnableBlendshapePrecombineForDirectVertexPath = true;
    public const bool EnableBlendshapePcaBasisCompression = false;
    public const int BlendshapePrecombineComputeMinActiveShapes = 8;
    public const int BlendshapePrecombineDirectMinActiveShapes = 8;
    public const int BlendshapePrecombineMinAffectedVertices = 1024;
    public const int ShaderConfigVersion = 0;
    public const ERenderClipSpaceYDirection ClipSpaceYDirection = ERenderClipSpaceYDirection.YUp;
    public const ERenderClipDepthRange ClipDepthRange = ERenderClipDepthRange.ZeroToOne;
    public const bool AllowBinaryProgramCaching = true;
    public const bool AsyncProgramBinaryUpload = true;
    public const bool AsyncProgramCompilation = true;
    public const int OpenGLProgramCompileLinkWorkerCount = 1;
    public const int MaxAsyncShaderProgramsPerFrame = 16;
    public const EOpenGLShaderLinkStrategy OpenGLShaderLinkStrategy = EOpenGLShaderLinkStrategy.Auto;
    public const int OpenGLShaderCompilerThreadCount = 1;
    public const bool OpenGLParallelShaderCompileProbeEnabled = true;
    public const int OpenGLParallelShaderCompileProbeTimeoutMs = 25;
    public const EVulkanAllocatorBackend VulkanAllocatorBackend = EVulkanAllocatorBackend.Vma;
    public const EVulkanSynchronizationBackend VulkanSynchronizationBackend = EVulkanSynchronizationBackend.Sync2;
    public const EVulkanDescriptorUpdateBackend VulkanDescriptorUpdateBackend = EVulkanDescriptorUpdateBackend.Template;
    public const bool VulkanDynamicUniformBufferEnabled = true;
    public const bool EnableVulkanBindlessMaterialTable = true;
    public const bool EnableVulkanDescriptorIndexing = true;
    public const bool ValidateVulkanDescriptorContracts = true;
    public const EVulkanBindlessMaterialMode VulkanBindlessMaterialMode = EVulkanBindlessMaterialMode.Auto;
    public const EVulkanGeometryFetchMode VulkanGeometryFetchMode = EVulkanGeometryFetchMode.Atlas;
    public const EVulkanRenderTargetMode VulkanRenderTargetMode = EVulkanRenderTargetMode.Auto;
    public const EVulkanGpuDrivenProfile VulkanGpuDrivenProfile = EVulkanGpuDrivenProfile.Auto;
    public const EVulkanQueueOverlapMode VulkanQueueOverlapMode = EVulkanQueueOverlapMode.Auto;

    public const bool IsRenderThread = true;
    public const bool IsRendererActive = false;
    public const bool IsShadowPass = false;
    public const bool IsStereoPass = false;
    public const bool IsSceneCapturePass = false;
    public const bool RenderCullingVolumesEnabled = false;
    public const bool IsNvidia = false;
    public const float DefaultLuminanceX = 0.2126f;
    public const float DefaultLuminanceY = 0.7152f;
    public const float DefaultLuminanceZ = 0.0722f;
    public const double DefaultDeltaSeconds = 0.0;
    public const long DefaultTimestampTicks = 0L;
    public const long DefaultTrackedVramBytes = 0L;
    public const long DefaultTrackedVramBudgetBytes = long.MaxValue;
    public const bool EnableGpuIndirectDebugLogging = false;
    public const EOcclusionCullingMode GpuOcclusionCullingMode = EOcclusionCullingMode.GpuHiZ;
    public const int CpuQueryOcclusionRetestPeriodFrames = 6;
    public const int CpuQueryOcclusionMaxQueriesPerFrame = 64;
    public const float CpuQueryOcclusionVisibleDemotionBudgetFraction = 0.25f;
    public const int CpuQueryOcclusionRecoveryMinCadenceFrames = 2;
    public const float CpuQueryOcclusionSmallMotionMeters = 0.02f;
    public const float CpuQueryOcclusionMediumMotionMeters = 0.25f;
    public const float CpuQueryOcclusionLargeMotionMeters = 2.0f;
    public const float CpuQueryOcclusionCameraCutMeters = 12.0f;
    public const float CpuQueryOcclusionSmallRotationDegrees = 1.0f;
    public const float CpuQueryOcclusionMediumRotationDegrees = 5.0f;
    public const float CpuQueryOcclusionLargeRotationDegrees = 15.0f;
    public const float CpuQueryOcclusionCameraCutRotationDegrees = 55.0f;
    public const float CpuQueryOcclusionVrHeadMotionMeters = 0.25f;
    public const float CpuQueryOcclusionVrHeadRotationDegrees = 20.0f;
    public const ECpuQueryStereoMode CpuQueryOcclusionStereoMode = ECpuQueryStereoMode.PerEyeSequential;
    public const int CpuQueryOcclusionMaxPendingFrames = 6;
    public const bool EnableCpuSoftwareOcclusionCulling = false;
    public const int CpuSocBufferWidth = 256;
    public const int CpuSocBufferHeight = 128;
    public const int CpuSocOccluderTriangleBudget = 5000;
    public const int CpuSocMaxOccluders = 64;
    public const float CpuSocMinOccluderScreenArea = 0.005f;
    public const bool CpuSocUseAvx2 = true;
    public const bool CpuSocDebugVisualization = false;
    public const bool CpuSocDebugForceVisible = false;
    public const ECpuSceneCullingStructure CpuSceneCullingStructure = ECpuSceneCullingStructure.Bvh;
    public const bool IsPlayModeTransitioning = false;
    public const string PlayModeStateName = "Stopped";
    public const uint DefaultMsaaSampleCount = 1u;
    public const bool DefaultOutputHDR = false;
    public const float DefaultTsrRenderScale = 1.0f;
    public const bool EnableRenderStatisticsTracking = true;
    public const bool EnableGpuRenderPipelineProfiling = false;
    public const bool GpuRenderPipelineTimingsReady = false;
    public const double GpuRenderPipelineFrameMs = 0.0;
    public const ulong CurrentRenderFrameId = 0UL;
    public const ETwoPlayerPreference TwoPlayerViewportPreference = ETwoPlayerPreference.SplitHorizontally;
    public const EThreePlayerPreference ThreePlayerViewportPreference = EThreePlayerPreference.PreferFirstPlayer;
    public const RuntimeGraphicsApiKind CurrentRenderBackend = RuntimeGraphicsApiKind.Unknown;
    public const EAntiAliasingMode DefaultAntiAliasingMode = EAntiAliasingMode.None;
    public const XRCamera.EDepthMode SceneCameraDepthModePreference = XRCamera.EDepthMode.Normal;

    public const bool ProvidesShadowAtlasSettings = false;
    public const bool UseSpotShadowAtlas = true;
    public const bool UseDirectionalShadowAtlas = true;
    public const bool UsePointShadowAtlas = true;
    public const uint ShadowAtlasPageSize = 4096u;
    public const int MaxShadowAtlasPages = 1;
    public const long MaxShadowAtlasMemoryBytes = 0L;
    public const int MaxShadowTilesRenderedPerFrame = 16;
    public const float MaxShadowRenderMilliseconds = 2.0f;
    public const uint MinShadowAtlasTileResolution = 128u;
    public const uint MaxShadowAtlasTileResolution = 4096u;

    public const string AssetFileExtension = "asset";
    public const TextureRuntimeLogMode TextureLogMode = TextureRuntimeLogMode.Summary;
    public const double TextureSlowCpuDecodeResizeMilliseconds = 5.0;
    public const double TextureSlowMipBuildMilliseconds = 5.0;
    public const double TextureSlowUploadChunkMilliseconds = 2.0;
    public const double TextureSlowTransitionMilliseconds = 8.0;
    public const double TextureSlowQueueWaitMilliseconds = 100.0;
    public const double TextureUploadFrameBudgetMilliseconds = 2.0;
    public const string SparseTextureStreamingUnsupportedReason = "No renderer-specific sparse texture capability service is configured.";
    public const string SparseTextureStreamingFinalizeNotConfiguredReason = "RuntimeRenderingHostServices.Current has not been configured for sparse texture finalization.";
    public const string JobSchedulingNotConfiguredMessage = "RuntimeRenderingHostServices.Current has not been configured for job scheduling.";

    public const string RendererCreationNotConfiguredMessage = "RuntimeRenderingHostServices.Current has not been configured to create renderers.";
    public const bool IsWindowScenePanelPresentationEnabled = false;
    public const EInteractiveWindowResizeStrategy InteractiveResizeStrategy = EInteractiveWindowResizeStrategy.Default;
    public const int ScenePanelResizeDebounceMs = 100;
    public const bool ForceFullViewport = false;

    public const bool RenderWindowsWhileInVR = false;
    public const bool EnableOpenXrVulkanParallelRendering = true;
    public const EVrViewRenderMode VrViewRenderMode = EVrViewRenderMode.SequentialViews;
    public const EVrMirrorMode VrMirrorMode = EVrMirrorMode.BlitSubmittedEye;
    public const float VrOutputTargetRateHz = 0.0f;
    public const bool VrDesktopAutoSkipWhenOverBudget = true;
    public const bool EnableVrFoveatedViewSet = false;
    public const EVrFoveationMode VrFoveationMode = EVrFoveationMode.Off;
    public const EVrFoveationQualityPreset VrFoveationQualityPreset = EVrFoveationQualityPreset.Balanced;
    public const bool VrFoveationRequireRequested = false;
    public const EOpenXrEyeResolutionPreset OpenXrEyeResolutionPreset = EOpenXrEyeResolutionPreset.RuntimeRecommended;
    public const float OpenXrEyeResolutionScale = 1.0f;
    public const uint OpenXrCustomEyeResolutionWidth = 0u;
    public const uint OpenXrCustomEyeResolutionHeight = 0u;
    public const bool IsInVR = false;
    public const bool IsOpenXRActive = false;
    public const bool VrMirrorComposeFromEyeTextures = false;
    public const bool VrCopyEyePreviewTextures = false;
    public const float VrFoveationCenterU = 0.5f;
    public const float VrFoveationCenterV = 0.5f;
    public const float VrFoveationInnerRadius = 0.35f;
    public const float VrFoveationOuterRadius = 0.85f;
    public const float VrFoveationInnerShadingRate = 1.0f;
    public const float VrFoveationMiddleShadingRate = 0.7f;
    public const float VrFoveationOuterShadingRate = 0.5f;
    public const float VrFoveationVisibilityMargin = 0.05f;
    public const bool VrFoveationForceFullResForUiAndNearField = true;
    public const float VrFoveationFullResNearDistanceMeters = 1.5f;
    public const bool OpenXrCullWithFrustum = true;
    public const bool OpenXrDebugGl = false;
    public const bool OpenXrDebugClearOnly = false;
    public const bool OpenXrDebugLifecycle = false;
    public const bool OpenXrDebugRenderRightThenLeft = false;
    public const bool OpenXrPrepareFrameAfterDesktopRender = true;
    public const OpenXRAPI.OpenXrRenderPacingMode OpenXrRenderPacingMode = OpenXRAPI.OpenXrRenderPacingMode.DedicatedThread;
    public const float OpenXrDeadlineSafetyMarginMs = 1.0f;
    public const float OpenXrCollectVisibleFrustumPaddingDegrees = 2.0f;

    public const bool IsViewportCurrentlyRendering = false;
    public const bool ShouldForceDebugOpaquePipeline = false;
    public const int FallbackBytesPerPixel = 4;
}
