using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using ImGuiNET;
using XREngine;
using XREngine.Core.Files;
using XREngine.Rendering.Models;

namespace XREngine.Editor.AssetEditors;

public sealed class SubMeshInspector : IXRAssetInspector
{
    private static readonly Vector4 DirtyBadgeColor = new(0.95f, 0.65f, 0.2f, 1f);
    private static readonly Vector4 SectionLabelColor = new(0.85f, 0.85f, 0.85f, 1f);

    public void DrawInspector(EditorImGuiUI.InspectorTargetSet targets, HashSet<object> visitedObjects)
    {
        var subMeshes = targets.Targets.OfType<SubMesh>().Cast<object>().ToList();
        if (subMeshes.Count == 0)
        {
            foreach (var asset in targets.Targets.OfType<XRAsset>())
                EditorImGuiUI.DrawDefaultAssetInspector(asset, visitedObjects);
            return;
        }

        if (targets.HasMultipleTargets)
        {
            EditorImGuiUI.DrawDefaultAssetInspector(new EditorImGuiUI.InspectorTargetSet(subMeshes, targets.CommonType), visitedObjects);
            return;
        }

        var sub = (SubMesh)subMeshes[0];

        DrawHeader(sub);
        DrawBoundsSummary(sub);
        DrawLODList(sub);
        DrawAdvancedSection(sub, visitedObjects);
    }

    private static void DrawHeader(SubMesh sub)
    {
        ImGui.TextUnformatted(GetDisplayName(sub));
        string path = sub.FilePath ?? "<unsaved asset>";
        ImGui.TextDisabled(path);

        if (sub.IsDirty)
        {
            ImGui.SameLine();
            ImGui.TextColored(DirtyBadgeColor, "Modified");
        }

        ImGui.Separator();
    }

    private static string GetDisplayName(SubMesh sub)
    {
        if (!string.IsNullOrWhiteSpace(sub.Name))
            return sub.Name!;
        if (!string.IsNullOrWhiteSpace(sub.FilePath))
            return Path.GetFileName(sub.FilePath) ?? sub.GetType().Name;
        return sub.GetType().Name;
    }

    private static void DrawBoundsSummary(SubMesh sub)
    {
        ImGui.TextColored(SectionLabelColor, "Bounds");
        ImGui.Spacing();

        var b = sub.Bounds;
        ImGui.TextUnformatted($"Min: {FormatVector(b.Min)}");
        ImGui.TextUnformatted($"Max: {FormatVector(b.Max)}");
        ImGui.TextUnformatted($"Size: {FormatVector(b.Max - b.Min)}");

        if (sub.CullingBounds is { } cb)
        {
            ImGui.Spacing();
            ImGui.TextDisabled("Culling override:");
            ImGui.TextUnformatted($"Min: {FormatVector(cb.Min)}");
            ImGui.TextUnformatted($"Max: {FormatVector(cb.Max)}");
        }

        if (sub.RootBone is { } bone)
            ImGui.TextUnformatted($"Root Bone: {bone.Name ?? bone.GetType().Name}");

        ImGui.Separator();
    }

    private static void DrawLODList(SubMesh sub)
    {
        var lods = sub.LODs;
        ImGui.TextColored(SectionLabelColor, $"LODs ({lods.Count})");
        ImGui.Spacing();

        if (lods.Count == 0)
        {
            ImGui.TextDisabled("No LODs configured.");
            ImGui.Separator();
            return;
        }

        int i = 0;
        foreach (var lod in lods)
        {
            string label = $"LOD {i} - max visible {lod.MaxVisibleDistance:F2}##SubMeshLod_{i}";
            if (ImGui.TreeNode(label))
            {
                string meshName = lod.Mesh is null
                    ? "<none>"
                    : (!string.IsNullOrWhiteSpace(lod.Mesh.Name) ? lod.Mesh.Name! : lod.Mesh.GetType().Name);
                string matName = lod.Material is null
                    ? "<none>"
                    : (!string.IsNullOrWhiteSpace(lod.Material.Name) ? lod.Material.Name! : lod.Material.GetType().Name);

                ImGui.TextUnformatted($"Mesh: {meshName}");
                ImGui.TextUnformatted($"Material: {matName}");

                float maxDist = lod.MaxVisibleDistance;
                if (ImGui.DragFloat($"Max Visible Distance##lod_{i}", ref maxDist, 0.1f, 0f, float.MaxValue))
                    lod.MaxVisibleDistance = maxDist;

                bool genAsync = lod.GenerateAsync;
                if (ImGui.Checkbox($"Generate Async##lod_{i}", ref genAsync))
                    lod.GenerateAsync = genAsync;

                if (lod.IsAutoGenerated)
                {
                    ImGui.TextDisabled("Auto-generated LOD");
                    ImGui.TextDisabled($"Target index ratio: {lod.GeneratedTargetIndexRatio:F3}");
                    ImGui.TextDisabled($"Normalized error: {lod.GeneratedNormalizedError:F4}");
                    ImGui.TextDisabled($"Object-space error: {lod.GeneratedObjectSpaceError:F4}");
                }

                ImGui.TreePop();
            }
            i++;
        }

        ImGui.Separator();
    }

    private static void DrawAdvancedSection(SubMesh sub, HashSet<object> visitedObjects)
    {
        if (!ImGui.CollapsingHeader("Raw Properties"))
            return;

        ImGui.PushID("SubMeshRawProperties");
        EditorImGuiUI.DrawDefaultAssetInspector(sub, visitedObjects);
        ImGui.PopID();
    }

    private static string FormatVector(Vector3 v) => $"({v.X:F3}, {v.Y:F3}, {v.Z:F3})";
}
