[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Animation.AnimationClip), "xre.animation.clip", 2)]
[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Animation.BlendTree1D), "xre.animation.blend-tree-1d", 2)]
[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Animation.BlendTree2D), "xre.animation.blend-tree-2d", 2)]
[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Animation.BlendTreeDirect), "xre.animation.blend-tree-direct", 2)]
[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Animation.AnimStateMachine), "xre.animation.state-machine", 2)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Animation.AnimationClip), XREngine.ERuntimeCookedAssetCodec.AnimationClipModel)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Animation.BlendTree1D), XREngine.ERuntimeCookedAssetCodec.BlendTree1DModel)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Animation.BlendTree2D), XREngine.ERuntimeCookedAssetCodec.BlendTree2DModel)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Animation.BlendTreeDirect), XREngine.ERuntimeCookedAssetCodec.BlendTreeDirectModel)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Animation.AnimStateMachine), XREngine.ERuntimeCookedAssetCodec.AnimStateMachineModel)]
