[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Rendering.XRTexture2D), "xre.rendering.texture-2d", 1)]
[assembly: XREngine.RuntimeTypeContract(typeof(XREngine.Rendering.XRMesh), "xre.rendering.mesh", 1)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Rendering.XRMesh), XREngine.ERuntimeCookedAssetCodec.CookedBinaryMesh)]
[assembly: XREngine.RuntimeCookedAsset(typeof(XREngine.Rendering.XRTexture2D), XREngine.ERuntimeCookedAssetCodec.TextureStreaming)]
[assembly: XREngine.RuntimeClosedFormatter(typeof(System.Numerics.Vector2[]))]
[assembly: XREngine.RuntimeClosedFormatter(typeof(System.Numerics.Vector2[][]))]
[assembly: XREngine.RuntimeClosedFormatter(typeof(System.Numerics.Vector3[]))]
[assembly: XREngine.RuntimeClosedFormatter(typeof(System.Numerics.Vector4[]))]
[assembly: XREngine.RuntimeClosedFormatter(typeof(System.Numerics.Vector4[][]))]
