#!/usr/bin/env python3
"""Emit the browser's explicit, versioned factory table from its allow-list manifest.

No source tree inspection or assembly scanning is involved. New types require a deliberate
change to both the manifest and the known signatures below.
"""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "XREngine.Browser/browser-registration-manifest.json"
OUTPUT = ROOT / "XREngine.Browser/BrowserStaticRegistrations.g.cs"
KNOWN = {
    "components": {
        "xre.browser.v1.component.scene-boot": "XREngine.Browser.SceneBootComponent",
        "xre.browser.v1.component.mesh": "XREngine.Browser.BrowserMeshComponent",
        "xre.browser.v1.component.spin": "XREngine.Browser.BrowserSpinComponent",
    },
    "transforms": {"xre.browser.v1.transform.trs": "XREngine.Scene.Transforms.Transform"},
    "resources": {
        "xre.browser.v1.resource.mesh": "XREngine.Rendering.BrowserMeshData",
        "xre.browser.v1.resource.texture-rgba8": "XREngine.Rendering.BrowserTextureData",
        "xre.browser.v1.resource.material-unlit": "XREngine.Rendering.BrowserMaterialData",
        "xre.browser.v1.resource.scene-snapshot": "XREngine.Rendering.BrowserSceneSnapshot",
    },
    "serializers": {"xre.browser.v1.serializer.scene-json": "XREngine.Rendering.BrowserSceneSnapshot"},
    "modules": {"xre.browser.v1.module.webgpu": "XREngine.Rendering.WebGPU.WebGpuRendererBackendModule"},
}


def main():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest != {"schema": "xre.browser.registrations.v1", **KNOWN}:
        raise ValueError("Registration manifest differs from the approved browser type/signature allow-list")
    # The scene snapshot is both a resource and the single approved wire serializer.
    lines = [
        "// <auto-generated />",
        "// Generated by Tools/Generate-BrowserRegistrations.py from XREngine.Browser/browser-registration-manifest.json.",
        "#nullable enable",
        "using System.Numerics;",
        "using XREngine.Components;",
        "using XREngine.Rendering;",
        "using XREngine.Rendering.WebGPU;",
        "using XREngine.Scene;",
        "using XREngine.Scene.Transforms;",
        "",
        "namespace XREngine.Browser;",
        "",
        "/// <summary>Explicit factories and stable IDs for the portable browser scene format.</summary>",
        "internal static class BrowserStaticRegistrations",
        "{",
        '    internal const string MeshComponentId = "xre.browser.v1.component.mesh";',
        '    internal const string SpinComponentId = "xre.browser.v1.component.spin";',
        '    internal const string SceneBootComponentId = "xre.browser.v1.component.scene-boot";',
        '    internal const string TransformId = "xre.browser.v1.transform.trs";',
        '    internal const string MeshId = "xre.browser.v1.resource.mesh";',
        '    internal const string TextureId = "xre.browser.v1.resource.texture-rgba8";',
        '    internal const string MaterialId = "xre.browser.v1.resource.material-unlit";',
        '    internal const string SnapshotId = "xre.browser.v1.resource.scene-snapshot";',
        '    internal const string SceneJsonId = "xre.browser.v1.serializer.scene-json";',
        '    internal const string WebGpuModuleId = "xre.browser.v1.module.webgpu";',
        "",
        "    internal static void Initialize()",
        "        => TransformFactoryRegistry.Register<Transform>(static () => new Transform());",
        "",
        "    internal static string GetRequiredTypeId(Type type)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(type);",
        "        return type == typeof(BrowserMeshComponent) ? MeshComponentId :",
        "            type == typeof(BrowserSpinComponent) ? SpinComponentId :",
        "            type == typeof(SceneBootComponent) ? SceneBootComponentId :",
        "            type == typeof(Transform) ? TransformId :",
        "            type == typeof(BrowserMeshData) ? MeshId :",
        "            type == typeof(BrowserTextureData) ? TextureId :",
        "            type == typeof(BrowserMaterialData) ? MaterialId :",
        "            type == typeof(BrowserSceneSnapshot) ? SnapshotId :",
        "            type == typeof(WebGpuRendererBackendModule) ? WebGpuModuleId :",
        '            throw new NotSupportedException($"Type {type} is not included in the browser profile.");',
        "    }",
        "",
        "    internal static Type ResolveRequiredType(string id) => id switch",
        "    {",
    ]
    for category in ("components", "transforms", "resources", "modules"):
        for id, name in sorted(KNOWN[category].items()):
            lines.append(f'        "{id}" => typeof(global::{name}),')
    lines += [
        '        _ => throw new NotSupportedException($"Browser type ID {id} is unknown or unsupported.")',
        "    };",
        "",
        "    internal static XRComponent AddRequiredComponent(string id, SceneNode node)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(node);",
        "        XRComponent? component = id switch",
        "        {",
        "            MeshComponentId => node.AddComponent(static () => new BrowserMeshComponent()),",
        "            SpinComponentId => node.AddComponent(static () => new BrowserSpinComponent()),",
        "            SceneBootComponentId => node.AddComponent(static () => new SceneBootComponent()),",
        '            _ => throw new NotSupportedException($"Browser component ID {id} is unknown or unsupported.")',
        '        };',
        '        return component ?? throw new InvalidOperationException("Browser component creation failed.");',
        "    }",
        "",
        "    internal static TransformBase CreateRequiredTransform(string id)",
        "    {",
        "        if (id != TransformId)",
        '            throw new NotSupportedException($"Browser transform ID {id} is unknown or unsupported.");',
        "        Initialize();",
        "        return TransformFactoryRegistry.TryCreate(typeof(Transform), out TransformBase? transform)",
        "            ? transform",
        '            : throw new InvalidOperationException("Browser transform factory is unavailable.");',
        "    }",
        "",
        "    internal static BrowserMeshData CreateMesh(string id, ReadOnlySpan<float> vertices, ReadOnlySpan<uint> indices)",
        "        => id == MeshId ? new BrowserMeshData(vertices, indices)",
        '            : throw new NotSupportedException($"Browser mesh resource ID {id} is unknown or unsupported.");',
        "",
        "    internal static BrowserTextureData CreateTexture(string id, int width, int height, ReadOnlySpan<byte> rgba)",
        "        => id == TextureId ? new BrowserTextureData(width, height, rgba)",
        '            : throw new NotSupportedException($"Browser texture resource ID {id} is unknown or unsupported.");',
        "",
        "    internal static BrowserMaterialData CreateMaterial(string id, Vector4 tint, BrowserTextureData? texture = null)",
        "        => id == MaterialId ? new BrowserMaterialData(tint, texture)",
        '            : throw new NotSupportedException($"Browser material resource ID {id} is unknown or unsupported.");',
        "",
        "    internal static BrowserSceneSnapshot DeserializeScene(string id, string json)",
        "        => id == SceneJsonId ? BrowserSceneEnvelope.Deserialize(json)",
        '            : throw new NotSupportedException($"Browser serializer ID {id} is unknown or unsupported.");',
        "",
        "    internal static string SerializeScene(string id, BrowserSceneSnapshot scene)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(scene);",
        "        return id == SceneJsonId ? BrowserSceneEnvelope.Serialize(scene)",
        '            : throw new NotSupportedException($"Browser serializer ID {id} is unknown or unsupported.");',
        "    }",
        "",
        "    internal static IRendererBackendModule CreateRendererModule(string id)",
        "        => id == WebGpuModuleId ? new WebGpuRendererBackendModule()",
        '            : throw new NotSupportedException($"Browser renderer module ID {id} is unknown or unsupported.");',
        "}",
    ]
    content = "\n".join(lines) + "\n"
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Browser registrations are stale; regenerate them")
    elif len(sys.argv) == 1:
        OUTPUT.write_text(content, encoding="utf-8")
    else:
        raise SystemExit("usage: Generate-BrowserRegistrations.py [--check]")


if __name__ == "__main__":
    main()
