<Project>
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)Assets/engine-audio.js">
      <Link>wwwroot/engine-audio.js</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
