<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="XREngine.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Sdl2" Version="2.2.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\XREngine.Audio\XREngine.Audio.csproj" />
  </ItemGroup>
</Project>
