namespace XREngine.Audio.Steam;

public enum IPLDirectEffectFlags
{
    IPL_DIRECTEFFECTFLAGS_APPLYDISTANCEATTENUATION = 1 << 0,
    IPL_DIRECTEFFECTFLAGS_APPLYAIRABSORPTION = 1 << 1,
    IPL_DIRECTEFFECTFLAGS_APPLYDIRECTIVITY = 1 << 2,
    IPL_DIRECTEFFECTFLAGS_APPLYOCCLUSION = 1 << 3,
    IPL_DIRECTEFFECTFLAGS_APPLYTRANSMISSION = 1 << 4
}