namespace XREngine.Audio.Steam;

public enum IPLDistanceAttenuationModelType
{
    IPL_DISTANCEATTENUATIONTYPE_DEFAULT,
    IPL_DISTANCEATTENUATIONTYPE_INVERSEDISTANCE,
    IPL_DISTANCEATTENUATIONTYPE_CALLBACK
}