namespace XREngine.Audio.Steam;

public enum IPLSIMDLevel
{
    IPL_SIMDLEVEL_SSE2,
    IPL_SIMDLEVEL_SSE4,
    IPL_SIMDLEVEL_AVX,
    IPL_SIMDLEVEL_AVX2,
    IPL_SIMDLEVEL_AVX512,
    IPL_SIMDLEVEL_NEON = IPL_SIMDLEVEL_SSE2
}