namespace XREngine.Audio.Steam;

public enum IPLSpeakerLayoutType
{
    IPL_SPEAKERLAYOUTTYPE_MONO,
    IPL_SPEAKERLAYOUTTYPE_STEREO,
    IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC,
    IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1,
    IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1,
    IPL_SPEAKERLAYOUTTYPE_CUSTOM
}
